### ISSUE TITLE
generics3: Hint assumes knowledge not introduced at this point

### ISSUE THREAD

**Issue by MattOates** [rust-lang/rustlings#1012]
Im looking at generics3s and it feels like it's stepped up a lot. The hint reads as follows:

> To find the best solution to this challenge you're going to need to think back to your
> knowledge of traits, specifically Trait Bound Syntax -  you may also need this: "use std::fmt::Display;"

But traits1 and traits2 haven't been introduced yet at all. Perhaps the order of these tasks needs to change? Or a little more skeleton available in generics3? Is there an assumption someone has already read through the entirety of the Rust book before attempting Rustlings? So far I've been fine just reading along.

**Comment by diannasoreil** [comment]
See #625
