### ISSUE TITLE
Needs more smart pointers exercises

### ISSUE THREAD

**Issue by Pacheco95** [rust-lang/rustlings#1020]
Personally I found the smart pointer topic hardest than others to absorb. I think if I had more exercises, I would understand the concepts quickly. It would be nice if we have exercices covering `Box`, `Rc`, `RefCell` and their asyncronous counterpart.

The current `Box` exercise is too easy. It's just a copy paste from the book's example.

**Comment by exdx** [comment]
I added a Rc exercise in #1069

**Comment by ChanceNCounter** [comment]
> I added a Rc exercise in #1069

The exercise hint reads, “This is a straightforward exercise to use…” and links to a chapter in the book. Until this section, Rustlings was an alternative to the book, and we’ve been referring to docs. I am infuriated.

**Comment by diannasoreil** [comment]
> Until this section, Rustlings was an alternative to the book, and we’ve been referring to docs.

This is not true, Rustlings is meant to work well alongside the book. Tons of exercises link to specific book chapters, there's even an index (`exercises/README.md`) mapping exercise groups to sections of the book.

**Comment by ChanceNCounter** [comment]
I tell you I’m currently going through the exercises, and this is the first time I’ve been forced over to the book. I tell you I am *currently* having this experience and you answer, “This is not true.”

Please be as interested in curating the learning resource hosted at this repo as you seem to be in curating this repo. That was a rude thing to find on top of my inbox.
