### ISSUE TITLE
suggestion: set rust's edition for exercises to 2021

### ISSUE THREAD

**Issue by Jagholin** [rust-lang/rustlings#1022]
The rustlings crate itself has its edition set in Cargo.toml:

> [package]
> name = "rustlings"
> version = "4.7.1"
> authors = ["mokou <mokou@fastmail.com>", "Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]
> edition = "2021"

But for some reason, exercises use a different setting:

https://github.com/rust-lang/rustlings/blob/b19f74e8cfaba7775e8ff2d74cab9cb862fb1473/src/exercise.rs#L124

which is strange, but also confuses rust-analyzer sometimes, because some typings have changed between 2018 and 2021

**Comment by mo8it** [comment]
Already fixed a while ago 😅
