### ISSUE TITLE
Suggestion: Support reseting an exercise

### ISSUE THREAD

**Issue by NicMcPhee** [rust-lang/rustlings#1031]
It might be nice to be able to "reset" an exercise back to the initial state. This could be useful, for example, for people who want to use some of these exercises for "dojo-style" repetitive practice to, e.g., explore different ways of approaching a particular problem.

This could be handled outside of Rustlings through, e.g., your IDE or version control, but in both cases it would be messy to go back and reset an early exercise after having done twenty or thirty subsequent exercises.

I have no idea how complex this would be, but I assume it wouldn't be too bad? Presumably some `git` fun plus some kind of appropriate warning that you'll lose the work you have, etc., etc.

Would anyone else find this useful? Or is this just me being weird… 😜

**Comment by exdx** [comment]
This would be interesting, I imagine the API could be something like `rustlings reset errors5` or something like that. Under the hood, `git stash push <filename>` or something could be applied. 

Seems like a handy feature

**Comment by magnusrodseth** [comment]
I would like to be assigned this issue! 🚀

**Comment by NicMcPhee** [comment]
That's awesome @magnusrodseth – thanks for adding that!

**Comment by VephoVandenberg** [comment]
I wonder if it is possible to reset the whole project. Like rustlings reset all or smth...

**Comment by shadows-withal** [comment]
> I wonder if it is possible to reset the whole project. Like rustlings reset all or smth...

`git checkout tags/LATEST_VERSION` should do the trick, no?
