### ISSUE TITLE
rustlings lsp fails: Unrecognized argument: lsp

### ISSUE THREAD

**Issue by mirao** [rust-lang/rustlings#1036]
https://github.com/rust-lang/rustlings#enabling-rust-analyzer says
![image](https://user-images.githubusercontent.com/12584138/176156291-7089eaed-4b8e-4f39-90d6-2f1d4e3a6c82.png)

but it doesn't work for me:
```bash
~/workspace/rust/rustlings$ rustlings lsp
Unrecognized argument: lsp
```
**Used SW:**

- Ubuntu 22.04
- rustlings v4.7.1
- cargo 1.61.0 (a028ae4 2022-04-29)
- rustc 1.61.0 (fe5b13d68 2022-05-18)

**Comment by mirao** [comment]
Finally I created `rust-project.json` by this tool: https://github.com/jackos/rustlings-fix
CC: @jackos

**Comment by jackos** [comment]
Hi @mirao, apologies the documentation has been updated but the new release hasn't been pushed yet, once @diannasoreil has done that `rustlings lsp` will work

**Comment by mirao** [comment]
> Finally I created rust-project.json by this tool: https://github.com/jackos/rustlings-fix

BTW now IntelliSense (Rust code offering) is working well in VSCode (with `rust-analyzer` extension) for rustlings exercises.
But errors/warnings (underlined by red/yellow) **are not shown** in VSCode editor in `rustlings` project. I would expect it when I save a change in an exercise, a build is triggered and causes an error. Any idea why the errors are not shown?
Note that errors are shown in my Rust projects which I created by `cargo new <project>` and opened by VSCode.

**Comment by diannasoreil** [comment]
Apologies for the unclear documentation, the release will follow tomorrow.

**Comment by jackos** [comment]
@mirao Having a `rust-project.json` at the root overrides the `Cargo.toml` for where `rust-analyzer` looks to parse files, this means the `rustlings` source code will no longer work with rust-analyzer. If you want to re-enable that delete the `rust-project.json`.

**Comment by shadows-withal** [comment]
@umneeq2 what's the output of `rustlings --version`?

**Comment by umneeq2** [comment]
> @umneeq2 what's the output of `rustlings --version`?

v4.6.0
