### ISSUE TITLE
iterators4: unstable library feature used (and not needed)

### ISSUE THREAD

**Issue by brainsik** [rust-lang/rustlings#1042]
Hello. At the top of `iterators4.rs` is:

```rust
use std::slice::range;
```

As of this writing, this is an experimental API ([see docs](https://doc.rust-lang.org/std/slice/fn.range.html)) and causes the compiler to error out:

```
error[E0658]: use of unstable library feature 'slice_range'
 --> exercises/standard_library_types/iterators4.rs:1:5
  |
1 | use std::slice::range;
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76393 <https://github.com/rust-lang/rust/issues/76393> for more information
```

It's not needed for this exercise since you can use the builtin range syntax:

```rust
(1..10)
```

Seems like it should be removed.

**Comment by brainsik** [comment]
Oops. It appears my editor added this in for me when I was looking at the `range` function. Apologies for the diversion.

**Comment by Guaderxx** [comment]
I didn't notice the `range`, so It takes me about 10 minutes try to figure out how to convert `u64` to `Iterator` without new variable. 
Thanks a lot.
