### ISSUE TITLE
rust-analyzer vscode windows not working on rustlings

### ISSUE THREAD

**Issue by chemiadel** [rust-lang/rustlings#1072]
rust-analyzer doesn't seems working on vscode windows, no autocompleting, no hover information.

but it does on another project I have.

**Comment by GersiD** [comment]
How did you get this to work? I am having the same issue.

**Comment by shadows-withal** [comment]
Does this help? https://github.com/rust-lang/rustlings#enabling-rust-analyzer

**Comment by GersiD** [comment]
No sorry I tried that and many many other things to get it to work :/. I will open my own issue so I can provide a bunch of information to make debugging easier.
