### ISSUE TITLE
Solution for hashmaps3 is unclear

### ISSUE THREAD

**Issue by RossBarnie** [rust-lang/rustlings#1074]
Very new to rust so I may be totally wrong on this, very happy to be corrected.

Given the struct `Team` which requires the team's name, and the scores hashmap which requires the team's name, both as `String`s, how can I, as directed by the hint, use `entry()` and `or_insert()`? From the exercise on ownership, and from the compiler error I receive, I can't do both as it leads to a move error.

In the following attempt at the solution, I try to initialise the team if it doesn't exist to a default state using the functions hinted at:

```rust
        let team_1 = scores.entry(team_1_name).or_insert(Team{ name: team_1_name, goals_scored: 0, goals_conceded: 0 });
        team_1.goals_scored += team_1_score;
        team_1.goals_conceded += team_2_score;
```

This leads to the following compiler error, as expected:

```
error[E0382]: use of moved value: `team_1_name`
  --> exercises/hashmaps/hashmaps3.rs:38:70
   |
34 |         let team_1_name = v[0].to_string();
   |             ----------- move occurs because `team_1_name` has type `String`, which does not implement the `Copy` trait
...
38 |         let team_1 = scores.entry(team_1_name).or_insert(Team{ name: team_1_name, goals_scored: 0, goals_conceded: 0 });
   |                                   ----------- value moved here       ^^^^^^^^^^^ value used here after move
```

`entry` requires the type of the key to match, so I can't borrow it, for example:
```rust
let team_1 = scores.entry(&team_1_name).or_insert(Team{ name: team_1_name, goals_scored: 0, goals_conceded: 0 });
```
Results in:
```
error[E0308]: mismatched types
  --> exercises/hashmaps/hashmaps3.rs:38:35
   |
38 |         let team_1 = scores.entry(&team_1_name).or_insert(Team{ name: team_1_name, goals_scored: 0, goals_conceded: 0 });
   |                                   ^^^^^^^^^^^^ expected struct `String`, found `&String`
```

And changing the type of the name in the `Team` struct gives me an error about lifetimes, which is something we haven't covered yet, so feels like I shouldn't be trying to solve this way.

```rust
struct Team {
    name: &String,
```
```
error[E0106]: missing lifetime specifier
  --> exercises/hashmaps/hashmaps3.rs:23:11
   |
23 |     name: &String,
   |           ^ expected named lifetime parameter
   |
help: consider introducing a named lifetime parameter
   |
22 ~ struct Team<'a> {
23 ~     name: &'a String,
   |
```

Am I missing something?

**Comment by Tostapunk** [comment]
Hi, you could use this for example
```
let team_1 = scores.entry(String::from(&team_1_name)).or_insert(...
```
[docs](https://doc.rust-lang.org/std/string/struct.String.html#impl-From%3C%26%27_%20String%3E)

I'm new to Rust too, so maybe there's a better solution.

**Comment by wojexe** [comment]
In my solution, I have used the `.get_mut()` method combined with a `if let` statement. You can check it out [here](https://github.com/wojexe/rustlings-5.0.0-solutions/blob/fe14c3b470210ed1f5a7034440fd19b3944ab833/exercises/hashmaps/hashmaps3.rs#L37). It may be possible to write a prettier solution, but that's what I came up with.

For your solution to work, you have to `clone` the key you pass to the `entry` method. As you can see in the documentation, there is no `&` symbol in the function signature. If you scroll a bit, you can see that the `get()` method consumes a reference to the key. Same for `get_mut()`.

**Comment by Veterangrail** [comment]
> Very new to rust so I may be totally wrong on this, very happy to be corrected.
> 
> Given the struct `Team` which requires the team's name, and the scores hashmap which requires the team's name, both as `String`s, how can I, as directed by the hint, use `entry()` and `or_insert()`? From the exercise on ownership, and from the compiler error I receive, I can't do both as it leads to a move error.
> 
> In the following attempt at the solution, I try to initialise the team if it doesn't exist to a default state using the functions hinted at:
> 
> ```rust
>         let team_1 = scores.entry(team_1_name).or_insert(Team{ name: team_1_name, goals_scored: 0, goals_conceded: 0 });
>         team_1.goals_scored += team_1_score;
>         team_1.goals_conceded += team_2_score;
> ```
> 
> This leads to the following compiler error, as expected:
> 
> ```
> error[E0382]: use of moved value: `team_1_name`
>   --> exercises/hashmaps/hashmaps3.rs:38:70
>    |
> 34 |         let team_1_name = v[0].to_string();
>    |             ----------- move occurs because `team_1_name` has type `String`, which does not implement the `Copy` trait
> ...
> 38 |         let team_1 = scores.entry(team_1_name).or_insert(Team{ name: team_1_name, goals_scored: 0, goals_conceded: 0 });
>    |                                   ----------- value moved here       ^^^^^^^^^^^ value used here after move
> ```
> 
> `entry` requires the type of the key to match, so I can't borrow it, for example:
> 
> ```rust
> let team_1 = scores.entry(&team_1_name).or_insert(Team{ name: team_1_name, goals_scored: 0, goals_conceded: 0 });
> ```
> 
> Results in:
> 
> ```
> error[E0308]: mismatched types
>   --> exercises/hashmaps/hashmaps3.rs:38:35
>    |
> 38 |         let team_1 = scores.entry(&team_1_name).or_insert(Team{ name: team_1_name, goals_scored: 0, goals_conceded: 0 });
>    |                                   ^^^^^^^^^^^^ expected struct `String`, found `&String`
> ```
> 
> And changing the type of the name in the `Team` struct gives me an error about lifetimes, which is something we haven't covered yet, so feels like I shouldn't be trying to solve this way.
> 
> ```rust
> struct Team {
>     name: &String,
> ```
> 
> ```
> error[E0106]: missing lifetime specifier
>   --> exercises/hashmaps/hashmaps3.rs:23:11
>    |
> 23 |     name: &String,
>    |           ^ expected named lifetime parameter
>    |
> help: consider introducing a named lifetime parameter
>    |
> 22 ~ struct Team<'a> {
> 23 ~     name: &'a String,
>    |
> ```
> 
> Am I missing something?

Had same problem solved it here 

Had same issues solved it with
Solve issues with
https://www.wallsolution.xyz/

**Comment by RossBarnie** [comment]
Thanks, I'm happy to close this since we've used `String::from` in previous examples and I should have understood what it was doing before now. You could argue that we need a more explicit "clone" example to really spell it out but I think it's reasonable to expect people to look up what `String::from` does in `strings2` and `strings4`.
