### ISSUE TITLE
test1.rs compiles with 'incorrect' solution when using 'watch' or 'verify'

### ISSUE THREAD

**Issue by phansch** [rust-lang/rustlings#108]
Hi, I'm currently going through the V2 exercises and love it so far!

Is `test1.rs` supposed to 'succeed' already when it compiles successfully?

According to the comment, a function like this should be required:

```rust
fn calculateprice(apples: i32) -> i32 {
    if apples > 40 {
        apples
    } else {
        apples * 2
    }
}
```

However, it currently marks the test as successful when it compiles already:

```rust
fn calculateprice(apples: i32) -> i32 {
    1
}
```

Should this test file perhaps include some unit tests?

**Comment by komaeda** [comment]
when i add this function and individually run the file, i get this result:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/45509655/51750672-12e8eb00-20b3-11e9-9004-c0de7052b63f.png">

could you verify that it's doing the same thing for you?

**Comment by komaeda** [comment]
okay, i'll check it out as soon as i have time!

**Comment by phansch** [comment]
Thanks, I will give it another go next week :+1:

**Comment by aa7955** [comment]
Still doesn't work. Same result.
