### ISSUE TITLE
Run command in exercises.rs triggering antivirus on windows under specific conditions

### ISSUE THREAD

**Issue by ikebenbrown** [rust-lang/rustlings#1091]
Noticed this first with primitive_types2

Here is what the code looks like:
![image](https://user-images.githubusercontent.com/25356792/180016191-7841e8dc-d549-45ca-9e50-158c8f17eb00.png)

Here is the error I am getting in the console:
![image](https://user-images.githubusercontent.com/25356792/180016030-4df5b06a-9b17-4d08-943c-31e95fd62fc2.png)

lines its referencing:
https://github.com/rust-lang/rustlings/blob/fb7dac75a722c681fa0ec77063fc330d6c3e8b99/src/exercise.rs#L182-L185

In addition to this I get a notification from crowd strike saying that it terminated or blocked a process that it thought was malware

It seems to only happen under circumstances where everything compiles and runs exceptionally fast, by adding even the slightest hiccup to primitive_types2 the error no longer occurs.
New Code:
![image](https://user-images.githubusercontent.com/25356792/180017671-3a837dae-88b7-4f6d-b40b-d98152375876.png)
Output:
![image](https://user-images.githubusercontent.com/25356792/180018256-fd4d3e6b-3e51-4415-ac02-3213d05f1b09.png)

Not sure if this is replicable, might be extremely specific to my system configuration, figured I would put it out there anyways.

Also I'm new to this so let me know if I made any mistakes with format/content I included in this Issue.

**Comment by diannasoreil** [comment]
Yeah, sounds like an issue with your specific configuration 😅 Guess Rust is _too_ fast for it

**Comment by ikebenbrown** [comment]
Yeah lol, it's certainly the kind of problem I don't mind having. I think I will close this issue then. Thank you for the work you have put into this project btw, it has been instrumental in my journey towards understanding rust
