### ISSUE TITLE
Advanced Errors exercises are missing in version 5.0.0

### ISSUE THREAD

**Issue by ArthurDanjou** [rust-lang/rustlings#1093]
In the [info.toml](https://github.com/rust-lang/rustlings/blob/main/info.toml) file, the advanced errors exercises are missing

**Comment by diannasoreil** [comment]
Yes, those were removed, at least in the `info.toml`. I don't feel like they currently fit in the curriculum, not even at the very end, so I'm keeping them out until I can think of a better solution.
