### ISSUE TITLE
`rustlings must be run from the rustlings directory`

### ISSUE THREAD

**Issue by vilinski** [rust-lang/rustlings#1097]
Maybe it is just not clear to me.

Noticed the announcement in rust news about 5.0 and instantly tired out on my Mac:

```
curl -L https://raw.githubusercontent.com/rust-lang/rustlings/main/install.sh | bash -s mypath/
```

But then absolutely lost how to start. This is my experience sofar after installing it:

```
~/Projects/rust
❯ rustlings

       welcome to...
                 _   _ _
  _ __ _   _ ___| |_| (_)_ __   __ _ ___
 | '__| | | / __| __| | | '_ \ / _` / __|
 | |  | |_| \__ \ |_| | | | | | (_| \__ \
 |_|   \__,_|___/\__|_|_|_| |_|\__, |___/
                               |___/

/Users/avilinski/.cargo/bin/rustlings must be run from the rustlings directory
Try `cd rustlings/`!

~/Projects/rust
❯ cd rustlings
cd: no such file or directory: rustlings

~/Projects/rust
❯ mkdir rustlings && cd rustlings

Projects/rust/rustlings
❯ rustlings

       welcome to...
                 _   _ _
  _ __ _   _ ___| |_| (_)_ __   __ _ ___
 | '__| | | / __| __| | | '_ \ / _` / __|
 | |  | |_| \__ \ |_| | | | | | (_| \__ \
 |_|   \__,_|___/\__|_|_|_| |_|\__, |___/
                               |___/

/Users/avilinski/.cargo/bin/rustlings must be run from the rustlings directory
Try `cd rustlings/`!

Projects/rust/rustlings
❯
```

Please help ))

**Comment by diannasoreil** [comment]
Since you executed `bash -s mypath/` when installing, your clone of Rustlings will be in the `mypath` directory.

**Comment by vilinski** [comment]
omg, didn't notice this, or imagined its some macOS `mypath` command 🤣 
how can I erase this issue from the earth's face?...

**Comment by marcusradell** [comment]
I had a similar issue and re-read the instructions. I still didn't understand how it was supposed to work based on the readme. I just thought it installed a binary, and then running `rustlings` would give a prompt to create a new folder or something.

This issue gave me the clues needed to run rustlings :-)
