### ISSUE TITLE
Why are Vec problems coming before Struct?

### ISSUE THREAD

**Issue by SAbruzzo** [rust-lang/rustlings#1104]
Hi,

I am following rustlings together with [The Rust Programming Language](https://doc.rust-lang.org/stable/book/#the-rust-programming-language) by Steve Klabnik and Carol Nichols. In this book after slices (chapter 4) come structs (chapter 5). Vectors are only explained in chapter 8. However, in rustlings, after the "primitive_types" section there is the "vecs" section. I would consider reordering that so that after "primitive_types" comes the "structs" section. 

If you are ok with the change I am happy to submit a pull request.

Kind regards,
Silvio

**Comment by diannasoreil** [comment]
Rustlings deviates from the book when we believe it's healthy to do so, and putting vecs significantly further ahead is because lots of the following exercises use vectors (because, frankly, it's _the_ Rust array type). Therefore, this ordering is intentional.
