### ISSUE TITLE
options2: Change exercise so that the output can be tested & add tests

### ISSUE THREAD

**Issue by rubiesonthesky** [rust-lang/rustlings#1109]
I had some problems understanding what is wanted in the exercise options2. I think it would make it clearer if it was changed little bit to make code testable and add test cases to exercise. 

Would you be interested of PR with suggestion how that could be done? In contributing doc, it just talks about new exercises or fixing bugs :)

**Comment by magnusrodseth** [comment]
I would happily contribute to this!

@rubiesonthesky, do you have some concrete examples of what you found hard to understand in `options2`?

**Comment by magnusrodseth** [comment]
@rubiesonthesky Please take a look at my PR #1150 and let me know what you think ☺️
