### ISSUE TITLE
`rustlings watch` does not work

### ISSUE THREAD

**Issue by christiansakai** [rust-lang/rustlings#111]
The command `rustlings watch` does not watch and recompile.

Mac OXS 10.14.1 (Mojave)

**Comment by christiansakai** [comment]
Yes I am, the `rustlings verify` work just fine. The `rustlings watch` just be in some suspended mode and does not recompile. I am using Rust 2018 if that helps

**Comment by komaeda** [comment]
i don't think i can reproduce this :/

**Comment by christiansakai** [comment]
That's ok. Maybe my environment is whacked up. Closing it now.
