### ISSUE TITLE
arc1 question

### ISSUE THREAD

**Issue by Lioness100** [rust-lang/rustlings#1116]
Hello! I have a question regarding `standard-library-types/arc1.rs`. This was my solution, which compiles fine:
```rust
#![forbid(unused_imports)] // Do not change this, (or the next) line.
use std::sync::Arc;
use std::thread;

fn main() {
    let numbers: Vec<_> = (0..100u32).collect();
    let shared_numbers = Arc::new(numbers);
    let mut joinhandles = Vec::new();

    for offset in 0..8 {
        let child_numbers = shared_numbers.clone();
        joinhandles.push(thread::spawn(move || {
            let sum: u32 = child_numbers.iter().filter(|n| *n % 8 == offset).sum();
            println!("Sum of offset {} is {}", offset, sum);
        }));
    }
    for handle in joinhandles.into_iter() {
        handle.join().unwrap();
    }
}
```
However if I remove `Arc::new()` (+ un-forbid unused imports) and just write `let shared_numbers = numbers; // no Arc` it also works fine. So, in this example, why is `Arc` needed?

**Comment by Tostapunk** [comment]
Hi! Here `Arc` (Atomically **Reference** Counted) is needed to avoid any copies of the "numbers" `Vec`.
The [clone trait implementation for Vec](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.clone) returns a copy of the value, while the [clone trait implementation for Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.clone) makes a clone of the `Arc` pointer (so it only increments the reference count).

Rust's convention is to use `Arc::clone` in this case (the same applies to `Rc<T>`), this makes it easier to visually distinguish between the deep-copy kind of clones and the ones that only increase the reference count.

**Comment by Lioness100** [comment]
Oooh, thanks!!
