### ISSUE TITLE
Word wrap is not correct when terminal height > width

### ISSUE THREAD

**Issue by satvikpendem** [rust-lang/rustlings#1118]
I often use VSCode with the terminal to the right side, as `rustlings` exercises wrap at 80 characters, and it looks to me like this, where the word wrapping is strange for `rustlings` output, as it seems to wrap on letters rather than words, and there are newlines that look fine on a terminal where width > height, but it looks strange when this is not the case. Is there a way to change this to wrap words correctly?

![image](https://user-images.githubusercontent.com/42670561/182246734-cc5f0941-ea50-474b-959a-d1e3413f4369.png)

**Comment by diannasoreil** [comment]
If anything, this would be a `rustc` issue, since that seems to be where that's coming from, correct? I'm not aware of an option to change `rustc`'s word wrap settings (if it even has any)

**Comment by satvikpendem** [comment]
Thanks, I'll ask there.
