### ISSUE TITLE
What's the difference between the normal and stable version "The Rust Programming Language" 

### ISSUE THREAD

**Issue by EarthMessenger** [rust-lang/rustlings#1119]
Why do some hints use "https://doc.rust-lang.org/stable/book/" but some use "https://doc.rust-lang.org/book/"? What's the difference between them?

https://github.com/rust-lang/rustlings/blob/39635598105264b8d60d5ad0c73d554a58dbf557/info.toml#L515-L524

For example, in the `info.toml`, the line 521 uses the "stable" version but line 523 uses the "normal" version. Should we standardize things like this?

**Comment by diannasoreil** [comment]
I believe both links redirect to the exact same thing, but it would be nice to have consistent.

**Comment by mo8it** [comment]
The [learn page](https://www.rust-lang.org/learn) on the official Rust website links to https://doc.rust-lang.org/book/ which is also shorter. So we should use that :)

**Comment by mo8it** [comment]
Done in https://github.com/rust-lang/rustlings/commit/69021e1497f62d52fd2b41d5e5b71ca46b76d7c0
