### ISSUE TITLE
Add potential projects after finishing rustlings

### ISSUE THREAD

**Issue by Vilhelm-Ian** [rust-lang/rustlings#1126]
It says in the READ.md to create your own projects after finishing rustlings. But it would help the learner to get an idea what kind of projects to build if there are examples listed

**Comment by diannasoreil** [comment]
Every learner's method of learning differs - Rustlings tries to provide as minimal of a common thread as possible by really only getting you used to Rust's syntax and some of its mechanisms, but what you do after that is completely up to you. I know some people like to hack on an existing project to get used to a new language, some like to build a small project from scratch, yet others like to stick to theoretical materials for a while longer.

There's no simple answer for this questions that can simply "fit most sizes", and therefore there's no "canonical" suggestions that I want to make.
