### ISSUE TITLE
Unable to find a solution to fn num_sq<T>(arg: &mut T)

### ISSUE THREAD

**Issue by CaliViking** [rust-lang/rustlings#1127]
### For reference, see:
Related exercise:
https://github.com/rust-lang/rustlings/blob/300cdc27dd0eb06939e187f86dd5833d146339a3/exercises/conversions/as_ref_mut.rs#L22

Related unit test:
https://github.com/rust-lang/rustlings/blob/300cdc27dd0eb06939e187f86dd5833d146339a3/exercises/conversions/as_ref_mut.rs#L55

Related pull request (solves only part of the problem): https://github.com/rust-lang/rustlings/pull/1113

### Background information:
```
rustc --version
rustc 1.62.1 (e092d0b6b 2022-07-16)
```
```
rustlings --version 
v5.0.0
```
```
ls -la
total 7868
drwxr-xr-x  9 niels niels    4096 Aug  6 16:17 .
drwxrwxrwx 31 niels niels    4096 Aug  6 17:14 ..
-rw-r--r--  1 niels niels   36818 Aug  1 13:15 .all-contributorsrc
-rw-r--r--  1 niels niels     102 Aug  1 13:15 .editorconfig
drwxr-xr-x  8 niels niels    4096 Aug  5 19:38 .git
drwxr-xr-x  3 niels niels    4096 Aug  1 13:15 .github
-rw-r--r--  1 niels niels     139 Aug  1 13:15 .gitignore
-rw-r--r--  1 niels niels     150 Aug  1 13:15 .gitpod.yml
-rw-r--r--  1 niels niels     104 Aug  1 13:15 .replit
drwxr-xr-x  2 niels niels    4096 Aug  2 17:03 .vscode
-rw-r--r--  1 niels niels   44269 Aug  1 13:15 AUTHORS.md
-rw-r--r--  1 niels niels   41137 Aug  1 13:15 CHANGELOG.md
-rw-r--r--  1 niels niels    4171 Aug  1 13:15 CONTRIBUTING.md
-rw-r--r--  1 niels niels   16506 Aug  5 19:49 Cargo.lock
-rw-r--r--  1 niels niels     497 Aug  1 13:15 Cargo.toml
-rw-r--r--  1 niels niels    1095 Aug  1 13:15 LICENSE
-rw-r--r--  1 niels niels    5799 Aug  1 13:15 README.md
drwxr-xr-x 26 niels niels    4096 Aug  2 13:52 exercises
-rw-r--r--  1 niels niels   40537 Aug  1 13:15 info.toml
-rw-r--r--  1 niels niels    3022 Aug  1 13:15 install.ps1
-rwxr-xr-x  1 niels niels    4591 Aug  1 13:15 install.sh
-rw-r--r--  1 niels niels    8696 Aug  1 13:17 rust-project.json
drwxr-xr-x  2 niels niels    4096 Aug  1 13:15 src
drwxr-xr-x  4 niels niels    4096 Aug  5 19:49 target
-rwxr-xr-x  1 niels niels 3879296 Aug  2 22:55 temp_3632_ThreadId1
-rwxr-xr-x  1 niels niels 3879248 Aug  2 22:56 temp_9867_ThreadId1
drwxr-xr-x  3 niels niels    4096 Aug  1 13:15 tests
niels@DESKTOP-GU276AE:~/git/rustlings$
```
#### It is not clear what the exercise is trying to teach
Please provide some context to the use case of passing u32 in a Box.
#### I can find no way to solve it
Are there examples of good solutions to the exercises available?

**Comment by 0x4B63** [comment]
I also felt that it wasn't immediately apparently what needed to be done. I believe the hint would be more useful if it also mentioned the AsMut portion of the exercise. Ultimately what allowed me to solve it was reading the [AsMut Documentation](https://doc.rust-lang.org/std/convert/trait.AsMut.html).

**Comment by maxcurzi** [comment]
I'm stuck here, too.

I'm hoping that something like this is the intended solution (judging from the examples above)

```
fn num_sq<T: AsMut<u32>>(arg: &mut T) {
    arg.as_mut().checked_pow(2); // if only this could modify 'arg' in place..!!
}
```
But of course it fails to pass because all the operations on u32 don't modify the value in-place... 
...Any hints welcome!

**Comment by maxcurzi** [comment]
see https://github.com/rust-lang/rustlings/issues/1156

**Comment by CaliViking** [comment]
@maxcurzi - thanks for the follow up. Not sure I am any wiser, but I will close the issue for now.
