### ISSUE TITLE
Rustfmt removes blank lines before hints

### ISSUE THREAD

**Issue by rouhannb** [rust-lang/rustlings#113]
I have my editor set to format code on saving, but when I do so the space before the hints is removed. This is an easy fix; just add blank comments after each line before the hint.

**Comment by komaeda** [comment]
are you sure it's rustfmt doing that? when running `cargo fmt` over a clean checkout of the repo, it doesn't change anything

**Comment by LesnyRumcajs** [comment]
`rustfmt` doesn't change anything for me as well, tested on Fedora 29.

**Comment by komaeda** [comment]
closing as I can't figure out how to reproduce this

**Comment by skondrashov** [comment]
@fmoko @LesnyRumcajs To reproduce:

```rust
    }

    #[test]
```

In a gap like this, if the empty line has whitespace on it, then the entire line is removed. If it only has an endline, then nothing happens.

**Comment by fmoko** [comment]
@skondrashov Sure, but at that point it's more of a problem in rustfmt. We don't put hints into files themselves anymore anyways.

**Comment by skondrashov** [comment]
Honestly thought this was an issue in rustfmt when I commented that... whoops!
