### ISSUE TITLE
where is the document of into() rustling string4.rs

### ISSUE THREAD

**Issue by dlintw** [rust-lang/rustlings#1135]
I've checked similar function, but don't understand why into() workable.

* [[into_string](https://doc.rust-lang.org/std/primitive.str.html#method.into_string)](https://doc.rust-lang.org/std/primitive.str.html#method.into_string)

**Comment by diannasoreil** [comment]
It's here: https://doc.rust-lang.org/std/convert/trait.Into.html. Into is a trait, not a specific function.

**Comment by dlintw** [comment]
Thanks, but seems The books not mention the into() trait. maybe could add document in the rustling string4.rs
