### ISSUE TITLE
Mac OS compilation issue and resolution

### ISSUE THREAD

**Issue by jkboyce** [rust-lang/rustlings#114]
It's probably worth noting somewhere in the "getting started" page that on a stock Mac OS system, the command `cargo install --path .` fails partway through with an error that `stdlib.h` cannot be found. This requires two or three steps to fix:

1. Install Xcode from the Mac App Store, which includes the C compiler tools
2. Install the Xcode command line tools by typing `xcode-select --install` at a Terminal prompt, and approving the license agreement.

In Xcode 10 there is an additional step since by default Apple no longer installs header files in their usual location at `/usr/include`. To do that you need to install the pkg file located at `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

**Comment by komaeda** [comment]
thank you for reporting this! i'll make an adjustment right away

**Comment by komaeda** [comment]
fixed in 17fa037!
