### ISSUE TITLE
String3.rs asks to trim from the end but then checks both the front and the end.

### ISSUE THREAD

**Issue by SunnyWar** [rust-lang/rustlings#1153]
On line 6 of the exercise is asked to remove white space from the _end_ of the string, but the test checks that both the front and the end have white space removed.
Recommend that it say: "TODO: Remove whitespace from both the front and the end of a string!

fn trim_me(input: &str) -> String {
    // TODO: Remove whitespace from the end of a string!
}

#[test]
    fn trim_a_string() {
        assert_eq!(trim_me("Hello!     "), "Hello!");
        assert_eq!(trim_me("  What's up!"), "What's up!");
        assert_eq!(trim_me("   Hola!  "), "Hola!");
}

**Comment by magnusrodseth** [comment]
In my up-to-date `main` branch, this is how `strings3.rs` looks:

```rust
fn trim_me(input: &str) -> String {
    // TODO: Remove whitespace from both ends of a string!
    ???
}
```

I don't think there is a problem here ☺️

**Comment by SunnyWar** [comment]
> In my up-to-date `main` branch, this is how `strings3.rs` looks:
> 
> ```rust
> fn trim_me(input: &str) -> String {
>     // TODO: Remove whitespace from both ends of a string!
>     ???
> }
> ```
> 
> I don't think there is a problem here ☺️

ok dokey!
