### ISSUE TITLE
Options1.rs confusions

### ISSUE THREAD

**Issue by washbin** [rust-lang/rustlings#1158]
![image](https://user-images.githubusercontent.com/76929116/185726757-5c3a7d7a-6f5d-4778-8e65-ff54dd2c9b15.png)

As seen here,
The question signifies that the ice-creams are eaten at 10pm, even gives a hint for 22 at 24 hours clock leaving 0 after that.

However,
The tests signify that the ice-creams are eaten at 10am

![image](https://user-images.githubusercontent.com/76929116/185726819-365f884e-a3d8-4629-9c82-a66f8e07b1c6.png)

**Comment by PerryCameron** [comment]
I agree,
assert_eq!(maybe_icecream(10), Some(0));
should be 
assert_eq!(maybe_icecream(10), Some(5));

**Comment by PerryCameron** [comment]
Looks like they updated it already

https://github.com/PerryCameron/rustlings/commit/4455c22b9aa5e4a6735e3ae67a4c9e75af24128a

**Comment by washbin** [comment]
Oh yes, it seems to have been updated already, My bad, Last time I looked it wasn't updated, Guess I forgot to look properly while opening.
Since, its already updated I guess closing this issue won't do any harm.
