### ISSUE TITLE
if1.rs requires main(), but comments suggest no additional function calls

### ISSUE THREAD

**Issue by technopagan** [rust-lang/rustlings#116]
The exercise if1.rs caused some frustration:

The one-liner that actually deals with the if-else is simple, but rustc complains about the exercise missing a main() function while the source code comments for the exercise explicitly state not to use an additional function call. Rock, say hello to hard place. ;)

I thought I'd try to be clever (that never ends well...) and rename fn bigger to main, but in Rust, main() cannot (easily) return an int. I spent quite some time working around this while knowing this couldn't possibly be the desired solution.

I ended up ignoring the comment about not using an additional function call and "solved" the execise by adding:
`fn main() {bigger(1,2);}`

Please consider taking into account that Rust requires main() to be present.

**Comment by komaeda** [comment]
`if1.rs` is supposed to be ran as a test. this automatically happens when using `rustlings verify` (i hope), but when running manually you need to add a --test flag (`rustlings run --test exercises/if/if1.rs`). when running in test mode, the rust compiler does not require a `main()` function to be present

**Comment by komaeda** [comment]
to be fair, i am thinking of a way of automating this so it's more transparent to the user, so i'll add it as a roadmap item!

**Comment by komaeda** [comment]
@technopagan could you try with the latest `master` branch and see if the problem persists?

**Comment by vitkarpov** [comment]
@komaeda it's a 🔥now (without `--test`)
<img width="505" alt="Screen Shot 2019-03-10 at 10 28 10 AM" src="https://user-images.githubusercontent.com/3001791/54081972-3ee8c480-431f-11e9-987c-892cafd5cd58.png">

**Comment by komaeda** [comment]
yep, can confirm this myself (untouched checkout)

<img width="948" alt="image" src="https://user-images.githubusercontent.com/45509655/54122098-6f526080-43fc-11e9-8c41-29dcbdad9a4f.png">
