### ISSUE TITLE
hashmaps3.rs name in the Team struct

### ISSUE THREAD

**Issue by radiden** [rust-lang/rustlings#1160]
Is having `name` in the team struct actually necessary? The team name is already used as the key, so I realistically don't see a reason to also have it in the value. The `name` in the team struct can also be completely bypassed, as it is not being tested for, so you can put anything you'd like in there and still complete the exercise.

**Comment by PerryCameron** [comment]
Yea, It is an unused double entry in the same data structure. I wondered about that too.

**Comment by NaokiM03** [comment]
I too was concerned about the compiler pointing out "warning: field \`name\` is never read".
I don't know of a model answer to this question, but it seems to me that the duplication of names forces a `clone()` that is not really needed.

**Comment by Ben2917** [comment]
I believe this merged PR closes this issue https://github.com/rust-lang/rustlings/pull/1547
