### ISSUE TITLE
quiz1 test case does not match problem description

### ISSUE THREAD

**Issue by thepolytheist** [rust-lang/rustlings#1169]
The problem description for quiz1 is as follows:
```rust
// Mary is buying apples. One apple usually costs 2 Rustbucks, but if you buy
// 40 or more at once, each apple only costs 1! Write a function that calculates
// the price of an order of apples given the quantity bought. No hints this time!
```
This means that if you buy anything less than 40 apples, the cost is 2 Rustbucks per apple and the cost == 2 * the number of apples. Starting at 40 apples, the cost is reduced to 1, so for 40 or more apples, the cost == the number of apples.

However, the second test case is
```
let price2 = calculate_price_of_apples(40);
...
assert_eq!(80, price2);
```
This implies that the cost at 40 apples is still 2 Rustbucks per apple.

Recent commit https://github.com/rust-lang/rustlings/commit/d6e26bb350e423a8f2a90d9405060fdaf9893736 is incorrect and should be reverted.

**Comment by vijoin** [comment]
The current test case doesn't match the problem description. I think you still need to change the test case to

```...
let price2 = calculate_price_of_apples(40);
...
assert_eq!(40, price2)
```

`40 or more at once` implies a price of `1` for 40 apples and will have to be solved this way:

```
if amount >= 40 {
        price = 1
    }
```

**Comment by diannasoreil** [comment]
Fixed on main

**Comment by asdkant** [comment]
I just encountered this issue the other way around in v6.3.0: https://github.com/rust-lang/rustlings/blob/v6.3.0/exercises/quizzes/quiz1.rs

The comment says that the price reduction starts at 41 apples:
```rust
// Mary is buying apples. The price of an apple is calculated as follows:
// - An apple costs 2 rustbucks.
// - However, if Mary buys more than 40 apples, the price of each apple in the
// entire order is reduced to only 1 rustbuck!
```

but as per the test, it starts at 40 apples:
```rust
        assert_eq!(calculate_price_of_apples(40), 80);
```

**Comment by mo8it** [comment]
@asdkant `80` is `2 * 40`. So the reduction doesn't start at 40 yet.

At 41, the price will be `1* 41`.
