### ISSUE TITLE
vec2.rs - compare addresses of input and output

### ISSUE THREAD

**Issue by Vest** [rust-lang/rustlings#1172]
Hello everyone,

I see that in the exercise the input vector and output vector [must be the same](https://github.com/rust-lang/rustlings/blob/3309a01b5e7f18da6409435151e8ebe0c0a697dc/exercises/vecs/vecs2.rs#L19) (v). I am curious, if the unit test should reflect this: "the addresses of input and output vectors must be equal".

I am asking this, because my colleague, when he was solving the case, has created a new vector and returned it with an explicit "return" statement.

If needed, I can try to create the PR with the additional unit test.

Thanks,
Vest

**Comment by mo8it** [comment]
Good idea, but `vecs2` has been changed so that `vec_loop` returns a `Vec` created in the function instead of mutating the input. This leads to a better comparison with the `vec_map` method.
