### ISSUE TITLE
quiz1.rs test case 2 typo

### ISSUE THREAD

**Issue by 08351ty** [rust-lang/rustlings#1177]
the second `assert_eq` should be `assert_eq!(40, price2);` not `assert_eq!(80, price2);` since prompt is `but if you buy
// 40 or more at once, each apple only costs 1!` so unit cost should be 1 per apple if apples >=40.

**Comment by Evgeny-SPB** [comment]
This issue is solved with pull request https://github.com/rust-lang/rustlings/pull/1170

**Comment by diannasoreil** [comment]
Fixed on main
