### ISSUE TITLE
Logic issue with Quiz 1

### ISSUE THREAD

**Issue by huzeifa** [rust-lang/rustlings#1193]
Quiz 1 states:  Mary is buying apples. One apple usually costs 2 Rustbucks, but if you buy **40 or more** at once, each apple only costs 1! Write a function that calculates the price of an order of apples given the quantity bought. No hints this time!

The question clearly states that orders above 40 or more should cost 1. However, the test for 40 orders evaluates to 80 instead of 40.

Need some clarification, or probably I am missing something.

**Comment by yotarotsukada** [comment]
The question is fixed now. #1164

**Comment by huzeifa** [comment]
Thanks!
