### ISSUE TITLE
Clone-on-Write exercise is unclear

### ISSUE THREAD

**Issue by black-puppydog** [rust-lang/rustlings#1195]
I am just going through `exercises/standard_library_types/cow1.rs` and while I think I understand the type (and have read up on it in the reference) I don't really see what I'm supposed to _do_ in this exercise.

Specifically, I find these lines confusing:

https://github.com/rust-lang/rustlings/blob/c923e7af73a91970d2e63e03babbca9cc0817551/exercises/standard_library_types/cow1.rs#L41-L47

As a learner I'm not sure what I'm expected to do here. I can just replace `Borrowed` by `Owned` and make the code compile & run. However, that seems too obvious as a solution, given that it's literally the same as a few lines above. And then the `panic!` also needs to be changed I guess, that assertion seems a bit confusing.

Maybe simply writing `// TODO: modify the following two lines to match the situation` or some such would take the uncertainty out of the situation. Or, if that seems _too_ easy then, maybe just leave the match incomplete and let the learner fill it completely?

I'm obviously nit-picking a bit here; including `cow` into the course is a great thing! 👍🏽

**Comment by Jzow** [comment]
This code only tells you that the `input` has the ownership of the `slice` value, so it will not clone

**Comment by black-puppydog** [comment]
yes I understood that, the reference of `cow` is quite clear about it. Maybe this is really just my particular brain that found this exercise a bit confusing. I think the reason might be that there are two lines, one of which affirming "expected borrowed value". I think I wouldn't have been confused if for example the match only contained the following:

```rust
match abs_all(&mut input) { 
    ... => println!("I own this slice!"), 
    _ => panic!("expected ... value"), 
} 
```

That makes the exercise even a little more obvious.
FWIW, I won't push hard on this, it's not a huge issue. But it was pretty much the first hiccup I had in the flow state of going through the rustlings so I found it noteworthy. 🙂

**Comment by qqrm** [comment]
I agree, the description of panic is misleading.

**Comment by dolzenko** [comment]
Confused here too, so the solution of the exercise is to `Cow::Borrowed => Cow::Owned` in the last match?

**Comment by JonShort** [comment]
I also got confused here, for me it's because the rest of the course is TDD but here the assertion is unclear/incorrect

```rust
_ => panic!("expected borrowed value"),
```

Agree with https://github.com/rust-lang/rustlings/issues/1195#issuecomment-1246539662 that altering this text would improve the exercise

**Comment by black-puppydog** [comment]
Wow, didn't realize github would throw a mention into this thread for every force-push on my own fork. Sorry for the noise everyone. 😛 
In any case, I made #1244 to address this. What do you all think (especially those who also got stumped by the current form)

**Comment by ajs1998** [comment]
I agree. This exercise is very confusing, the comments are not descriptive, and it is not clear what the `// TODO` is telling me I should to change. As a new learner, I still don't understand how this hint is supposed to help me:

> Since the vector is already owned, the `Cow` type doesn't need to clone it.

Rustlings seems like a neat educational tool, but some of these exercises have little educational value. Why are there so few useful, descriptive comments? Half the time I have to go read the chapter in the book anyway, so why not put a relevant paragraph or two in the comments so I don't have to leave my IDE?

**Comment by black-puppydog** [comment]
@ajs1998 I wouldn't actually recommend rustlings as your _sole_ learning tool. It may work for some (many, even) but for me it really started to shine after I read the book cover to cover. TRPL is _extremely_ well written IMO, and rustlings then drove home all the important points to consolidate the acquired knowledge. But of course, YMMV.

As to the comments and such: take not whenever you get stumped by an exercise and feel free to make issues for that. It takes a bit of introspection to really figure out what confuses you about an exercise, see above where it took me a bit of discussions with others to even verbalize it.
