### ISSUE TITLE
Add "Expected output:" comment 

### ISSUE THREAD

**Issue by Kazumasan** [rust-lang/rustlings#1197]
First thing first Amazing project has been fun so far.

Now I'm currently in the move_semantics2 and I'm unclear what the output should be.
I Solved it, to the point where it is compiling, as well as read the hints and tried all 3 solutions.

But I'm expecting the output to be `Vec0: [22,44,66]` and for `Vec1: [22,44,66,88]` but im always getting:
`Vec0 []  Vec1[22,44,66,88]` is this what it should be ? 

It seems like having "is able to compile" as the only win condition is a bit confusing (this obviously doesn't apply to the parts with Tests but I don't think its necessary to apply test rules to every part a simple `Expected Output: ....` section would suffice." IMO.

any thoughts ?

**Comment by JoonasPitk** [comment]
The goal of this exercise is ambiguous, I agree.
I ended up looking up what others have do to get the code to compile, and all I find are ones where the vec0 is empty...
Meanwhile the hint implies that you should fix dropped variables, which people don't appear to be doing?

**Comment by morberg** [comment]
I am also confused about this exercise and the hints. The first hint says to "Make another, separate version of the data that's in `vec0` and pass that to `fill_vec` instead.". But `vec0` is empty so there is no data to copy?

The last hint is "Make `fill_vec` *mutably* borrow a reference to its argument (which will need to be
   mutable), modify it directly, then not return anything. Then you can get rid
   of `vec1` entirely -- note that this will change what gets printed by the
   first `println!`". But then the code in `main`doesn't make sense.

**Comment by houghta4** [comment]
This really stumped me because of those expected comment lines. I have no idea if the 3 ways I did it match the 3 hints given. It almost seems like that expected output should be for move_semantics3.rs
