### ISSUE TITLE
Install fails due to API rate limit exceeded

### ISSUE THREAD

**Issue by thefreefox** [rust-lang/rustlings#1208]
https://github.com/rust-lang/rustlings/blob/2398f378b06fbb547cf3a3b292554a756d806c5e/install.sh#L144

Not sure why, but line 144, request for https://api.github.com/repos/rust-lang/rustlings/releases/latest" gives an error message.

{"message":"API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

This prevents the installation from succeeding. Maybe it would be possible to catch the problem, inform user, and carry on?

**Comment by shadows-withal** [comment]
This is a pretty niche problem and should really only happen on large shared (maybe public) networks. Don't really think it's worth catching, it's the first time I've seen this pop up.
