### ISSUE TITLE
Watch recompiles all the files each time

### ISSUE THREAD

**Issue by vitkarpov** [rust-lang/rustlings#121]
Hey 👋 there!

Thanks for this awesome project, it's really helpful for beginners (like me). I'd like to suggest an improvement (and probably would be happy to implement).

When I run `rustlings watch` my learning flow is simple: walk through all files one by one and fix errors. Does it make sense **to verify only changed files** (most like only the last one), not the whole set?

Thanks! 👍

**Comment by komaeda** [comment]
@vitkarpov a pull request for what you're requesting (i think) currently exists at #120!

**Comment by vitkarpov** [comment]
@komaeda yep, that's exactly it. Thanks! 🙇
