### ISSUE TITLE
Improving rustlings watch latency

### ISSUE THREAD

**Issue by eliasjonsson023** [rust-lang/rustlings#1215]
About 2 seconds pass after file has been saved to the point that rustlings reacts to the newly changed file and starts compiling it. Is there a way of making this delay shorter?

**Comment by diannasoreil** [comment]
Yes, by decreasing the timeout between polling here: https://github.com/rust-lang/rustlings/blob/main/src/main.rs#L365. I'd be up for decreasing this to half a second.

**Comment by magnusrodseth** [comment]
@diannasoreil I checked this by manipulating values both in the [`watcher`](https://github.com/rust-lang/rustlings/blob/97e3c419aaae6d368bdab69035c44ddf6da43633/src/main.rs?rgh-link-date=2022-10-10T09%3A43%3A27Z#L353) and in the [`rx`](https://github.com/rust-lang/rustlings/blob/97e3c419aaae6d368bdab69035c44ddf6da43633/src/main.rs?rgh-link-date=2022-10-10T09%3A43%3A27Z#L365), and it still seems to be around 2 seconds after decreasing these values. Any other ideas?

**Comment by eliasjonsson023** [comment]
Same issue here.

**Comment by AxolotlTears** [comment]
@magnusrodseth @eliasjonsson023 That's odd, manipulating the value for `watcher` seems to work for me. Did you reinstall rustlings afterwards?

**Comment by AxolotlTears** [comment]
@diannasoreil Would you mind https://github.com/rust-lang/rustlings/blob/97e3c419aaae6d368bdab69035c44ddf6da43633/src/main.rs?rgh-link-date=2022-10-10T09%3A43%3A27Z#L353 being cut to half?  From 2 -> 1?

**Comment by diannasoreil** [comment]
@AxolotlTears sounds good to me, yeah
