### ISSUE TITLE
variable1: cannot guess keyword

### ISSUE THREAD

**Issue by loewis** [rust-lang/rustlings#1223]
I started rustlings with zero rust knowledge. I first failed at variable 1. The error I get is "cannot find variable". This is clear enough, I need to declare it. So I try

`    int x = 5;
`
which fails with a syntax error. Then I try "hint" in the rustlings watch window. It tells me "The declaration on line 8 is missing a keyword that is needed in Rust to create a new variable binding." I was guessing that much, but: what keyword?

I try `declare` which fails. Seeing that the function is declared with `fn`, I guess that it might be `dcl`, but no cigar. Googling then tells me that the keyword is actually `let`.

I was under the impression that rustlings leads me through the tutorial without having to search syntax on the internet. If that assumption is wrong, it would be useful to point that out in the very opening text of rustlings. Otherwise, I suggest that the hint actually reveals that the keyword is `let`.

**Comment by SpaceCadet404** [comment]
I'm not certain if your impression that Rustlings will lead you through without having to lookup syntax is correct, but you at least won't have to turn to google. In the Variables section is a README.md file that points to https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html

**Comment by diannasoreil** [comment]
Rustlings is designed to be used alongside the official book, which can either be studied, or used for reference. Have a look here: https://github.com/rust-lang/rustlings/blob/main/exercises/README.md, and in the respective exercise directories' `README.md` files.
