### ISSUE TITLE
rustlings watch fails after manual install

### ISSUE THREAD

**Issue by murku** [rust-lang/rustlings#1225]
Hi Everybody,

I tried with vscode&devcontainer and I have issues when running `rustlings watch`:
```
Error: Could not watch your progress. Error message was Io(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }).
Most likely you've run out of disk space or your 'inotify limit' has been reached.
```
I have plenty of free space and inotify limit is far away...

I use the manual install see: https://github.com/rust-lang/rustlings/commit/e89f904c7554f0f3e3c447e104460276ba0a1d49

Do anybody has an idea what could be the issue? Thanks

* `rustc 1.64.0 (a55dd71d5 2022-09-19)`
* rustlings v5.2.1 (I cloned commit [cade600](https://github.com/rust-lang/rustlings/commit/cade600c912d4d39d9e6ba602a9e21467cb324bd))
* macOS 12.6, Docker version 20.10.17, build 100c701, mcr.microsoft.com/vscode/devcontainers/rust:0-buster

`ls -la`:
```
total 264
drwxr-xr-x 24 vscode vscode   768 Oct  9 13:52 .
drwxr-xr-x  3 root   root    4096 Oct  9 13:26 ..
-rw-r--r--  1 vscode vscode 42997 Oct  9 13:52 .all-contributorsrc
-rw-r--r--  1 vscode vscode 53328 Oct  9 13:52 AUTHORS.md
-rw-r--r--  1 vscode vscode 16506 Oct  9 12:27 Cargo.lock
-rw-r--r--  1 vscode vscode   497 Oct  9 12:27 Cargo.toml
-rw-r--r--  1 vscode vscode 42872 Oct  9 12:27 CHANGELOG.md
-rw-r--r--  1 vscode vscode  4171 Oct  9 12:27 CONTRIBUTING.md
drwxr-xr-x  5 vscode vscode   160 Oct  9 12:46 .devcontainer
-rw-r--r--  1 vscode vscode   102 Oct  9 12:27 .editorconfig
drwxr-xr-x 29 vscode vscode   928 Oct  9 12:27 exercises
drwxr-xr-x 15 vscode vscode   480 Oct  9 13:52 .git
drwxr-xr-x  3 vscode vscode    96 Oct  9 12:27 .github
-rw-r--r--  1 vscode vscode   139 Oct  9 12:27 .gitignore
-rw-r--r--  1 vscode vscode   150 Oct  9 12:27 .gitpod.yml
-rw-r--r--  1 vscode vscode 41702 Oct  9 13:52 info.toml
-rw-r--r--  1 vscode vscode  3022 Oct  9 12:27 install.ps1
-rwxr-xr-x  1 vscode vscode  4591 Oct  9 12:27 install.sh
-rw-r--r--  1 vscode vscode  1095 Oct  9 12:27 LICENSE
-rw-r--r--  1 vscode vscode  6095 Oct  9 12:27 README.md
-rw-r--r--  1 vscode vscode   104 Oct  9 12:27 .replit
drwxr-xr-x  8 vscode vscode   256 Oct  9 12:27 src
drwxr-xr-x  5 vscode vscode   160 Oct  9 13:18 target
drwxr-xr-x  4 vscode vscode   128 Oct  9 12:27 tests
```

**Comment by diannasoreil** [comment]
Weird! I have no knowledge of devcontainers, so I'll leave this issue open in case someone who does (or who's ran into the same issue?) knows something.

**Comment by murku** [comment]
Fine by me! I will try to reproduce on my win machine. Anyway, thanks for looking on it:)

**Comment by murku** [comment]
I used rust devcontainer of vscode: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/rust
Take care os using the variant suggested for your machines arch. I used a wrong one...
See related commet:
```
// Use the VARIANT arg to pick a Debian OS version: buster, bullseye
// Use bullseye when on local on arm64/Apple Silicon.
```
here: https://github.com/microsoft/vscode-dev-containers/blob/v0.245.2/containers/rust/.devcontainer/devcontainer.json
