### ISSUE TITLE
Why not use tests for some exercises

### ISSUE THREAD

**Issue by Hades32** [rust-lang/rustlings#127]
There are several exercises of the style

```
if you_did_it_right {
  print("great");
} else {
  print("try again");
}
```

Why aren't these exercises done as tests?

**Comment by MForever78** [comment]
Echo on this. some exercises can now pass by just not having compiling errors.

**Comment by mo8it** [comment]
Closing but feel free to open new issues pointing to specific exercises. You are also welcome to submit pull requests :D
