### ISSUE TITLE
Teach that String implements Add<&str>?

### ISSUE THREAD

**Issue by Prism019** [rust-lang/rustlings#1277]
I've been programming in Rust for about three years now, but never really got into using `String`s and `&str`s outside of the absolute bare minimum required for my projects. I decided to do Rustlings again for the heck of it, but once I got to `standard_library_types/iterators2.rs`, I got very frustrated with step 1, as I had no idea how to add a `String` to a `&str` (I was trying `.extend` but that mutates in-place and returns `()`). The hint didn't help much either, as it just says `... needs to be added to ...` (added **how?**).
It wasn't until I looked at the file history for the exercise that I discovered that `String` implements `Add<&str>`. This would probably be a good idea to add somewhere in the `strings` exercises (possibly `strings4.rs`?) as this seems to me like something that's good to know about.

**Comment by mo8it** [comment]
Fixed in https://github.com/rust-lang/rustlings/commit/08c408aae042509526e8cc1f175e7a010836f53d :)
