### ISSUE TITLE
Show the exercises name in the end of output after failed

### ISSUE THREAD

**Issue by dlintw** [rust-lang/rustlings#1281]
I often require copy & paste the failed exercise name, but when it compiled failed, the name will be overwritten if my terminal only show 25 lines.

**Comment by mo8it** [comment]
Will be fixed by https://github.com/rust-lang/rustlings/issues/1920

**Comment by mo8it** [comment]
@dlintw In the next release, not only will the exercise name be shown at the end of the output, but it will also be clickable so that you can open the exercise file in the browser :D

Here is a demo: https://fosstodon.org/@mo8it/112266859767062951
