### ISSUE TITLE
nix: following install instructions clones a version without required nix files

### ISSUE THREAD

**Issue by MathanGeurtsen** [rust-lang/rustlings#1282]
Hey, From reading the readme I ran the command `git clone -b 5.2.1 --depth 1 https://github.com/rust-lang/rustlings`, but that version doesn't have the `flake.nix` file which is required to run `nix develop` afterwards. Perhaps this should be amended to another fixed commit? At the moment I seem to get a working nix environment on  on commit `e3af483f`.

**Comment by diannasoreil** [comment]
Will be fixed by publishing the next release!
