### ISSUE TITLE
Run Rustlings within Codespaces

### ISSUE THREAD

**Issue by eroullit** [rust-lang/rustlings#1284]
Hi Rustlings Team ! 👋 

Since [Codespaces are readily available to all GitHub users](https://github.com/features/codespaces), it would be great to make use of them to allow Rust-curious developers to quickly spin-up an environment and get started.

A feature branch is available on [this fork](https://github.com/eroullit/rustlings/tree/codespaces) and you are [free to give it go](https://docs.github.com/en/codespaces/developing-in-codespaces/creating-a-codespace-for-a-repository#creating-a-codespace-for-a-repository).

I am open to feedback and changes to prepare a Pull Request. 🚀

**Comment by diannasoreil** [comment]
Looks good and works for me! If you want to, you can open a PR from your fork.

(for my reference: this would close #1194 and #442)

**Comment by eroullit** [comment]
Sorry for the late answer. I just saw this post just now.
I will prepare a PR shortly.
