### ISSUE TITLE
compilation of 'rustlings watch' hangs in functions3.rs (edge case)

### ISSUE THREAD

**Issue by luckynumberke7in** [rust-lang/rustlings#1285]
Hey guys,

Was learning about unsigned 32bit ints and wanted to test just how long this function example would take to render the maximum value of u32 (4_294_967_295).

This appeared to freeze the compiler on: "⠈ Running exercises/functions/functions3.rs..."

I canceled and did some tested of other values to see if it was just taking so long because it was getting ready to print 4 billion strings. I tested 333, 33_333, 333_333, 3_333_333, and all compilations were basically instant, except 3_333_333 took about 5 to 10 seconds.

So by those calculations if the issue was linear it should process in about 200ish minutes. I decided to re-run the maximum value again while sleeping to see if it would compile...

Woke up this morning almost 5 hours later and it was still frozen.

Code was as follows:
```rust
fn main() {
    call_me(4_294_967_295);
}

fn call_me(num: u32) {
    for i in 0..num {
        println!("Ring! Call number {}", i + 1);
    }
}
```

**Comment by luckynumberke7in** [comment]
PS, I am absolutely LOVING Rustlings! The feel of the course is very authentic to an insidious debugging session, breaking down the compiler messages and getting used to the whole rust experience.

I also want to note that I am able to move along in the program as normal when changing the value to something lower (like say 33).

**Comment by luckynumberke7in** [comment]
I also tested it with and without the number literals (just to see if that would make a difference, but it did not.

**Comment by luckynumberke7in** [comment]
I'm re-running it and just going to see if / how long it will hang for now. It has been 6 hours this time so far.

**Comment by luckynumberke7in** [comment]
Somewhere after the 8 hour mark the terminal showed "Killed" not exactly sure on the timeframe as I had it going while I was out for the evening.
```bash
Progress: [######>-----------------------------------------------------] 10/94
⠠ Running exercises/functions/functions3.rs...
Killed
ke7in@ke7in-pc:~/Desktop/Coding/Rustlings$ 
```

**Comment by diannasoreil** [comment]
Closing as this _is_ an edge case, and likely the only time someone will report something like this, but thanks for testing it out 😄 x
