### ISSUE TITLE
Provide a mode to not re-compile/re-test everything at every iteration

### ISSUE THREAD

**Issue by ColinPitrat** [rust-lang/rustlings#132]
I find it a bit annoying that `rustlings verify` and `rustlings watch` both recompile everything at every attempt.

One option I'm thinking of is to make `rustlings watch` only validate the test corresponding to the changed file. Then, if it succeeds, it could redo a `verify` to get to the next one.

What do you think ?

**Comment by komaeda** [comment]
this has been fixed in #120 and is released in version 1.1.0!
