### ISSUE TITLE
Suggestion: `error_handling/errors3.rs` Add line to prevent modifying `?` line

### ISSUE THREAD

**Issue by kai-tub** [rust-lang/rustlings#1329]
Hey all.

First of all, thank you very much for creating such an amazing learning resource!
I have never touched Rust before and am using this guide to get my feet wet after having tried and failed to go through the _book_ a couple of times.
I have been enjoying it a lot and would like to contribute back, even if it is only a minor point.
In exercise `error_handling/errors3.rs`, I wasn't aware that it was possible to change the return type of `main`, which seems to have been the main point of the exercise but instead changed the error handling to `panic` via `unwrap` instead of propagating the error with `?`. And I also didn't saw it highlighted in the book chapter from the exercise before: https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator.

https://github.com/rust-lang/rustlings/blob/c5898ac6b7d4e4048c40ac90b4c2669fc380660d/exercises/error_handling/errors3.rs#L11-L23

Only after looking at the hint after completing the exercise, I learned that this was an option.
Sometimes I do forget to check the hint if I completed the exercise fairly quickly.
As it is an interesting 'feature' to have the `main` function return with a Result type, I would suggest to add the `// Try not to change the following line` before line 15.

More than happy to make a single line PR :)

**Comment by mo8it** [comment]
Thanks! Done in https://github.com/rust-lang/rustlings/commit/2d5d70693a879f07fcd941c21da3a3760cb81db6
