### ISSUE TITLE
Suggest swapping the order of the "standard_library_types" exercises and the "threads" exercises

### ISSUE THREAD

**Issue by exicx** [rust-lang/rustlings#1340]
Working through rustlings, I had issues figuring out the standard_library_types exercises, specifically the arc1.rs exercise. The threaded concepts make more sense after completing the threads1.rs exercise.

**Comment by mo8it** [comment]
We will move `arc1` after `threads3`. This is tracked in https://github.com/rust-lang/rustlings/issues/1701
