### ISSUE TITLE
Suggestion: hashmaps3.rs chaniging a test case

### ISSUE THREAD

**Issue by iamtburger** [rust-lang/rustlings#1344]
I'm going through the exercises and noticed that in `hashmaps3` there might be a case which is not covered.
At the moment the tests do not consider a scenario when a team plays two games at home. For example you can add:
`+ "England,Germany,2,0\n";` to the `get_results` function, then correct the `validate_team_score_1` so it will look like this:
```
fn validate_team_score_1() {
    let scores = build_scores_table(get_results());
    let team = scores.get("England").unwrap();
    assert_eq!(team.goals_scored, 7);
    assert_eq!(team.goals_conceded, 4);
}
```
And the test might fail if you did not consider this scenario in your solution, while it will pass without the above addition.

Let me know if this was intentional or not. If it needs correction, I'm more than happy to fix it.

**Comment by mo8it** [comment]
This has been fixed in the [latest version](https://github.com/rust-lang/rustlings/blob/main/exercises/11_hashmaps/hashmaps3.rs) :)
