### ISSUE TITLE
Update Vec's Readme

### ISSUE THREAD

**Issue by javihernant** [rust-lang/rustlings#1345]
Vec2.rs contains methods not explained in the resources specified in the README. They are:

- iter_mut(). The page linked in the readme doesn't use it. Instead, it uses the `for i in &mut v` construction.
- .map(). This one doesn't appear in the readme either. Maybe we should put a link to where it's explained in the rust's book.

**Comment by javihernant** [comment]
Also, in the the page linked talks about the borrow checker and ownership. Wouldn't it be better that `move_semantics` exercises comes before `vectors`?

**Comment by morberg** [comment]
I just got to this part and it tripped me up as well. `iter_mut` is not described anywhere else in The Rust Programming Language book either and only mentioned once.
