### ISSUE TITLE
Somewhat strange order of exercises: ARC, threads and RC

### ISSUE THREAD

**Issue by VorpalBlade** [rust-lang/rustlings#1348]
I'm doing the rustlings course and some things seem out of order:

* `standard_library_types/arc1.rs` happens before `standard_library_types/rc1.rs`
* `standard_library_types/arc1.rs` happens before `threads`

To me it is unintuitive to be thrown into ARC at that point.

**Comment by VorpalBlade** [comment]
Doing the rest of the course, Arc does need to be introduced before threads (though there is a bit of a circular dependency). But Rc should probably still go before Arc.

**Comment by shadows-withal** [comment]
Should be fixed in master.
