### ISSUE TITLE
Offering help with issue triage and PR review

### ISSUE THREAD

**Issue by matthri** [rust-lang/rustlings#1362]
Hi, first of all thank you for this great project, I really enjoyed learning Rust with it.
 
I noticed that there are some open unlabeled issues and pull requests and I would like to contribute to this project to give something back. 
I could offer to label the uncategorized issues and review some of the open pull requests.

So I wanted to ask if this is something that is wanted and if so if there is already a process in this project how this is handled. Especially who has the ability to add labels to issues and in what way.

**Comment by shadows-withal** [comment]
It's not as dire as it sounds :P Most of the open pull requests are a bit stale, they may as well be closed, but I get around to reviewing them on a somewhat regular basis. The issues kind of moderate themselves in a way, a lot of them get closed without my intervention, so it's currently a very manageable level for one person. Thanks for the offer though!
