### ISSUE TITLE
Show hint(s) after exercise completion

### ISSUE THREAD

**Issue by felipemoran** [rust-lang/rustlings#1373]
Hi, first of all thanks for the great work on the exercises! It's a joy to learn from them.

A suggestion I'd like to make is to print all hints for a given exercise after it's successfully completed. They often contain useful information and I aways find myself having to double check if I read them.

This could be an optional flag for the `watch` command to prevent people that solved it in a particular way from getting spoilers on other possible solutions.

I considered updating the code myself for this but unfortunately I'm still only getting started, so any help is very much appreciated!

**Comment by rb5014** [comment]
![Capture](https://user-images.githubusercontent.com/105397317/235383349-3823e599-eb10-45d4-8083-91d10ac31943.PNG)
Like this ?

**Comment by rb5014** [comment]
I'm still trying to understand how to send these changes to the git
