### ISSUE TITLE
rustlings watch crashing with "Text file busy"

### ISSUE THREAD

**Issue by AsaAyers** [rust-lang/rustlings#139]
I'm not sure what other information to provide since I'm working on learning Rust, but if you can point me in the right direction I'll help gather whatever is needed to debug this.

> ----------**********----------
> 
> ⠙ Running exercises/standard_library_types/iterator3.rs...
> thread 'main' panicked at 'fail: Os { code: 26, kind: Other, message: "Text file busy" }', src/libcore/result.rs:997:5

**Comment by komaeda** [comment]
@AsaAyers Are you still having this issue? Sounds like some other program was using the text file, maybe your editor?
