### ISSUE TITLE
Clarify expected solution for iterator3

### ISSUE THREAD

**Issue by yogo1212** [rust-lang/rustlings#1403]
It is possible to implement both `result_with_list` and `list_of_results` using the same line:

```
fn result_with_list() -> Result<Vec<i32>, DivisionError> {
    let numbers = vec![27, 297, 38502, 81];
    numbers.into_iter().map(|n| divide(n, 27)).collect()
}

fn list_of_results() -> Vec<Result<i32, DivisionError>> {
    let numbers = vec![27, 297, 38502, 81];
    numbers.into_iter().map(|n| divide(n, 27)).collect()
}
```

but it is unclear whether that is desired.

Should that be hinted at or pointed out in comments?

**Comment by shadows-withal** [comment]
I don't think it needs to be DRYed, a bit of repetition is good when it proves a point (like how useful `collect()` is).
