### ISSUE TITLE
strings2 hint can be a bit misleading

### ISSUE THREAD

**Issue by Nagidal** [rust-lang/rustlings#1407]
The hint for `strings2` can be a bit misleading with regards to the coercion of the `String` variable `word`. The hint says that it is possible to "add one character to line 9 (...) that will coerce the `String` into a string slice". 

By this you mean to add a `&` to `word` in the function call:
```rust
is_a_color_word(word)
```
should become
```rust
is_a_color_word(&word)
```

It's just that, technically, the `&` does not coerce the word into a `&str`. A `&word` is just a `&String`. (If _you  yourself_ want to coerce it to `&str` you need to write `&word[..]`). The coercion you talk about in the hint happens because `String` [implements](https://doc.rust-lang.org/stable/std/string/struct.String.html#impl-Deref-for-String) the Deref trait in a way applicable to meet the function signature's needs.

A better wording in the hint would be: "There is a way to add one character to line 9, though, that _would let_ the `String` _coerce_ into a string slice."

Note aside: A user might ask why is it that a `&String` (a borrowed String) will coerce into `&str` whereas a `String` (owned) will not. The [Deref trait](https://doc.rust-lang.org/stable/std/string/struct.String.html#impl-Deref-for-String), after all, is implemented for String, isn't it? Well, I don't know the answer to that. But I'm wondering if it has something to do with the [fn deref's signature](https://doc.rust-lang.org/stable/src/alloc/string.rs.html#2459), in the source of the Deref implementation itself. The `deref` function _borrows_ the `self` argument (it takes a `&self`) so maybe that's why only a `&String` can deref-coerce, rather than a `String`, maybe? 🤷🏻‍♂️ Although why shouldn't the owner of the String not be able to call its fn deref is still a mystery to me.

**Comment by shadows-withal** [comment]
I don't really think changing the hint like like you suggested would change its meaning – definitely not for beginners who don't know about `Deref`, but also not necessarily for people who know how it works. The character `&` will _technically_ induce the coercion via `deref()`, converting it from `&String` to `&str`. There is no "intermediate" type here, the dereferencing happens via the trait implementation, so the original hint comment is correct. The only thing that happens is that the `deref()` function is called somewhere down the compiler stack.

**Comment by Nagidal** [comment]
> I don't really think changing the hint like like you suggested would change its meaning – definitely not for beginners who don't know about `Deref`, but also not necessarily for people who know how it works. 

I agree with the first part. It was exactly my goal _not to change the meaning_ of the original hint for beginners who don't know much about `Deref`. But for the people who do know a bit more, I think they clearly see that the hint is misleading. Even a beginner who has read chapter 15.2 of the book will notice the falsehood in this. Further you say:

> The character `&` will _technically_ induce the coercion via `deref()`, converting it from `&String` to `&str`. 

This is wrong. The character `&` induces nothing. It just creates a reference to the `String`. Really. The deref coercion is done implicitly by the compiler because the function requires a `&str` and `Deref` with target `str` is implemented for `String`. As the book [writes](https://doc.rust-lang.org/stable/book/ch15-02-deref.html#implicit-deref-coercions-with-functions-and-methods): 

> deref coercion can convert &String to &str because String implements the Deref trait such that it returns &str.

It really has nothing to do with the `&` although it may seem so, because the `deref` function called in this given context can only operate on `&String` rather than `String`.

Look @shadows-withal, in the book, which has been written for beginners, the authors found it very important to point out what _exactly_ is happening when a `&String` deref coerces into `&str`. Rustlings course referred to the book in many previous hints and encouraged the student to read up on certain topics. Sometimes even in the Rust Reference book (not for beginners). Now you have such a textbook situation in this exercise and instead of encouraging the students to go and read up on it, you gloss over this whole scenario with an ambiguously worded hint, which, when taken literally, is teaching the wrong thing. Shall the beginner who never heard of deref coercion, who just recently learned that `&` creates a reference, now learn that `&` also does the coercion? If not, then please reopen the issue.

**Comment by shadows-withal** [comment]
> But for the people who do know a bit more, I think they clearly see that the hint is misleading.

No. This is not an issue of how the semantics of the Rust compiler interact with implicit reference conversion, and more of an issue with how to convey this notion in the English language. We could probably argue for hours on end on who is correct, but as it stands, bikeshedding over changing a couple of words that barely change the sentence's meaning does not benefit either of us. (Besides, you're, afaik, the first person to bring this up)

> in the book, which has been written for beginners, the authors found it very important to point out what exactly is happening when a &String deref coerces into &str

In chapter 15, which is lengths away from chapter 8.2, where strings are first introduced. In my opinion, it's not fair to burden learners at this point in the course with semantics on how Rust converts references. Rust already has a pretty steep learning curve, and Rustlings is less about understanding the semantics behind how Rust's type and ownership system works, and more about getting your feet wet with some of the syntax, seeing what kind of errors the compiler will produce that you'll likely see more often when writing Rust, etc... you'll likely be reading the book anyways when going through the course, which is where all of those advanced concepts are explained.

What we CAN do, however, is amend the hint to link to this chapter. Something like `Side note: If you're interested in learning about how this kind of reference conversion works, you can jump ahead in the book and read this part in the smart pointers chapter: [link]`. If you're willing to open a pull request adding that, I'd be happy to merge it.
