### ISSUE TITLE
the percent progress is always 0.0%

### ISSUE THREAD

**Issue by digevil** [rust-lang/rustlings#1410]
as title, and the pic below, the percent progress is always 0.0%
<img width="867" alt="截屏2023-03-06 00 42 37" src="https://user-images.githubusercontent.com/375281/222973881-2f954603-dcfb-4c7a-bf11-01e0cbe033c8.png">

system info:

- macOs 13.2, m1 air
- rustc 1.66.1
- rustlings 5.4.0

**Comment by sourproton** [comment]
Having the same problem

- Arch Linux
- rustc 1.67.1
- rustlings 5.4.0

**Comment by shadows-withal** [comment]
Fixed in #1404
