### ISSUE TITLE
rust-analyzer fails to provide diagnostics after 'rustlings lsp' (Windows 11)

### ISSUE THREAD

**Issue by GersiD** [rust-lang/rustlings#1421]
------problem-statement----

After running rustlings lsp and setting cargo to use all features (for the exercise feature). Rust analyzer still fails to recognize the workspace and populate the exercises subdirectory with diagnostic information.

Please note that I still get Syntax Errors

---------env-info-----------
- Neovim Version: v0.9.0-dev-1147+ge389b1890
- cargo 1.66.0 (d65d197ad 2022-11-15)
- rust-analyzer 1.68.0 (2c8cc343 2023-03-06)

-------what-I-tried--------
1. Run rustligns lsp multiple times after re installing rustlings
2. setting cargo. Features to "exercises"
3. setting cargo.features to "all"
4. updating rust
5. updating rust-analyzer
6. trying to see if VScode gets it
7. manually adding the exercise subdir into the cargo.toml file with 
```
[features]
default = ["exercises"]
exercises = []
```

None of the above worked :(

**Comment by GersiD** [comment]
Please tell me what file I should use to test the diagnostics. Currently I am testing traits4.rs (because that's what I made it up to without the diagnostics).

**Comment by jnnnnn** [comment]
I spent a couple of hours trying to figure this out too (windows 10, the only weird thing about my rust installation is SCCACHE). 

I ended up ditching the rust-project.json approach and [generating mod files](https://gist.github.com/jnnnnn/9767f9f6ebae03840fcb9bc438107385) instead.

**Comment by GersiD** [comment]
@jnnnnn Thank you! this works for rustlings files that are in directories but for things like quiz1,2,3 this solution does not work. I am working out now how to change it so that it works and then I will open a PR with you. Thank you!
