### ISSUE TITLE
Improve hints for traits, generics and Quiz3

### ISSUE THREAD

**Issue by 1oglop1** [rust-lang/rustlings#1426]
Hi, I am completely new to Rust and trying these exercises. I am familiar with Python and more or less TypeScript.

Up until Generics and Traits everything was well explained and hints provided enough information on what to read.

However, the traits section does not provide much information at all. 

The description and hints in quiz3 assume a lot of knowledge which wasn't previously mentioned.

In the description it says https://github.com/rust-lang/rustlings/blob/9acefe8b3a2bed6e23dc31e9c1d5e9c5f6ab7596/exercises/quiz3.rs#L12-L13

but the todo note is https://github.com/rust-lang/rustlings/blob/9acefe8b3a2bed6e23dc31e9c1d5e9c5f6ab7596/exercises/quiz3.rs#L51

Hint goes as:
```
To find the best solution to this challenge you're going to need to think back to your
knowledge of traits, specifically Trait Bound Syntax -  you may also need this: `use std::fmt::Display;`.
```

I do not remember the term `Trait Bound Syntax` being mentioned before. Also, there was no opportunity to try `use std::fmt::Display;`.

This makes the quiz very complicated for me because I am unable to associate the hint with the information from the rust book or rust by example. 

It would be great if the text contained more links to examples.

What actually helped me to finish the exercise was 
First make the change of https://github.com/rust-lang/rustlings/blob/9acefe8b3a2bed6e23dc31e9c1d5e9c5f6ab7596/exercises/quiz3.rs#L53 to `A+` 

And then the compiler complained that the grade expected `f32` but found `&str`. Which ultimately lead me to use what I learned in `generics2` -> `pub struct ReportCard<T> ` and after implementing all this the compiler suggested using `std::fmt::Display;`.

 - I'd probably move the todo directly above the line which is supposed to be changed 
https://github.com/rust-lang/rustlings/blob/9acefe8b3a2bed6e23dc31e9c1d5e9c5f6ab7596/exercises/quiz3.rs#L50-L55

```rust
fn generate_alphabetic_report_card() {
        let report_card = ReportCard {
        // TODO: Change 2.1 to "A+"
            grade: 2.1,
            student_name: "Gary Plotter".to_string(),
            student_age: 11,
```

**Comment by Eshanatnight** [comment]
Hey! So in my opinion, I think the it is a good practice to read the [README.md](https://github.com/rust-lang/rustlings/blob/main/exercises/traits/README.md) files as you progress. I understand that it takes you out of the immersion and the flow.

As for the `std::fmt::Display`, yes there is no explicit exercise that shows how to use builtin traits. So someone going through the exercise can go [here](https://doc.rust-lang.org/book/ch10-02-traits.html#using-trait-bounds-to-conditionally-implement-methods), it is linked in the README file.

**Comment by asadsnowman** [comment]
I agree that this quiz seems to need a bit of improvement. I read the Rust Book up through chapter 15 before starting the rustlings and breezed through almost everything until quiz3, where I was completely stumped until I googled solutions. Why even make the student change the second test from 2.1 to "A+"? That seems to add a whole separate layer of complication to a quiz that already asks you to make abnormally large leaps in logic and knowledge compared to previous problems and quizzes.

**Comment by mo8it** [comment]
Version 6 [improved the exercise a lot](https://github.com/rust-lang/rustlings/commit/64c2de95ca95c1d23dcb416723b33ccdfca9c956). Most importantly, the grade in the test is already changed to `"A+"`.

If you still have any suggestions for [the current version](https://github.com/rust-lang/rustlings/blob/main/exercises/quizzes/quiz3.rs), I can reopen the issue :)
