### ISSUE TITLE
I don't understand why the last a will output 78

### ISSUE THREAD

**Issue by hindlee** [rust-lang/rustlings#1433]
> a = 81, b = 6

```

pub fn divide(a: i32, b: i32) -> Result<i32, DivisionError> {
    let c: i32 = a / b;
    println!("{}", c * b);
    println!("{}", a);
    match b {
        0 => `Err(DivisionError::DivideByZero),`
        other => {
            println!("{}", a);
            match c * b {
                a => {
                    println!("{}", a);
                    return Ok(c);
                }
                other => {
                    return Err(DivisionError::NotDivisible(NotDivisibleError {
                        dividend: a,
                        divisor: b,
                    }))
                }
            };
        }
    }

```

result:
78
81
81
78

**Comment by YasinVeliyev** [comment]
Can you share all code?

**Comment by YasinVeliyev** [comment]
> > Hi.Can you share all code?
> 
> This is the third iterator chapter in the exercise

Which exercise?

**Comment by YasinVeliyev** [comment]
Use f

**Comment by YasinVeliyev** [comment]
First check if b==0  and return error
Then you can define c=a/b.
Otherwise your app will crash

**Comment by hindlee** [comment]
> First check if b==0  and return error
> Then you can define c=a/b.
> Otherwise your app will crash

Thinks

**Comment by hindlee** [comment]
> First check if b==0  and return error
> Then you can define c=a/b.
> Otherwise your app will crash

thanks

**Comment by YasinVeliyev** [comment]
> > First check if b==0  and return error
> > Then you can define c=a/b.
> > Otherwise your app will crash
> 
> thanks

You are welcome
