### ISSUE TITLE
Macro Autocomplete strangely doesn't work on VSCode

### ISSUE THREAD

**Issue by jaymehta-g** [rust-lang/rustlings#1436]
`rustlings --version`
`v5.4.1`
`rustc --version`
`rustc 1.67.1 (d5a82bbd2 2023-02-07)`
`ls -la`
`Get-ChildItem : A parameter cannot be found that matches parameter name 'la'.` (is this meant for linux??)
Running Windows 10

I ran `rustlings lsp` and it seems to be working because I do get underlines syntax errors, but autocompleting specifically for macros just does not work. When I open another VSCode window with a different rust cargo, autocomplete can fill in `println!` `assert!` etc. just fine, only in the rustlings cargo does it mess up. Also autocomplete for all other rust keywords works fine.

**Comment by jaymehta-g** [comment]
noticed another strange thing: auto filling arms of a match statement through the "Quick Action" button also doesn't work when I'm in rustlings but works fine in other crates...

**Comment by shadows-withal** [comment]
Weird, but this sounds like a `rust-analyzer` (the LSP implementation) issue rather than on our end. All that running `rustlings lsp` does is generate a file that `rust-analyzer` can read that points to the exercise files (because we don't use a conventional Cargo project structure).
