### ISSUE TITLE
generics1: does not require use of explicit generics

### ISSUE THREAD

**Issue by benjaminbauer** [rust-lang/rustlings#1448]
The idiomatic solution for `generics1` is to simply remove the explicit type from the variable binding since it can be inferred:
```rust
fn main() {
    let mut shopping_list = Vec::new();
    shopping_list.push("milk");
}
```

The hint says:
```
Vectors in Rust make use of generics to create dynamically sized arrays of any type.
You need to tell the compiler what type we are pushing onto this vector.
```

Two problems with this:

1. The solution is better without specifying a type and thus is not teaching/requiring the explicit use of generics
2. The hint is wrong, because there is not _need_ to tell the compiler the type

**Comment by Eshanatnight** [comment]
I agree with you. Maybe the thought process at the time of writing was 

- as a way of learning about generics without depending much on the compiler, or better phrased as to get the hang of the generic syntax
```rust
let mut shopping_list: Vec<&str> = Vec::new();
```
- and going of the reasoning, making one familiar to the explicit syntax, would make one more comfortable with the turbofish syntax in the future

Again, I do agree with you, but this is the conclusion I drew after reading `generics1.rs`.

**Comment by benjaminbauer** [comment]
I see two options here:

1. Make it explicit, that this example is not showing the idiomatic solution
2. Find a better example, where the use of generics is required. The challenge here is to find one that is simple enough, to not distract from the point being made

**Comment by Eshanatnight** [comment]
> Find a better example, where the use of generics is required. The challenge here is to find one that is simple enough, to not distract from the point being made

I agree with this too

**Comment by mo8it** [comment]
I rewrote the exercise in the upcoming version 6: https://github.com/rust-lang/rustlings/blob/v6/exercises/14_generics/generics1.rs
