### ISSUE TITLE
Cannot use the dbg! macro :(

### ISSUE THREAD

**Issue by omerGithub8** [rust-lang/rustlings#1458]
I'm very sad that the dbg! macro doesn't work inside the rustlings to print and check things and also to save keystrokes
I'm using vsCode and it doesn't print the dbg to the rustlings terminal

**Comment by shadows-withal** [comment]
Using `--nocapture` will make tests output their stdout:

![CleanShot 2023-04-02 at 12 44 19@2x](https://user-images.githubusercontent.com/6445316/229348100-8b0d23bc-6662-4544-8a9f-d862d3dfcc12.png)
