### ISSUE TITLE
Printout includes exercises/quiz1 compilation error, despite quiz1 passing verify, when completing subsequent exercises in "watch" mode

### ISSUE THREAD

**Issue by Pooletergeist** [rust-lang/rustlings#1459]
Going through the exercises in watch mode, after completing quiz 1, the printout shows quiz1 with compile errors whenever it introduces new exercises (like primitive_types 1 & 2).

<img width="569" alt="Screen Shot 2023-03-31 at 3 40 38 PM" src="https://user-images.githubusercontent.com/70556570/229245058-c5a56398-e8c5-475f-8a38-7308b7a53971.png">

At the same time, quiz1 passes the call to verify.

<img width="565" alt="Screen Shot 2023-03-31 at 5 20 46 PM" src="https://user-images.githubusercontent.com/70556570/229256005-45f4b269-a2c7-401d-aaea-52bc51687e17.png">

=====Issue Arises On=====
macOS Monterey v12.4
rustc 1.66.1
rustlings v5.4.1
<img width="467" alt="Screen Shot 2023-03-31 at 5 23 36 PM" src="https://user-images.githubusercontent.com/70556570/229256166-3ef5f3c7-26bc-460d-97e5-a02c086e1e6e.png">

Thank you!

**Comment by mo8it** [comment]
This is fixed in the newly released version 6 :D
