### ISSUE TITLE
I tried running the curl command on manjaro and this is what I get in the end

### ISSUE THREAD

**Issue by c0dr7** [rust-lang/rustlings#147]
Finished release [optimized] target(s) in 2m 12s
   Replacing /home/c0dr/.cargo/bin/rustlings
bash: line 97: rustlings: command not found
All done! Run 'rustlings' to get started.
[c0dr@c0dr-mc-gpc ~]$ ^C
[c0dr@c0dr-mc-gpc ~]$ rustlings
bash: rustlings: command not found
[c0dr@c0dr-mc-gpc ~]$

**Comment by ArpHiemstra** [comment]
I have the same issue, running archlinux cannot get rustlings to start. Same output as above.

**Comment by miller-time** [comment]
@c0dr7 @ghost do you have your `~/.cargo/bin` directory in your path?

I have the following in my ~/.profile :
```sh
export PATH="$HOME/.cargo/bin:$PATH"
```

However, it seems like install.sh does have a small bug.

You both had the following error during install:

```sh
 bash: rustlings: command not found
```

it was from this check (which didn't print its message upon failure):

https://github.com/rust-lang/rustlings/blob/34e31232dfddde284a341c9609b33cd27d9d5724/install.sh#L97
