### ISSUE TITLE
move_semantics3 solution places mut in front of parameter without explaining it is possible

### ISSUE THREAD

**Issue by lectrician1** [rust-lang/rustlings#1479]
The solution for this
```rust
fn main() {
    let vec0 = Vec::new();

    let mut vec1 = fill_vec(vec0);

    println!("{} has length {} content `{:?}`", "vec1", vec1.len(), vec1);

    vec1.push(88);

    println!("{} has length {} content `{:?}`", "vec1", vec1.len(), vec1);
}

fn fill_vec(vec: Vec<i32>) -> Vec<i32> {
    vec.push(22);
    vec.push(44);
    vec.push(66);

    vec
}
```
is to put a `mut` in front of the `vec` parameter in `fill_vec`. 

However, neither the [references](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html) or [ownership](https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html) Rust book pages explain that placing `mut` in front of a parameter is possible. I was stuck on this until I looked at an answer key.

**Comment by mo8it** [comment]
The current feedback from the compiler tells you to add `mut`. The current comment and hint should also be more helpful :)

![image](https://github.com/rust-lang/rustlings/assets/76752051/2a43eaa7-b426-4029-99ea-c7acfdb458e7)
