### ISSUE TITLE
Exercise Suggestion/Discussion: Add Exercises For Some Commonly Used Rust Crates

### ISSUE THREAD

**Issue by Ben2917** [rust-lang/rustlings#1481]
As the title says, I'm wondering what people think about introducing some exercises to rustlings that cover some useful or commonly used Rust crates. So for example, I've been looking into how I can follow my usual TDD practises in Rust and found the [mockall crate](https://docs.rs/mockall/latest/mockall/) that can be used to mock structs, set expectations etc. I'd be really interested in writing an exercise that teaches users how to utilise mockall since mocks are such a powerful tool for TDD. 

My question is, would this fall out of the scope of Rustlings? I personally believe it would be a natural expansion, however, I'm also very new to the project. I'd also be interested to hear suggestions about what exercises could be added for commonly used crates. To the experienced Rust devs, what tools do you feel you couldn't live without?

**Comment by mo8it** [comment]
Yes, this is out of scope, but what we could do instead is to support third-party exercises as mentioned  in https://github.com/rust-lang/rustlings/issues/1936. Closing in favor of that issue :)
