### ISSUE TITLE
Tests Pass no matter what if the code compiles

### ISSUE THREAD

**Issue by ZSteinberger** [rust-lang/rustlings#149]
Ran through the rustlings tutorial and had to remove the --nocapture flag in exrecise.rs in order for the tests to properly run.
Command:
rustlings verify
rustlings run <file>
Expected Results:
 If an assert fails there should be some output stating why.
Actual Results:
 A success message is displayed stating you passed the test. (only if the code can compile)

**Comment by stevenzyang** [comment]
+1

**Comment by komaeda** [comment]
Released [1.2.2](https://github.com/rust-lang/rustlings/releases/tag/1.2.2)
