### ISSUE TITLE
Hints to add offline documentation suggestions

### ISSUE THREAD

**Issue by Wilker-uwu** [rust-lang/rustlings#1501]
hi! thank you for making this a thing, i appreciate it <3

i just wanted to ask if it would be good to make available commands and text to make the hints and similar text to be completely accessible offline, possibly all with `cargo doc `[...]` --open` too. it would help me a lot since i will be without an internet connection very soon.

thank you for the attention ^^

**Comment by shadows-withal** [comment]
After you've completed the installation, everything should be available offline. `rustlings hint <exercise>` will work regardless of whether you have an internet connection or not.

If you're asking about other materials, for example the book, that can be accessed offline by running `rustup doc`.

**Comment by Wilker-uwu** [comment]
that i do know, but the problem is that there are several hints linking to online resources instead, rather than offering commands or link for offline ones. see for example `errors2`:
![ALT: screenshot of a terminal log, showing the output of the command `rustlings hint errors2`, with a highlighted text to a link for a page in The Rust Programming Language.](https://user-images.githubusercontent.com/10854855/235362234-022ef87a-d615-40a0-8c19-d4a39ef7387b.png)

it would be better if it instead¹ pointed to an equivalent page in the book linked by `rustup doc` (¹ or *additionally to, since there's also the chance where one could be running Rustlings in a place where files like these aren't as easily accessible.)

**Comment by shadows-withal** [comment]
Yeah, trying to somehow dynamically replace those points in the hints is a misendeavour, I think, given the different kinds of environments people use Rustlings in. I see two possible ways to improve the situation here:

- Replace or amend the book links with "See the Book, Chapter X, etc etc" so that it's easier for offline users to cross-reference the book
- Add a paragraph somewhere (intro exercises? readme?) hinting at the existence of `rustup doc`, since not a lot of people know about it, and even if you're not offline, it may be more comfortable to use because of the significantly faster page load speed

**Comment by Wilker-uwu** [comment]
what if there was instead a way to implement in Rustup itself a way to open a given indexed section of the book or doc? maybe it would be easier to approach this issue if it was implemented on Rustup's side?

**Comment by shadows-withal** [comment]
Definitely! Feel free to open an issue on Rustup's side for that, if that does get implemented I'd be happy to add support for it here.

**Comment by mo8it** [comment]
I will close this issue because there is nothing Rustlings can do right now. It would be nice if rustup could take a link and open its offline equivalent. If this gets implemented, feel free to open an issue to add a hint in the introduction message :)

**Comment by Wilker-uwu** [comment]
with https://github.com/rust-lang/rustup/pull/4070 closing https://github.com/rust-lang/rustup/issues/3345 there might be a way to do it soon. would it make sense to reopen this issue here at this point?

**Comment by senekor** [comment]
We should also keep in mind that not every user will have a Rust toolchain installed via rustup. Some users will prefer to install Rust via their package manager.
