### ISSUE TITLE
options3.rs and similar tasks should panic when there is a logic error to avoid false positives

### ISSUE THREAD

**Issue by nmay231** [rust-lang/rustlings#1503]
In the options3 task, you just have a println if there is no match:

```rust
let y: Option<Point> = Some(Point { x: 100, y: 200 });

match y {
    Some(p) => println!("Co-ordinates are {},{} ", p.x, p.y),
    _ => println!("no match"),
}
```

For this and similar tests, it should instead panic when matched incorrectly in case the user made a logic error. Otherwise, it would compile and show green lights unless they actually read the output, which I just skim most times, to be honest.

```diff
-    _ => println!("no match"),
+    _ => panic!("no match!"),
```

I'd be willing to make this contribution.

**Comment by shadows-withal** [comment]
Sounds good!
