### ISSUE TITLE
Running on macOS

### ISSUE THREAD

**Issue by vjay82** [rust-lang/rustlings#151]
This is what happens when following the instructions on macOS. Installed via your first line, then:

/tmp/rustlings(branch:0279294) » rustlings     

       welcome to...                      
                 _   _ _                  
  _ __ _   _ ___| |_| (_)_ __   __ _ ___  
 | '__| | | / __| __| | | '_ \ / _` / __| 
 | |  | |_| \__ \ |_| | | | | | (_| \__ \ 
 |_|   \__,_|___/\__|_|_|_| |_|\__, |___/ 
                               |___/      

Thanks for installing `rustlings`!

## Is this your first time?

Let's make sure you're up to speed:
- You have Rust installed, preferably via `rustup`
- You have `~/.cargo/bin` added to your PATH variable
- You have cloned this repository (https://github.com/rust-lang/rustlings)
- You have installed Rust language support for your editor
- You have locally installed the `rustlings` command by running:

```sh
cargo install --path .
```

If you've done all of this (or even most of it), congrats! You're ready
to start working with Rust.

To get started, run `rustlings verify` in order to get the first exercise.
Make sure to have your editor open!

------------------------------------------------------------
/tmp/rustlings(branch:0279294) » rustlings verify                                                                                                                           
⚠️  Compilation of exercises/variables/variables1.rs failed! Compiler error message:

error[E0425]: cannot find value `x` in this scope
 --> exercises/variables/variables1.rs:5:5
  |
5 |     x = 5;
  |     ^ not found in this scope

error[E0425]: cannot find value `x` in this scope
 --> exercises/variables/variables1.rs:6:36
  |
6 |     println!("x has the value {}", x);
  |                                    ^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.

**Comment by PatrickMcSweeny** [comment]
This appears to be functioning as intended. The idea is that you are supposed to fix the error messages by editing the exercise files yourself. In this case the compiler is telling you which file you need to edit. After you change the file, run the 'rustlings verify' command again to see if your change was successful.

**Comment by scostanzo** [comment]
like @PatrickMcSweeny said, you have to follow the error message and try to fix the problem, this is the goal of the exercises!
Good luck and have fun!
