### ISSUE TITLE
hashmaps exercise 3 assert incorrect and dual data

### ISSUE THREAD

**Issue by Eric-Busch0** [rust-lang/rustlings#1514]
Firstly this assertion here seems to be wrong. If there is something I am missing, then please correct me, but England, France is 4 and 1 respectively.

https://github.com/rust-lang/rustlings/blob/d45ec21b3c955785157cf12921cd987c864b0d94/exercises/hashmaps/hashmaps3.rs#LL76C26-L76C26

Second there are two insertions of England. 

England,France and Germany,England. 

So, the score gets written over and becomes 1 and not the 4 originally inserted.

This is not necessarily an issue, but the assertion would check for the lastly inserted value (Germany/England)

```rust
for r in results.lines() {

        let v: Vec<&str> = r.split(',').collect();
        let team_1_name = v[0].to_string();
        let team_1_score: u8 = v[2].parse().unwrap();
        let team_2_name = v[1].to_string();
        let team_2_score: u8 = v[3].parse().unwrap();


        // TODO: Populate the scores table with details extracted from the
        // current line. Keep in mind that goals scored by team_1
        // will be the number of goals conceded from team_2, and similarly
        // goals scored by team_2 will be the number of goals conceded by
        // team_1.
        

        scores.insert(team_1_name.clone(), Team{
            name:team_1_name,
            goals_scored: team_1_score,
            goals_conceded: team_2_score
        });
        scores.insert(team_2_name.clone(), Team{
            name:team_2_name,
            goals_scored: team_2_score,
            goals_conceded: team_1_score
        });

}

```

**Comment by musmuris** [comment]
The scores are cumulative - so England get 4 goals against France and 1 against Germany - so 5 in total as the assertion checks?
They also concede 2 against both France and Germany so total of 4.
You have to update an existing entry if there is one to get it to pass.

**Comment by Eric-Busch0** [comment]
This makes more sense. Thank you
