### ISSUE TITLE
rust-analyzer not integrating with rustlings using VSCode in Windows

### ISSUE THREAD

**Issue by dehan-jl** [rust-lang/rustlings#1525]
I am having an issue similar to the issues described here: https://github.com/rust-lang/rust-analyzer/issues/12235 and here https://github.com/rust-lang/rust-analyzer/issues/4894.

So I tried this on multiple machines:
- Machine A: Windows, Rust using MSVC, VSCode
- Machine B: Windows, Rust on WSL, VSCode using WSL Extension, rust-analyzer running in WSL.
- Machine C: MacOS, Rust installed natively, VSCode.

On both windows machines, rust-analyzer does not seem to be integrating nicely with the rustlings repo. For example, syntax checking is not working. However, on the mac, everything seems to be fine.

For all three machines, the project was opened in the rustlings root directory, and `rustlings lsp` was ran. However, the windows machines still did not seem to play nice.

I was using the following versions:
- rustc 1.69.0 (84c898d65 2023-04-16)
- rustlings v5.5.1

**Comment by shadows-withal** [comment]
Which version of the `rust-analyzer` VSCode plugin are you using?

**Comment by dehan-jl** [comment]
> Which version of the `rust-analyzer` VSCode plugin are you using?

Machine B & C: v0.3.1524

**Comment by dehan-jl** [comment]
My `rust-project-json` looks something like this:
```json
{
    "sysroot_src": "/home/<user>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library",
    "crates": [
        {
            "root_module": "exercises/clippy/clippy1.rs",
            "edition": "2021",
            "deps": [],
            "cfg": [
                "test"
            ]
        },
...
```

I suspect it might have something to do with the `rust-analyzer` extension as when I reload it on one of the BMW machines, it says "indexing 1/5", while on the Mac it says "indexing 1/10". Almost like the Mac is picking up dependencies whereas the windows machine is not. For me it's really peculiar that this is happing both using MSVC and WSL.

**Comment by shadows-withal** [comment]
Could you open an issue on r-a referencing this one, maybe? They might be able to figure out what's happening here, because I don't think (= hope) it's because of what's happening on our end.

**Comment by Veykril** [comment]
Just spotted this randomly (there was no new r-a issue opened afaik). Latest rustlings repo + latest r-a nightly works for me just fine on nightly on my windows machine. Could you post an entry of the rust-project.json from your windows machine maybe?

**Comment by mo8it** [comment]
Closing because @Veykril verified that it works :)

The whole class of such issues might just disappear when we use `Cargo.toml` instead of `rust-project.json` as described in https://github.com/rust-lang/rustlings/issues/1935
