### ISSUE TITLE
Hints for vec2.rs exercise hasn't been updated.

### ISSUE THREAD

**Issue by Andre97gps** [rust-lang/rustlings#1532]
Hello everyone, in the #1418 the `i` was changed to `element`.

```rust
fn vec_loop(mut v: Vec<i32>) -> Vec<i32> {
    for i in v.iter_mut() {
        // TODO: Fill this up so that each element in the Vec `v` is
        // multiplied by 2.
        ???
    }
``` 
```rust
fn vec_loop(mut v: Vec<i32>) -> Vec<i32> {
    for element in v.iter_mut() {
        // TODO: Fill this up so that each element in the Vec `v` is
        // multiplied by 2.
        ???
    }
``` 
but in the hints, is still the `i`:
```
Hint 1: `i` is each element from the Vec as they are being iterated. Can you try
multiplying this?

[...]
```

**Comment by shadows-withal** [comment]
Closed in https://github.com/rust-lang/rustlings/pull/1544.

**Comment by jhnance** [comment]
I think this was reverted.

I've downloaded Rustlings v5.5.1 and I'm getting the old hint again.

https://github.com/rust-lang/rustlings/blob/5.5.1/info.toml#L263

Would be happy to submit another PR to fix this so it matches the exercise code, if it's wanted.

**Comment by shadows-withal** [comment]
This isn't in a release yet, it's only on `main`.

**Comment by jhnance** [comment]
My bad; I misread one of the changelog entries and mistook it for this PR.
