### ISSUE TITLE
rustlings watch doesn't show fail test case

### ISSUE THREAD

**Issue by bomcon123456** [rust-lang/rustlings#1554]
Hi, awesome project, I'm currently running on Mac M1, and the problem is when there are failure test case, it doesn't show which tests are failed and the logs, it just showed passed test just like the image below. Running the same code in ubuntu does show failed tests.
<img width="1119" alt="image" src="https://github.com/rust-lang/rustlings/assets/20278911/45183e39-2087-429f-a3f5-4f0750f2261c">

**Comment by bomcon123456** [comment]
<img width="957" alt="image" src="https://github.com/rust-lang/rustlings/assets/20278911/800e2953-ebcd-41b4-845f-7312a4646402">
`rustling verify/run` has the same outcome

**Comment by shadows-withal** [comment]
Does running with `--nocapture` fix this?

**Comment by bomcon123456** [comment]
> Does running with `--nocapture` fix this?

thank you for the blazingly fast reply, I tried to use `rustlings --nocapture watch`, it does print out something more but I dont think it solve it completely?
<img width="1027" alt="image" src="https://github.com/rust-lang/rustlings/assets/20278911/63099b7f-dac0-4e68-b7a0-30cbe0e7f859">

**Comment by bomcon123456** [comment]
I see, thank you for your support!
