### ISSUE TITLE
`rustlings verify` fails due to 2 errors.

### ISSUE THREAD

**Issue by Phate6660** [rust-lang/rustlings#156]
```
! Compilation of exercises/variables/variables1.rs failed! Compiler error message:

error[E0425]: cannot find value `x` in this scope
 --> exercises/variables/variables1.rs:5:5
  |
5 |     x = 5;
  |     ^ not found in this scope

error[E0425]: cannot find value `x` in this scope
 --> exercises/variables/variables1.rs:6:36
  |
6 |     println!("x has the value {}", x);
  |                                    ^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
```

Edit: This is the first time running the command. I just cloned the repository, installed rustlings, and ran the command.

**Comment by Phate6660** [comment]
I'm an idiot.

**Comment by kitplummer** [comment]
So...I'm an idiot too.  But why?

**Comment by aruniyer** [comment]
> So...I'm an idiot too. But why?

And God said,
"let" there be variable?!

**Comment by kitplummer** [comment]
Ok, is this a lesson, or a bug?  :D

**Comment by Phate6660** [comment]
This was me being stupid. For some reason, I thought that it was broken, when it was really just the lesson telling me to fix it. 

I realized it was the lesson doing what it was supposed to, so I closed the issue I made.
