### ISSUE TITLE
`move_semantics2` doesn't show the print output

### ISSUE THREAD

**Issue by boyleconnor** [rust-lang/rustlings#1569]
Unlike other exercises containing the `println!` macro (such as [`primitive_types3`](https://github.com/rust-lang/rustlings/blob/c2264cabae976cf534be08942ff33f3a58f8795e/exercises/primitive_types/primitive_types3.rs)), the exercise [`move_semantics/move_semantics2.rs`](https://github.com/rust-lang/rustlings/blob/c2264cabae976cf534be08942ff33f3a58f8795e/exercises/move_semantics/move_semantics2.rs) does not actually show the printed output in the terminal--at least when I complete the exercise in `rustlings watch` mode.

Here is my completed version of the exercise:

<details>
<summary>move_semantics2.rs</summary>

```rust
// move_semantics2.rs
//
// Expected output:
// vec0 has length 3, with contents `[22, 44, 66]`
// vec1 has length 4, with contents `[22, 44, 66, 88]`
//
// Execute `rustlings hint move_semantics2` or use the `hint` watch subcommand
// for a hint.

// I AM NOT DONE

fn main() {
    let mut vec0 = Vec::new();

    let mut vec1 = fill_vec(&mut vec0);

    println!("{} has length {}, with contents: `{:?}`", "vec0", vec0.len(), vec0);

    vec1.push(88);

    println!("{} has length {}, with contents `{:?}`", "vec1", vec1.len(), vec1);
}

fn fill_vec(vec: &mut Vec<i32>) -> Vec<i32> {
    vec.push(22);
    vec.push(44);
    vec.push(66);

    vec.clone()
}
```

</details>

Here is the output:

<details>

<summary>Terminal output</summary>

```
✅ Successfully tested exercises/move_semantics/move_semantics2.rs!

🎉 🎉  The code is compiling, and the tests pass! 🎉 🎉

You can keep working on this exercise,
or jump into the next one by removing the `I AM NOT DONE` comment:

 8 |  // for a hint.
 9 |  
10 |  // I AM NOT DONE
11 | 
```

</details>

My rustc version is `rustc 1.70.0 (90c541806 2023-05-31)` and I am running on MacOS Ventura 13.4 (22F66).

**Comment by shadows-withal** [comment]
Oh, that seems to be because we're testing the exercise despite there being no tests...? Very strange, I'll fix it on main.

**Comment by boyleconnor** [comment]
I have tested and it now shows the correct output:

<details>
<summary>Output</summary>

```
🎉 🎉  The code is compiling! 🎉 🎉

Output:
====================
vec0 has length 3, with contents: `[22, 44, 66]`
vec1 has length 4, with contents `[22, 44, 66, 88]`

====================

You can keep working on this exercise,
or jump into the next one by removing the `I AM NOT DONE` comment:

 8 |  // for a hint.
 9 |  //
10 |  // I AM NOT DONE
11 |
```

</details>
