### ISSUE TITLE
What is learning order of topics in exercise folder?

### ISSUE THREAD

**Issue by BruceChen2017** [rust-lang/rustlings#158]
I am new to rust,but I don't know learning order of topics in exercise folder.Can somebody give me some guide? Start from `variables`? If so,what next?

**Comment by asdfhjkl** [comment]
If you run `rustlings watch` it will show you the errors that you have to fix in the intended order of the material.

**Comment by asdfhjkl** [comment]
If you run `rustlings watch` it will show you the errors that you have to fix in the intended order of the material.

**Comment by pringshia** [comment]
@BruceChen2017 - You can also find the ordering in the [`info.toml` file](https://github.com/rust-lang/rustlings/blob/6ef284bb1a94c6e8c07d0bb9c3c782172bf6b19c/info.toml) but yes `rustlings watch` will guide you through them automatically.
