### ISSUE TITLE
Exercise to learn tests appears to have incorrect logic

### ISSUE THREAD

**Issue by ltfschoen** [rust-lang/rustlings#159]
The logic in rustlings/exercises/test1.rs appears to be incorrect
Shouldn't the tests be:
```
    assert_eq!(price1, 110);
    assert_eq!(price2, 40);
```

**Comment by cjpearce** [comment]
This test seemed right to me. The first price is for 55 apples, which is over the threshold of 40, meaning that each should cost 1 dollar. The second is for 40 apples, which is not 'over 40', meaning that each should cost 2 dollars. It feels like the example could be improved, but in this situtation it seems like you might have just missed where it says that buying more than 40 apples at once lowers the price per apple.
