### ISSUE TITLE
remove the master branch

### ISSUE THREAD

**Issue by szabgab** [rust-lang/rustlings#1600]
I see the project has switched to use `main` branch. It might be a good idea to remove the `master` branch so not to cause confusion for potential developers.

**Comment by FrankXenarthra** [comment]
@szabgab I would like to work on this issue. However, I do not have the permission to delete the branch directly on the Website. And I cannot create a pull request with a deleted branch only with changes on existing branches. How can we proceed here?

**Comment by szabgab** [comment]
Thanks, but there is not much "to work on this issue". It is just a reminder to the maintainers of the project, the people who have direct commit access to the repository, that there is a left-over branch that *they* can remove if they want.

**Comment by FrankXenarthra** [comment]
Thank for the explanation.
