### ISSUE TITLE
Hint for exercise vecs2 mentions variable that doesn't exist

### ISSUE THREAD

**Issue by its-kos** [rust-lang/rustlings#1614]
The first hint for the exercise vecs2 is as follows "Hint 1 `i` is each element from the vec as they are being iterated. Can you try multiplying this?" The issue is that in code there's no variable *i*, the variable mentioned is named "element". This should be changed so as not to confuse people. 
This is the relevant code from vecs2:

    fn vec_loop(mut v Vec<i32>) -> Vec<i32> {
        for element in v.iter_mut() {
            //
            v[]
        }
        v
    }

**Comment by kfv** [comment]
This issue's already been addressed in 1e02f19 on May 31.
