### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by omalaspinas** [rust-lang/rustlings#1627]
Hello,

thank you for the great work in Rustlings!

I haven't found any information about it online so maybe it already exists maybe not.

I'm planning to use Rustlings for a Rust class in French. I will therefore (at least partly) translate hints and assignments in French (people in the class are not really fluent in English). Is there any plan to support more languages for Rustlings? Would there be any interest in doing such translations?

I don't know if there exists "a good way" to make such a translations (or a platform to do so)... For the moment I will just fork the repository and translate the relevant parts. If there is any interest for such things I would be very happy to share my translation.

**Comment by shadows-withal** [comment]
Would be an interesting feature to support (and I won't say I haven't thought about it before), but I agree that there's a lot of unknowns (we'd want to avoid copying exercises, for example), so for now, I think forking is the best option.

**Comment by omalaspinas** [comment]
Ok thanks! If help is needed I would be very happy to give a hand ;)

I guess this can be closed for now!

**Comment by shadows-withal** [comment]
If you want, I can keep this issue open as a feature tracking issue!

**Comment by omalaspinas** [comment]
It's up to you. If you like it better open for me it's fine as well!

**Comment by omalaspinas** [comment]
In case you are interested I finished the translation in my fork.

**Comment by mo8it** [comment]
Version 6 is now released and it allows you to create third-party exercises. You can use this features to publish a translation of the official exercises :D

See the [guide for third-party exercises](https://github.com/rust-lang/rustlings/blob/main/THIRD_PARTY_EXERCISES.md)
