### ISSUE TITLE
Update notify to v6

### ISSUE THREAD

**Issue by mo8it** [rust-lang/rustlings#1640]
Update `notify` to version 6. The jump to version 5 broke debounced events and at least one additional crate is needed ([notify-debouncer-mini](https://docs.rs/notify-debouncer-mini/latest/notify_debouncer_mini/) or [notify-debouncer-full](https://docs.rs/notify-debouncer-full/latest/notify_debouncer_full/)).

**Comment by NicMcPhee** [comment]
Should this be marked as closed? I think that #1639 resolves this, correct?

**Comment by mo8it** [comment]
No, I didn't update `notify` in that PR.
