### ISSUE TITLE
Smart Pointers and hints out of order

### ISSUE THREAD

**Issue by irbull** [rust-lang/rustlings#1654]
Maybe this is just how I've been working through the exercises, but I have one shell with `rustlings watch` running and another shell where I type `rustlings hint next` when I want to read the hints.

When I get to the smart pointer exercise, it seems that `rustlings watch` runs the exercises in alphabetical order within each directory, but `rustlings hint next` uses the order defined in `info.toml`. This means that the exercise is `arc1.rs` but the hint is for `box1.rs`. The hint was obviously very confusing. As others have mentioned, the smart pointer section is a bit of a leap already 😄 .

**Comment by irbull** [comment]
I guess the reason this happens with `smart_pointers` is that this is the first time that the exercises are not in alphabetical order. All other exercises have names like `string[n].rs`. But in this case we have names like `arc1` and `box1.rs`.

**Comment by irbull** [comment]
Maybe I jumped to conclusions and it's not the alphabetical order, but there is something strange going on here.

The exercises in smart pointers are in the order [arc1, box1, rc1, cow1] but the hints were in the order [box1, arc1, rc1, cow1]. The `info.toml` file has the order [box1, rc1, arc1, cow1]. I'm not sure what the expected order is.

I'm running this on a Mac.

**Comment by shadows-withal** [comment]
Huuuh, this does look a like a genuine bug, let's see...

**Comment by irbull** [comment]
I was just redoing some of the exercises, and I have an updated version of rustlings. This bug doesn't seem to happen anymore. Maybe it was something wacky on my system before or maybe something has been fixed. Either way, #closing.
