### ISSUE TITLE
Compilation error when running `cargo install --force --path .` for 5.6.* version

### ISSUE THREAD

**Issue by gilbertguan2385** [rust-lang/rustlings#1666]
facing compilation error when building from source and running `cargo install --force --path .` for 5.6.0 version.

OS: Windows 8.1
Rust: rustc **1.72.0** (**stable-x86_64-pc-windows-gnu**)

the error as below:
```
error: failed to compile `rustlings v5.6.0 (\xxx\path\to\rustlings)`, intermediate artifacts can be found at `\xxx\path\to\rustlings\target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by randych-gilad** [comment]
In case someone outright asks "have you tried 5.5.1" - yes and it works first try.
(I've the same problem as OP)

**Comment by gilbertguan2385** [comment]
checked that 5.6.1 has same compilation issue.

**Comment by andrewkboyd** [comment]
I found that I needed to install `gcc-multilib` for the compilation to work with the latest version.

Found the answer on [StackOverflow](https://stackoverflow.com/questions/6329887/how-to-fix-linker-error-cannot-find-crt1-o)

Not sure if this helps anyone else but it resolved it for me.

**Comment by mo8it** [comment]
Sorry for the late reply. I hope that the answer by @andrewkboyd was helpful. If not, please test the main branch again with the latest Rust version. If you still have problems, please reopen the issue and provide the whole error message.
