### ISSUE TITLE
Integrate semantic-rs

### ISSUE THREAD

**Issue by komaeda** [rust-lang/rustlings#168]
I'm tired of writing manual changelogs! Let's integrate `semantic-rs`. We would have to start using Angular style commit messages (which is no problem), but my  biggest concern is that crate auto-publishing is baked in there, and we don't need to publish a crate. @badboy do you know if there's any way to turn that off?

**Comment by badboy** [comment]
Sure, you can [disable release](https://github.com/semantic-rs/semantic-rs/blob/master/src/main.rs#L321-L326).

If it is just about the changelog though, [cargo changelog](https://github.com/yoshuawuyts/changelog) or [clog](https://crates.io/crates/clog) would be a sensible alternative.

**Comment by komaeda** [comment]
@badboy Thanks! clog sounds good.

**Comment by komaeda** [comment]
Closed in 34e31232dfddde284a341c9609b33cd27d9d5724!
