### ISSUE TITLE
Cannot directly call "rustlings" inside "rustlings" folder after following readme.

### ISSUE THREAD

**Issue by pegasusearl** [rust-lang/rustlings#1687]
I followed readme.

I did this
`
curl -L https://raw.githubusercontent.com/rust-lang/rustlings/main/install.sh | bash
`

But I can't run `rustlings`. No executable found.
apparently it doesn't exist in ~/rustlings. but it was in ~/rustlings/target/release.

But if I tried to run it from `~/rustlings/target/release`, rustling complain `/home/$USER/rustlings/target/release/rustlings must be run from the rustlings directory`.

What would be the correct way to use rustlings?
at the moment, I just `cd ~/rustlings` then run it like this `./target/release/rustlings`

**Comment by shadows-withal** [comment]
Can you paste the output of the install script? It seems like your Cargo is misconfigured to me.

**Comment by pegasusearl** [comment]
Yes it is. I tried to install rustup manually from the website now it's working.
