### ISSUE TITLE
How to update the rustlings(or exercises)

### ISSUE THREAD

**Issue by linc01** [rust-lang/rustlings#1694]
Hello,
Is there a way to do the update? I'm on Ubuntu. Thanks.

**Comment by shadows-withal** [comment]
The theoretically easiest way to update is described in [each release](https://github.com/rust-lang/rustlings/releases/tag/5.6.1):

```
git fetch
git checkout tags/5.6.1
```

Depending on how much you've worked on the exercises, a new version may be trying to overwrite one of your modified exercise files. Assuming you haven't committed yet, and you want to start from a clean slate:

```
git fetch
git stash # store changes in git's long-term memory
git checkout tags/5.6.1
```

You could also clone the new version of Rustlings in a different folder (without installing it), and selectively apply updated files by copying them. Hope this helps!
