### ISSUE TITLE
I have a question about the exercises/traits/traits2.rs

### ISSUE THREAD

**Issue by wangyanfu** [rust-lang/rustlings#1695]
![image](https://github.com/rust-lang/rustlings/assets/3389763/a33aa734-ca38-4a69-81bd-dc5161e15da1)
see line 19, i'd tired to add a `mut` before `self` , it's different from the origin tarit define in line 14, but it does compile pass,
why?
i remember in the impl block the function's signature must same with the tarit's define

**Comment by wangyanfu** [comment]
Oh sorry, i get it, close

**Comment by asasine** [comment]
What was your conclusion? I was also tripped up by needing to add `mut self` to the `impl`, even though it differs from the trait declaration.
