### ISSUE TITLE
Is making all hints proper Markdown a good idea?

### ISSUE THREAD

**Issue by docwilco** [rust-lang/rustlings#1698]
I'm working on a VSCode extension to help with Rustlings: https://marketplace.visualstudio.com/items?itemName=drwilco.rustlings-helper

One of the features is showing the hints when the user wants to. A lot of hints use Markdown, but not all of them do it well. Would it be welcome if I went through all hints in `info.toml` and update them all to use proper Markdown?

Examples:

- `variables3` doesn't have an empty line between the two paragraphs.
- `variables5` has the same problem.
- `variables6` uses ticks instead of backticks around `let` and `const`.
- `primitive_types3` should probably use triple backticks.

And many many more.

I'm quite willing to go through them all and make sure they render nicely, but figured it'd be a good idea to ask before getting started.

**Comment by shadows-withal** [comment]
First of all, thank you for the cool extension! And yes, I think at least clearing up uneven Markdown-style formatting is a good idea. We don't need to use stuff like headings, but making sure we use proper line break paragraph separators and backticks is something I'd happily merge.

**Comment by docwilco** [comment]
Awesome. Feel free to mess around with my extension, recommend doing it on a fresh Rustlings directory. 

I'll get started on the Markdown.
