### ISSUE TITLE
Gui Building Exercises

### ISSUE THREAD

**Issue by Adesoji1** [rust-lang/rustlings#1762]
Please could we also add exercises for building GUi's using rust un this link: https://github.com/rust-lang/rustlings/tree/main/exercises .i  really need help knowing how to build ui's using Rust. i have seen egui library but it's hard for me 1 :upside_down_face:

**Comment by mo8it** [comment]
Although a good idea, this is beyond the scope of Rustlings.
Rustlings focuses on teaching the language itself and not teaching about specific domains or crates in the ecosystem.

Personally, I recommend to you that you check out the examples provided by egui:
https://github.com/emilk/egui/tree/master/examples
