### ISSUE TITLE
502 response from rustlings.cool

### ISSUE THREAD

**Issue by WesternStar** [rust-lang/rustlings#1763]
502 response from sh.rustlings.cool. When I try to run the install command on my mac it does nothing and when I checked the website I was getting a 502 response

**Comment by about-hector** [comment]
Up, same here. 

I made sure to have xcode-select installed, updated rustup and everything.

**Comment by shadows-withal** [comment]
Should be working again, not sure why it didn't before...

**Comment by NULLx76** [comment]
yeah, had some issues today as well again
