### ISSUE TITLE
Exercise modules2.rs uses partially outdated syntax

### ISSUE THREAD

**Issue by joshi001** [rust-lang/rustlings#178]
Lines 5 and 6 use the unnecessary `self` keyword, which can be deleted. Lines 9, 10, 14, and 15 has the keyword `&'static str` when only `&str` is necessary.

**Comment by Jesse-Cameron** [comment]
Hi @joshi001,

When you remove the `self` keyword from line 5 & 6, the compiler complains with:
```
error[E0432]: unresolved import `fruits`
 --> exercises/modules/modules2.rs:5:13
  |
5 |     pub use fruits::PEAR as fruit;
  |             ^^^^^^ help: a similar path exists: `self::fruits`

```
The alternative would be doing something like `delicious_snacks::fruit::PEAR`. However I am not sure that this would be more idomatic.

Keen to hear your thoughts!
