### ISSUE TITLE
macros2 run command panicking

### ISSUE THREAD

**Issue by Kurlgargyey** [rust-lang/rustlings#1796]
Hi, I'm not sure if this is a bug, but it seems to be persistent and I can't really figure out how to fix it.

Any time I try to solve macros2.rs, the watch subcommand just exits. If I manually try to run macros2, the following error shows up:

"thread 'main' panicked at 'Failed to run 'run' command: Os { code: 5, kind: PermissionDenied, message: "Zugriff verweigert" }', src\exercise.rs:189:14"

This error does not occur when the exercise is still in its unsolved state. I can work around it by not using the watch subcommand and manually running the exercises as I continue through the course.

My version info:
I am on Windows 10.
rustc 1.74.0 (79e9716c9 2023-11-13)
rustlings v5.5.1 (this is odd, since I am on 5.6.1)

$ ls -la
total 69194
drwxr-xr-x 1 RK 1049089       0 Dec  4 15:49 ./
drwxr-xr-x 1 RK 1049089       0 Aug  2 11:30 ../
-rw-r--r-- 1 RK 1049089   67761 Dec  1 11:16 .all-contributorsrc
drwxr-xr-x 1 RK 1049089       0 Aug  2 11:30 .devcontainer/
-rw-r--r-- 1 RK 1049089     109 Aug  2 11:30 .editorconfig
-rwxr-xr-x 1 RK 1049089      78 Dec  1 11:16 .envrc*
drwxr-xr-x 1 RK 1049089       0 Dec  4 15:28 .git/
drwxr-xr-x 1 RK 1049089       0 Aug  2 11:30 .github/
-rw-r--r-- 1 RK 1049089     234 Dec  1 11:16 .gitignore
-rw-r--r-- 1 RK 1049089     169 Aug  2 11:30 .gitpod.yml
-rw-r--r-- 1 RK 1049089      61 Aug  2 11:30 .markdownlint.yml
drwxr-xr-x 1 RK 1049089       0 Aug  2 11:30 .vscode/
-rw-r--r-- 1 RK 1049089   86647 Dec  1 11:16 AUTHORS.md
-rw-r--r-- 1 RK 1049089   26659 Dec  1 11:16 Cargo.lock
-rw-r--r-- 1 RK 1049089     659 Dec  1 11:16 Cargo.toml
-rw-r--r-- 1 RK 1049089   49359 Dec  1 11:16 CHANGELOG.md
-rw-r--r-- 1 RK 1049089    4301 Aug  2 11:30 CONTRIBUTING.md
drwxr-xr-x 1 RK 1049089       0 Dec  1 11:16 exercises/
-rw-r--r-- 1 RK 1049089    2062 Dec  1 11:16 flake.lock
-rw-r--r-- 1 RK 1049089    2416 Dec  1 11:16 flake.nix
-rw-r--r-- 1 RK 1049089   43747 Dec  1 11:16 info.toml
-rwxr-xr-x 1 RK 1049089    3139 Dec  1 11:16 install.ps1*
-rwxr-xr-x 1 RK 1049089    4846 Aug  2 11:30 install.sh*
-rw-r--r-- 1 RK 1049089    1117 Aug  2 11:30 LICENSE
-rw-r--r-- 1 RK 1049089     774 Dec  1 11:16 oranda.json
-rw-r--r-- 1 RK 1049089    6529 Dec  1 11:16 README.md
-rw-r--r-- 1 RK 1049089    9081 Aug 21 11:27 rust-project.json
-rw-r--r-- 1 RK 1049089     284 Aug  2 11:30 shell.nix
drwxr-xr-x 1 RK 1049089       0 Dec  1 11:16 src/
drwxr-xr-x 1 RK 1049089       0 Aug 21 11:29 target/
-rw-r--r-- 1 RK 1049089 1396736 Dec  4 15:32 temp_10168_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Aug 21 11:20 temp_10840_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 1396736 Dec  4 15:32 temp_11108_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2764800 Aug 11 11:14 temp_1112_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 1396736 Dec  4 15:33 temp_12016_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Nov 30 14:12 temp_12264_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 1396736 Dec  4 15:32 temp_12460_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Nov 24 15:47 temp_12920_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Nov 24 15:54 temp_1324_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 1396736 Dec  4 15:49 temp_13596_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2904064 Dec  4 15:26 temp_1892_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2904064 Dec  4 15:27 temp_2340_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2764800 Aug 11 10:50 temp_2372_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2871296 Dec  1 15:54 temp_2596_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 1396736 Dec  4 15:31 temp_3400_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2756608 Aug 10 12:47 temp_4376_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2904064 Dec  4 15:30 temp_6484_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2756608 Aug  9 11:57 temp_6552_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Nov 28 16:06 temp_6828_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Aug 11 12:48 temp_7192_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 1396736 Dec  4 15:38 temp_7948_ThreadId1.pdb
-rwxr-xr-x 1 RK 1049089  206336 Dec  4 15:19 temp_8316_ThreadId1*
-rw-r--r-- 1 RK 1049089 2887680 Dec  4 15:19 temp_8316_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Nov 29 17:30 temp_8372_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Aug 17 12:05 temp_844_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2904064 Dec  4 15:29 temp_8944_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2748416 Aug  8 12:42 temp_904_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 1396736 Dec  4 15:45 temp_9052_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Nov 24 15:45 temp_9396_ThreadId1.pdb
-rw-r--r-- 1 RK 1049089 2789376 Aug 21 12:07 temp_9876_ThreadId1.pdb
drwxr-xr-x 1 RK 1049089       0 Dec  1 11:16 tests/

**Comment by matthri** [comment]
Hi, 

I'm currently trying to reproduce this but for me the exercise is showing the correct compilation error and after solving the exercise `rustlings watch` moves on to the next exercise without crashing. 

Can you please provide some more information on the failing case (e.g. whats your code of the `macros2` exercise when the crash occurs) ?

**Comment by YoungKamilson** [comment]
I have simmilar issue with clippy1.rs, when rustlings compiles file, error occures.

```Failed to write 📎 Clippy 📎 Cargo.toml file.: Os { code: 3, kind: NotFound, message: "System cannot fint desired path." }```

**Comment by glmcz** [comment]
> I have simmilar issue with clippy1.rs, when rustlings compiles file, error occures.
> 
> `Failed to write 📎 Clippy 📎 Cargo.toml file.: Os { code: 3, kind: NotFound, message: "System cannot fint desired path." }`
> 
> ![image](https://private-user-images.githubusercontent.com/95166936/333347124-4e3b2a11-bd07-4de1-8ce7-5db6eaf51662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzgzNjIsIm5iZiI6MTcxNjYzODA2MiwicGF0aCI6Ii85NTE2NjkzNi8zMzMzNDcxMjQtNGUzYjJhMTEtYmQwNy00ZGUxLThjZTctNWRiNmVhZjUxNjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDExNTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMWMyMThlNmY1YTNjOGU1NTg5ZDNlY2FjNmY0NzJhODIzODJjNmU4NGIyYmM3MDI4MWU4NjFlYTJhZDQ1YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gajke1253bHf-PmV6tZHXiyTGXzlIctizZa4dFGbZJ0)
> 
> We can also see where the error is thrown. It seems to be bug with clippy module.
> 
> I use rustlings inside Linux WSL and i didnt removed or changed cargo.toml file

I have a same problem. So far workaround is to manualy create a new Cargo.toml inside clippy dir with this content
[package]
                    name = "clippy1"
                    version = "0.0.1"
                    edition = "2021"
                    [[bin]]
                    name = "clippy1"
                    path = "clippy1.rs"
                    
btw. I don`t get why it is indented in src/exercise.rs:140

**Comment by mo8it** [comment]
This should be fixed in the [upcoming version 6](https://github.com/rust-lang/rustlings/tree/v6)
