### ISSUE TITLE
change base URL for rust-lang.org

### ISSUE THREAD

**Issue by radu-relantin** [rust-lang/rustlings#1800]
Change the base URL from rust-lang.org to rust-book.cs.brown.edu/

Reasoning is shown in the example below: 
[DEFAULT](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html#mutable-references) and [CSBROWN](https://rust-book.cs.brown.edu/ch04-02-references-and-borrowing.html)

**Comment by mo8it** [comment]
The interactive version of the book is still experimental :/

**Comment by mo8it** [comment]
After thinking about it, I think that we should stick to the stable, official Rust book. It would be awesome if the improvements get merged into the official book :)
