### ISSUE TITLE
rust-analyzer suggests me to execute `rustup component add rust-src`

### ISSUE THREAD

**Issue by K0R7** [rust-lang/rustlings#1810]
I ran the install script on Linux and opened the folder with vscode. After running `rustlings lsp` and installing rust-analyze, it told me "could not find libcore in loaded sysroot at `/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library` try running `rustup component add rust-src` to possible fix this". So I ran this command and then everything was OK. Now I wonder if this step is necessary, could we integrate it into the `rustlings lsp` command?

**Comment by K0R7** [comment]
This issue can be reproduced in a blank codespace.

**Comment by deepkrg17** [comment]
`rust-src` is required by `rust-analyzer`.
It has no direct connection with `rustlings`.
So, I don't think this issue is valid.

**Comment by matthri** [comment]
Yes the `rust-src` component contains the code for the rust standard library, which is used by `rust-analyzer` to provide auto-completion.
So in theory `rust-analyzer` should complain in every rust project if this component is missing and not just in the `rustlings` project.

If for some reason this is a `rustlings` specific behavior and works in other projects then please reply here so we can do some debugging why this is happening.
