### ISSUE TITLE
Module declaration missing warning in IntelliJ

### ISSUE THREAD

**Issue by tastapod** [rust-lang/rustlings#1825]
First up, I'm loving rustlings. It's addictive!

In IntelliJ 2023.3.2 with the JetBrains Rust plugin (233.23135.116) I get a warning whenever I open a module, that says *Module declaration missing. This may impact smart editing features and auto-completion.* (See image below.)

I think it is because all the exercises are technically detached modules; they aren't referenced in a `lib.rs` or `main.rs` elsewhere.

I can suppress this warning by disabling the `Detached file` inspection in the project settings (Editor -> Inspections -> Rust -> Detached file).

The Rust plugin seems to be working ok, with completions, etc., and the rustlings watch process is working fine too, so I'm posting this issue mostly for awareness.

ObSetup:
- OS: macOS 14.2.1
- rustc version `1.75.0 (82e1608df 2023-12-21)`
- rustlings version `5.6.1`
 
![image](https://github.com/rust-lang/rustlings/assets/3180/348163a1-fa75-4f41-8a2c-66933a502811)

**Comment by shadows-withal** [comment]
Did you run `rustlings lsp` to see if that helps? AFAIK IntelliJ editors don't use `rust-analyzer`, but they may still respect the `rust-project.json` that that command generates, not sure though...

**Comment by shadows-withal** [comment]
Right, then I think that's just going to be something that the editor will keep complaining about, I'm afraid. It's good that there's a way to disable the warning, at least.

**Comment by tastapod** [comment]
I just noticed something else, which I think is related. I can't navigate to rustlings code in the same file.

In [structs3.rs][] when I go to `Package::new` on [line 53][], I can't navigate to the definition of `new` using Cmd-B (which is a few lines above), but I can navigate to e.g. `String::from` in the core library. So IntelliJ isn't able to index the current file.

So the package indexing is definitely A Thing in the exercise sources, I just can't figure out how to resolve it.

[structs3.rs]: ../blob/main/exercises/07_structs/structs3.rs
[line 53]: ../blob/main/exercises/07_structs/structs3.rs#L53

**Comment by mo8it** [comment]
Closing because this should be fixed in https://github.com/rust-lang/rustlings/issues/1935

Also this might be outdated anyway since there is RustRover now.
