### ISSUE TITLE
 In primitive types, incorrect denomination for non-alphabetical letters. (Japanese)

### ISSUE THREAD

**Issue by ProHaller** [rust-lang/rustlings#1834]
I am a beginner and I might be missing something, but the following code classifies the Japanese ideograms as alphabetical.
For example, the character '龍' (U+9F8D in Unicode) returns `true`. 

![CleanShot 2024-01-20 at 13 17 11@2x](https://github.com/rust-lang/rustlings/assets/88140523/cd4bfdd5-9904-4851-80bb-e249333a9d9e)

This surprises me in a few places. 
First, I thought that `is_alphabetic(chr: u8)` returned true for all semantic letters and that the denomination "alphabetical" was just an oversight that should include letters from abjab, and syllabaries, but it appears that's not the case: 
```
pub fn is_alphabetic(chr: u8) -> bool {
  (chr >= 0x41 && chr <= 0x5A) || (chr >= 0x61 && chr <= 0x7A)
}
```
Since the character '龍' (U+9F8D in Unicode) is encoded in UTF-8 as a sequence of three bytes: 0xE9, 0xBE, 0x8D , I feel it shouldn't match at all… 

What am I missing?

**Comment by FilipRazek** [comment]
Hi, where did you find the `is_alphabetic` definition? Looking at the latest Rust version I see this ([source](https://github.com/rust-lang/rust/blob/master/library/core/src/char/methods.rs)):
```rust
pub fn is_alphabetic(self) -> bool {
    match self {
        'a'..='z' | 'A'..='Z' => true,
        c => c > '\x7f' && unicode::Alphabetic(c),
    }
}
```

`unicode::Alphabetic` re-exports `unicode_data::alphabetic::lookup` which can be found [here](https://github.com/rust-lang/rust/blob/master/library/core/src/unicode/unicode_data.rs)


In any case the character '龍' is indeed considered as alphabetical. If this is a mistake, it is probably an error in the Rust compiler itself, or the Unicode standard.

**Comment by Y5Yash** [comment]
I have a slightly different query here. `.is_alphabetic()` fails to compile for `your_character` being a number, array, or a string, so why bother even having `else if your_character.is_numeric()` and `else ...` in the first place?
For emojis, the conditional goes to the `else ...` statement.

**Comment by FilipRazek** [comment]
I think that `.is_numeric` can still be called on numbers that have character type, such as '3' or '5'

**Comment by Y5Yash** [comment]
I think I made a mistake in understanding it earlier. Ignore my previous comment. The exercise works as intended. Apologies.
