### ISSUE TITLE
options/options1 comment could lead to incorrect interpretation of the problem

### ISSUE THREAD

**Issue by tomasguinzburg** [rust-lang/rustlings#1847]
`rustlings/excercises/options/options1.rs` invites to use the Option types to manage the return value of a function that checks whether there's icecream or not.

Both scenarios where there's a known amount of icecream are expected to be `Some` values, and the excercise asks to "gracefully handle values where the hour of the day is larger than 23". Sure, using a `None` is a possibility, but another one is to just `time_of_day % 24`, specially in the context of the comment:

```
// We use the 24-hour system here, so 10PM is a value of 22 and 12AM is a
// value of 0 The Option output should gracefully handle cases where
// time_of_day > 23.
```

Which I think sounds more biased towards the modulo solution than the behaviour expected from the tests. Maybe some kind of rephrasing as to what is understood as "graceful" could be more leading as to *why* we are using an Option as return type here. Is the function only supposed to work today? 

Will the ice-cream be automatically replenished every day at zero hours? I think both of this statements are equally funny and far-fetched, and nothing points clearly towards it being the former and not the latter that is true.

**Comment by bangjiehan** [comment]
I have same comment about this exercise.

**Comment by shadows-withal** [comment]
Right, I agree that the comment could be rephrased to explain that if `time_of_day = 493`, that's an invalid state, and that we want to handle that gracefully by returning `None`. If someone wants to go for a PR, I'll happily merge it, otherwise I'll get to it at some point :+1:

**Comment by mo8it** [comment]
Improved in the upcoming version 6: https://github.com/rust-lang/rustlings/blob/v6/exercises/12_options/options1.rs
