### ISSUE TITLE
errors3.rs has outdated informations

### ISSUE THREAD

**Issue by rusty-snake** [rust-lang/rustlings#185]
https://github.com/rust-lang/rustlings/blob/5e1d7c30767a7e138e02cd5e2935aab635b3762b/exercises/error_handling/errors3.rs#L48-L58

Since rust 1.26 `main` can also return Result.

**Comment by mikemorris** [comment]
I was just working through this exercise and noticed this too, the following is now a acceptable solution for example
```
fn main() -> Result<String, ParseIntError> {
    let mut tokens = 100;
    let pretend_user_input = "8";

    let cost = total_cost(pretend_user_input)?;

    if cost > tokens {
        Ok(format!("You can't afford that many!"))
    } else {
        tokens -= cost;
        Ok(format!("You now have {} tokens.", tokens))
    }
}
```

**Comment by rusty-snake** [comment]
maybe better:`fn main() -> Result<(), AnyErrorType>`

because `fn main() -> String` isn't allowed.

**Comment by EvanCarroll** [comment]
I'm not sure that this issue should be marked as completed. Previously the lesson was that you can use `?` only if you're returning a result, but if you want to panic on error and only concern yourself with success you can use the `.unwrap()`.

    let cost = total_cost(pretend_user_input)?; # old
    let cost = total_cost(pretend_user_input).unwrap(); #fixed

The hint says,

    If other functions can return a `Result`, why shouldn't `main`?

That's pushing the users to make `main` return a `Result`. The user is likely to look up "how do I make main return a result".
