### ISSUE TITLE
`iterator3.rs` doesn't appear to run tests at all

### ISSUE THREAD

**Issue by monuszko** [rust-lang/rustlings#187]
I initially encountered this issue when solving Rustlings 1.2.1. A test didn't seem to care if I handled zero division and not-even-division at all. I commented out my serious solution and left out only a lazy one to see if rustlings care. They do not. You can even change the numbers in asserts to something that shouldn't pass, and the exercise still passes.

I normally use `rustlings watch`, `rustlings verify`, and `rustlings run exercises/standard_library_types/iterator3.rs`. It makes no difference. But If I paste the code to playground, then the compiler complains!

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7c954a55e6c2d7f8c9713c1e37b5120c

----

Reproduction steps:
1. git clone rustlings
2. `git checkout tags/1.2.1`
3. Paste the code from the playground into `exercises/standard_library_types/iterator3.rs`
4. use `rustlings run exercises/standard_library_types/iterator3.rs`. You should see the exercise pass, which is disturbing.
5. `git checkout tags/1.3.0` and repeat steps 3,4 . It should still incorrectly pass.

I thought pulling more recent rustlings would do the trick because I found a closed/fixed issue with tests not running correctly, but alas the fix doesn't cover my case.

**Comment by monuszko** [comment]
Actually **there's even a simpler minimal example**. Make the body of `fn divide` consist of this single line:
`    Ok(a / b)`

You should see the exercise pass (the 4 tests that are initially uncommented), even though it obviously doesn't handle the division errors.

**Comment by fmoko** [comment]
Can't reproduce this on 1.5.0. @monuszko, are you still getting this bug?

**Comment by danwilhelm** [comment]
I also can't reproduce this in the latest master (3.0.0+). The linked playground code and the simpler minimal example both fail on `test_divide_by0` and `test_not_divisible`. 

I'm not sure how the minimal example `Ok(a / b)` could possibly pass those two tests, since each requires the return of a custom error type.

**Comment by monuszko** [comment]
The anomaly, whatever caused it, is no more. Tests catch it.

I retried it with:
rustlings 4.0.0
rustc 1.46.0 (04488afe3 2020-08-24)

**Comment by monuszko** [comment]
@fmoko I'm not getting the bug anymore.
