### ISSUE TITLE
Add Rustlings fast-track

### ISSUE THREAD

**Issue by jpedrick** [rust-lang/rustlings#1870]
I've been learning rust for a few months now, but I'm still benefitting from Rustlings as there are details covered that I haven't learned yet. I'm probably not the only one who found the cost/benefit (time/(learning/fun)) ratio a bit high(admittedly, I should have walked through rustlings a couple months ago.) I'm proposing an option to solve a single fast-track exercise that contains all the concepts for each chapter, potentially allowing users to switch back and forth within `rustings watch`. If a user finds the fast-track too daunting, they can switch back to the standard track and vice versa. When testing if the chapter is completed, first check the fast-track exercise and if it runs correctly, skip the rest of the chapter.

```
Welcome to watch mode! You can type 'help' to get an overview of the commands you can use here.
help
Commands available to you in watch mode:
  hint  - prints the current exercise's hint
  [fast-track/standard-track] - switch to fast-track exercises / switch to standard-track exercises
  clear - clears the screen
  quit  - quits watch mode
  help  - displays this help message

Watch mode automatically re-evaluates the current exercise
when you edit a file's contents.
```

**Comment by shadows-withal** [comment]
Interesting idea! I'll keep it in mind, I've been meaning to take another look at the progression some time.

**Comment by mo8it** [comment]
I think that the ability to skip exercises with the new list mode in version 6 is enough. Otherwise, a new set of exercises for advanced devs can be created with the new [support for third-party exercises](https://github.com/rust-lang/rustlings/blob/main/THIRD_PARTY_EXERCISES.md).
