### ISSUE TITLE
Idea - Migrate help issues to discussions in github

### ISSUE THREAD

**Issue by beastr45** [rust-lang/rustlings#1879]
In the readme for this project it is stated that users should be asking questions for support on their own rust journey in the issues section of this project. 
I think that due to  this reason the issues section is full of a ridiculous amount of issues unrelated to the actual implementation or bugs of the project. In this way the bugs dont get read and the help never gets answered.
Github has a feature in order to fix this called discussions which projects like lazy.nvim successfully integrate into their projects https://docs.github.com/en/discussions/quickstart I think that It would be beneficial to new learners and contributors alike to make a better system of issues

At the very least I think that it would be smart to add tags in order to separate actual bugs and issues from advice on the rust language itself. There should be tags for both separate bugs, feature requests or ideas and currently tagging or labeling is not required.

**Comment by shadows-withal** [comment]
Good idea, I haven't looked into Discussions, but those seem like the right place to funnel questions about how to solve exercises.

**Comment by mo8it** [comment]
"Discussions" seems to be activated for the repository now. I will convert help issues to discussions :)
