### ISSUE TITLE
rustlings watch hangs

### ISSUE THREAD

**Issue by ashokpappu** [rust-lang/rustlings#1880]
/ functions2.rs
//
// Execute `rustlings hint functions2` or use the `hint` watch subcommand for a
// hint.

// I AM NOT DONE

fn main() {
    call_me(300000000);
}

fn call_me(num:i32) {
    for i in 0..num {
        println!("Ring! Call number {}", i + 1);
    }
}
~                        

The above code will cause rustlings watch to hang

**Comment by shadows-withal** [comment]
This is most likely Rust hanging your thread because you're outputting trillions of lines to your terminal, I'd suggest not doing that :D

**Comment by ashokpappu** [comment]
This is an awesome tutorial I am loving it.  Thank you

Thank you,
Ashok Pappu
