### ISSUE TITLE
Maybe I'm the dummy -hashmaps3

### ISSUE THREAD

**Issue by pnhearer** [rust-lang/rustlings#1896]
I had to cheat and look at others solutions to understand why the test to England's score was 5. I honestly had thought the test was written incorrectly. Given the requirements at the head of the file
```
// You have to build a scores table containing the name of the team, goals the
// team scored, and goals the team conceded. One approach to build the scores
// table is to use a Hashmap. The solution is partially written to use a
// Hashmap, complete it to pass the test.

```

I had not derived that I needed to sum the scores of each team. Maybe this would have been more obvious to me had I been a sportsball enjoyer(I'm not) but here we are.

```
Had the statement been 
// You have to build a scores table containing the name of the team, 
// total goals the team scored, and total goals the team conceded. 
```

I would have arrived at a sensible conclusion. Now that I understand the requirement is to present cumulative values I can rather unhappily go back and solve this problem that I've seen the answer to 😞 .

Anywho, maybe it's just me being the dumb dumb.

**Comment by shadows-withal** [comment]
This should be fixed on main due to https://github.com/rust-lang/rustlings/pull/1869, and will be included in the next release!

**Comment by pnhearer** [comment]
Yep! That'll do ti! That's great.
