### ISSUE TITLE
enums3 has an argument in the testing that does not compile

### ISSUE THREAD

**Issue by LuckyLuc96** [rust-lang/rustlings#1900]
I am getting an error on compile when I am sure I have the solution, since I took that solution off the internet!

I believe that the line in testing should say:

> state.process(Message::Move{ x: 10, y: 15 });

But currently it says:

> state.process(Message::Move(Point{ x: 10, y: 15 }));

The compile error when the latter is ran is:

  --> exercises/enums/enums3.rs:76:23
   |
76 |         state.process(Message::Move(Point{ x: 10, y: 15 }));
   |                       ^^^^^^^^^^^^^ not a value

error: aborting due to previous error

**Comment by shadows-withal** [comment]
For reference, could you post your solution?

**Comment by LuckyLuc96** [comment]
> For reference, could you post your solution?

Definitely. I know the solution could just simply be incorrect and my changing of the test was a huge mistake. But I am fairly sure that the solution here is right and the test had an error.


_____________


enum Message {
    // TODO: implement the message variant types based on their usage below
    Move{x: u8, y: u8},
    ChangeColor(u8, u8, u8),
    Echo(String),
    Quit,
}

struct Point {
    x: u8,
    y: u8,
}

struct State {
    color: (u8, u8, u8),
    position: Point,
    quit: bool,
    message: String,
}

impl State {
    fn change_color(&mut self, color: (u8, u8, u8)) {
        self.color = color;
    }

    fn quit(&mut self) {
        self.quit = true;
    }

    fn echo(&mut self, s: String) {
        self.message = s
    }

    fn move_position(&mut self, p: Point) {
        self.position = p;
    }

    fn process(&mut self, message: Message) {
        // TODO: create a match expression to process the different message
        // variants
        // Remember: When passing a tuple as a function argument, you'll need
        // extra parentheses: fn function((t, u, p, l, e))
        match message{
        Message::Quit => self.quit(),
        Message::Move{x, y} => self.move_position(Point{x, y}),
        Message::ChangeColor(r, g, b) => self.change_color((r, g, b)),
        Message::Echo(s) => self.echo(s),}
        
        
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_match_message_call() {
        let mut state = State {
            quit: false,
            position: Point { x: 0, y: 0 },
            color: (0, 0, 0),
            message: "hello world".to_string(),
        };
        state.process(Message::ChangeColor(255, 0, 255));
        state.process(Message::Echo(String::from("Hello world!")));
        state.process(Message::Move{ x: 10, y: 15 });
        state.process(Message::Quit);

        assert_eq!(state.color, (255, 0, 255));
        assert_eq!(state.position.x, 10);
        assert_eq!(state.position.y, 15);
        assert_eq!(state.quit, true);
        assert_eq!(state.message, "Hello world!");
    }
}

**Comment by LuckyLuc96** [comment]
I'm gonna close with the assumption that I did something wrong. I am still new to this and my assumption that the test was wrong is kind of presumptuous.
