### ISSUE TITLE
Self-contained installation

### ISSUE THREAD

**Issue by mo8it** [rust-lang/rustlings#1919]
I was thinking about the possibility of installing Rustlings without the installation scripts that are piped into a shell. Wouldn't it be nice if we could just offer `cargo install rustlings`?

# Why?

- No piping of a script from the internet into a shell. This is often perceived as a security threat. Yes, the script is tiny and can be read, but avoiding it altogether would not scare anyone off.
- No requirement on git
- No requirement on Python
- No shell scripts to maintain
- One installation method for all platforms (currently, there is a separate script for Windows)
- Less to download (no cloning of the whole repository)
- No need to look for the latest git tag during installation
- Make beginners familiar with `cargo install`
- Reduce the confusion with files not related to the exercises (I observed this during my course).
- Reduce the countless PRs of people submitting their solutions by mistake.

# How?

My suggestion is to include the exercises in the binary using something like [`include_bytes!`](https://doc.rust-lang.org/stable/std/macro.include_bytes.html) on the whole `exercises` directory. Then, the directory is extracted to the filesystem on first run. Something similar to [this](https://docs.rs/include_dir/latest/include_dir/struct.Dir.html#method.extract). This initialization would also automatically generate the `rust-project.json` file for Rust-Analyzer. So the `lsp` command would be eliminated and users don't forget to run it.

Many of the students in my course forgot to run the `lsp` command and got no language server support until I noticed it.

# Changes

Resetting an exercise would not be done using `git stash push -- EXERCISE` anymore. The exercise would be completely nuked and replaced by the original file in the binary.

# crates.io

Currently, [`rustlings` is taken on crates.io](https://crates.io/crates/rustlings)… But we can try to contact the author.

---

@shadows-withal what do you think? I would take care of the implementation. That would be version 6.0

**Comment by mo8it** [comment]
I found another positive effect in case we go in this direction: https://github.com/rust-lang/rustlings/issues/293#issuecomment-2023953936

**Comment by mo8it** [comment]
Done in the `v6` branch :D

**Comment by jsejcksn** [comment]
> Reduce the countless PRs of people submitting their solutions by mistake

🥲

**Comment by jsejcksn** [comment]
@mo8it Just curious: is there an available estimation on when you might publish the initial v6 to https://crates.io/crates/rustlings? It looks like some additional [feature ideas](https://github.com/rust-lang/rustlings/issues?q=is%3Aopen+is%3Aissue+milestone%3Av6) have been added to that milestone [`v6`](https://github.com/rust-lang/rustlings/milestone/1) since I last checked.

**Comment by mo8it** [comment]
Hi @jsejcksn, thanks for your interest 🥰
My estimate for releasing a stable version 6 is about 2 weeks.

I should finish development at the end of this week. Then, I will publish a beta version and invite people to test it for about a week because I did almost a complete rewrite of the Rustlings program (not the exercises) and some bugs might exist. While people are testing, I will start working on the exercise solutions that will also be part of version 6.

If you are interested in the progress so far, check out my writing from today on Zulip 😃 https://rust-lang.zulipchat.com/#narrow/stream/334454-rustlings/topic/v6/near/432731528
