### ISSUE TITLE
Improved `move_semantics4` exercise proposal

### ISSUE THREAD

**Issue by Cai1Hsu** [rust-lang/rustlings#1947]
Current:
https://github.com/rust-lang/rustlings/blob/258ff6f462880aa866d6d9d269ae4e2070db6a17/exercises/06_move_semantics/move_semantics4.rs#L12-L29

Proposed Change:
```Rust
#[test]
fn main() {
    // No changes should be made in the main function
    let vec1 = fill_vec();

    assert_eq!(vec1, vec![22, 44, 66, 88]);
}

// `fill_vec()` no longer takes `vec: Vec<i32>` as argument
fn fill_vec() -> ??? {
    // Instead, let's create and fill the Vec in here - how do you do that?
    let mut vec = ???

    vec.push(88);

    vec
}
```
The purpose of this exercise, as I understand it, is to help users grasp the concept of ownership and how values can be returned with ownership transferred back to the caller.

1. Removed the declaration and usage of `vec0` as it doesn't serve any purpose in this exercise. When I was solving this exercise, I thought I had to do something with it but at last, I found I had to remove it.
2. Refactored the declaration of `vec` in `fill_vec` to guide learners towards what they should modify.
3. Ask the user to determine the return type of `fill_vec` to help learners understand that they should return a value with ownership instead of a reference.
4. Added a comment in `main` to instruct learners not to change the `main` function, allowing them to focus on modifying `fill_vec`.

This proposal might still have some imperfections so I opened this issue. Feel free to share your ideas.

**Comment by mo8it** [comment]
Yeah, the exercise is a bit weird. I removed it in the upcoming version 6, especially because of the change in `vecs2` where you see how to create a `Vec`, push to it and return it.
