### ISSUE TITLE
Installing rustlings fails on WSL 

### ISSUE THREAD

**Issue by omarq** [rust-lang/rustlings#195]
I'm trying to install rustlings on WSL Ubuntu Windows 10 but when I follow the tutorial I got the following error 
error: unknown start of token: \u{0}
 --> /home/oqadan/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.5.6/src/unicode_tables/property_names.rs:1:1
  |
1 |
  | ^

error: aborting due to previous error

error: Could not compile `regex-syntax`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rustlings v1.4.0 (/mnt/c/Projects/rustlings)`, intermediate artifacts can be found at `/mnt/c/Projects/rustlings/target`

I noticed that there is an issue with compiling regex-syntax-0.5.6 and I noticed that cargo.lock is referencing 2 versions for that same library it also referencing regex-syntax-0.6.6 so I removed the references to the olde version and run 

cargo install --force --path .

but I still get the same error again 

rustc 1.36.0
rustling 1.4.0

**Comment by komaeda** [comment]
This might be a bug in `regex-syntax`, then?

**Comment by rusty-snake** [comment]
> I noticed that cargo.lock is referencing 2 versions for that same library

You should not edit `Cargo.lock` use always the version generated by cargo (cargo will overriede it anyway), to update the depencies try run `cargo update`.

**Comment by omarq** [comment]
@rusty-snake I tried update but it failed because of some error so I did this based on google search 
`rm -rf ~/.cargo/registry`
then 
`cargo update`
and it builds the registry again 
then 
`cargo install --force --path .` 
worked fine 
thank you for your help
