### ISSUE TITLE
Instructions on 'Doing exercises' named wrong. 

### ISSUE THREAD

**Issue by starch0** [rust-lang/rustlings#1977]
In the third step of the 'Doing Exercises' category, the exercise is named `myExercise1` where it is in the real intro1 and others. In fact, there is no `myExercise1`.

![image](https://github.com/rust-lang/rustlings/assets/152428867/62f07fbc-668a-45d3-8bec-0225422bb4c2)

Im i able to change that? How should i proceed? 
```[tasklist]
### Tasks
```

**Comment by mo8it** [comment]
Thanks for reporting this confusion. Closing because this is not relevant in the [upcoming version 6](https://github.com/rust-lang/rustlings/tree/v6)
