### ISSUE TITLE
[question] how to add repo as submodule?

### ISSUE THREAD

**Issue by yozachar** [rust-lang/rustlings#1989]
Hi,

I'm practicing `Rust`, I hope to practice other languages too. So I created https://github.com/yozachar/practice, add tried to add `rustlings` as a git submodule. But I'm facing some trouble.

1. When I do `git submodule add -b 5.6.1 --depth 1 gh:rust-lang/rustlings`, I see
    ```console
    fatal: 'origin/5.6.1' is not a commit and a branch '5.6.1' cannot be created from it
    fatal: unable to checkout submodule 'rustlings'
    ```
    I guess that's because no such branch exists on this repository.
2. So I did
    ```console
    $ git submodule add gh:rust-lang/rustlings
    $ cd rustlings
    $ git checkout 5.6.1
    $ cargo install --locked --force --path .
    $ cd ..
    $ git add rustlings
    $ git commit && git push
    ``` 
    but I get a 404: https://github.com/yozachar/practice/blob/main/rustlings.

Why? How can I see my rustling progress on that GitHub repository as a submodule?

**Comment by mo8it** [comment]
As far as I can see in your repo, you were able to do it :)

**Comment by yozachar** [comment]
Not exactly no. Sub-modules didn't work the way I thought it would, if I add commits, it does not reflect on GitHub, cause I can't push them here (to `rustlings` repo).

Anyway I ended up adding rustlings clone as a whole folder.
