### ISSUE TITLE
standard_library_types/iterators2.rs, wrong ::?

### ISSUE THREAD

**Issue by lromor** [rust-lang/rustlings#199]
Hi, 

I'm new to rust, but I couldn't really find a solution to this [line](https://github.com/rust-lang/rustlings/blob/master/exercises/standard_library_types/iterators2.rs#L12)

Could the `collect()` round brackets be a typo and the original code should be instead:
```
.collect::<String>() + c.as_str()
```

If it's not the case, could you provide a hint on how to solve the exercise with `.collect()::<String>()`?

Thank you,

-l

**Comment by nkanderson** [comment]
+1, I got hung up on this one for a bit as well. The resulting error message is a bit confusing, in my opinion, for those of us new to the syntax.

I would support either removing `()` after `collect` as suggested above, or removing the `::<String>()` type annotation and guiding the user through the addition of a turbofish annotation.
