### ISSUE TITLE
threads3 produces no output

### ISSUE THREAD

**Issue by JCTschechne** [rust-lang/rustlings#1991]
Exercise "threads3" doesn't produce any output.

### System Info

Pop!_OS 22.04 LTS

rustc 1.78.0 (9b00956e5 2024-04-29)

rustlings 5.6.1

total 36536
drwxrwxr-x 10 jojo jojo    4096 Jun 10 15:36 .
drwxr-x--- 35 jojo jojo    4096 Jun 10 15:36 ..
-rw-rw-r--  1 jojo jojo   65324 Jun  3 12:12 .all-contributorsrc
-rw-rw-r--  1 jojo jojo   86292 Jun  3 12:12 AUTHORS.md
-rw-rw-r--  1 jojo jojo   25693 Jun  3 12:12 Cargo.lock
-rw-rw-r--  1 jojo jojo     629 Jun  3 12:12 Cargo.toml
-rw-rw-r--  1 jojo jojo   48488 Jun  3 12:12 CHANGELOG.md
-rw-rw-r--  1 jojo jojo    4171 Jun  3 12:12 CONTRIBUTING.md
drwxrwxr-x  2 jojo jojo    4096 Jun  3 12:12 .devcontainer
-rw-rw-r--  1 jojo jojo     102 Jun  3 12:12 .editorconfig
-rw-rw-r--  1 jojo jojo      74 Jun  3 12:12 .envrc
drwxrwxr-x 26 jojo jojo    4096 Jun  3 12:12 exercises
-rw-rw-r--  1 jojo jojo    1984 Jun  3 12:12 flake.lock
-rw-rw-r--  1 jojo jojo    2338 Jun  3 12:12 flake.nix
drwxrwxr-x  8 jojo jojo    4096 Jun  3 12:12 .git
drwxrwxr-x  3 jojo jojo    4096 Jun  3 12:12 .github
-rw-rw-r--  1 jojo jojo     216 Jun  3 12:12 .gitignore
-rw-rw-r--  1 jojo jojo     162 Jun  3 12:12 .gitpod.yml
-rw-rw-r--  1 jojo jojo   42573 Jun 10 15:31 info.toml
-rw-rw-r--  1 jojo jojo    3045 Jun  3 12:12 install.ps1
-rwxrwxr-x  1 jojo jojo    4662 Jun  3 12:12 install.sh
-rw-rw-r--  1 jojo jojo    1095 Jun  3 12:12 LICENSE
-rw-rw-r--  1 jojo jojo      59 Jun  3 12:12 .markdownlint.yml
-rw-rw-r--  1 jojo jojo     750 Jun  3 12:12 oranda.json
-rw-rw-r--  1 jojo jojo    6349 Jun  3 12:12 README.md
-rw-rw-r--  1 jojo jojo     278 Jun  3 12:12 shell.nix
drwxrwxr-x  2 jojo jojo    4096 Jun  3 12:12 src
drwxrwxr-x  3 jojo jojo    4096 Jun  3 12:12 target
-rwxrwxr-x  1 jojo jojo 6169080 Jun 10 00:20 temp_22662_ThreadId1
-rwxrwxr-x  1 jojo jojo 6168464 Jun 10 00:29 temp_24597_ThreadId1
-rwxrwxr-x  1 jojo jojo 6168280 Jun 10 00:31 temp_25962_ThreadId1
-rwxrwxr-x  1 jojo jojo 6168280 Jun 10 00:33 temp_27069_ThreadId1
-rwxrwxr-x  1 jojo jojo 6168280 Jun 10 00:34 temp_27189_ThreadId1
-rwxrwxr-x  1 jojo jojo 6169080 Jun 10 00:18 temp_6819_ThreadId1
drwxrwxr-x  3 jojo jojo    4096 Jun  3 12:12 tests
drwxrwxr-x  2 jojo jojo    4096 Jun  3 12:12 .vscode

**Comment by mo8it** [comment]
I can't reproduce it. Could you please try again with the new version 6? If you still have the issue, please post your exercise code :)
