### ISSUE TITLE
Progress bar logs into new lines?

### ISSUE THREAD

**Issue by shogunsea** [rust-lang/rustlings#1992]
<img width="913" alt="image" src="https://github.com/rust-lang/rustlings/assets/2238944/be3342a9-3732-49ae-8b10-425306b7f4f3">
It wasn't like this before, not sure if it's some dependency upgrades caused the progress bar to log to new lines

**Comment by mo8it** [comment]
This is very annoying, but it is fixed in the upcoming version 6 :D
