### ISSUE TITLE
Installing issues with cargo 

### ISSUE THREAD

**Issue by bek-shoyatbek** [rust-lang/rustlings#1993]
I'm trying to install rustlings but couldn't pass 
"cargo install --force --path ." step 

and rustling command is not working

![image](https://github.com/rust-lang/rustlings/assets/92543629/1dbde139-d5ff-4d4d-9b93-1b6c0c106fc3)

![image](https://github.com/rust-lang/rustlings/assets/92543629/05d60e66-55a0-49a7-ba45-649a453c2e4c)

**Comment by mo8it** [comment]
It looks like a linker problem. How did you install Rust? Could you also share the version that you have installed?

**Comment by bek-shoyatbek** [comment]
I downloaded latest version .exe file from official website and just installed it in windows 10

**Comment by evanmiller2112** [comment]
I have a few thoughts:

The actual error appears to be: `note: ld: cannot find -lktmw32: No such file or directory`

- Have you intentionally placed rustlings within your C:\Windows\system32 directory? That doesn't seem like the right location for a userspace application. I wonder if that could have an impact?
- Have you tried installing using the Powershell script provided [here?](https://raw.githubusercontent.com/rust-lang/rustlings/main/install.ps1) - it may help.
- There are two commands listed in the README for manual install. One is what you've used, and one is slightly different. Maybe try this one? The difference is the "--locked" runtime param. `cargo install --locked --force --path .`

**Comment by mo8it** [comment]
Can you also please try compiling a hello-world program to make sure that it is rather not an installation issue? You can do so by running the following:

```
cargo new hello-world
cd hello-world
cargo run
```
