### ISSUE TITLE
Failed to write Clippy Cargo.toml file: Path Not Found Error

### ISSUE THREAD

**Issue by erickcestari** [rust-lang/rustlings#1998]
**Steps to Reproduce**:
1. Run `rustlings run clippy1`.
2. Encounter the error message `Failed to write 📎 Clippy 📎 Cargo.toml file: Os { code: 3, kind: NotFound, message: "O sistema não pode encontrar o caminho especificado." }`.

**Expected Behavior**:
- Expected the Clippy exercise `clippy1.rs` to compile and run without errors related to writing the Clippy configuration file.

**Actual Behavior**:
- Received an error stating "Path Not Found" when attempting to write the Clippy Cargo.toml file.

**Environment**:
- Operating System: Windows 10
- Rustlings Version: rustlings 5.6.1
- Rust Version: rustc 1.77.0 (aedd173a2 2024-03-17)
- Clippy Version: clippy 0.1.77 (aedd173a 2024-03-17)

**Comment by erickcestari** [comment]
More context: I did the windows installation instead of the manual

**Comment by erickcestari** [comment]
Manually installing it resolved the issue in my case.

**Comment by mo8it** [comment]
Closing because it is a known issue that is resolved in the upcoming version 6 :)
Happy that it is resolved for you for now.
