### ISSUE TITLE
Rust Analyzer not working in /exercises/*.rs

### ISSUE THREAD

**Issue by matormentor** [rust-lang/rustlings#2001]
Issue with file not included in crate hieriarchy for all exercies.

**Comment by matormentor** [comment]
Nevermind, just missed the rust-project.json generation. 
For anyone with the same issue, just use `rustlings lsp` and restart the rust-analyzer.

**Comment by resthedev** [comment]
> Nevermind, just missed the rust-project.json generation. For anyone with the same issue, just use `rustlings lsp` and restart the rust-analyzer.

Thanks for providing the solution. I was confused I was not getting any auto complete nor definitions.

**Comment by mo8it** [comment]
Note that this is not needed in the new release of version 6 :)

**Comment by wrnlb666** [comment]
I got 
`This file is not included in any crates, so rust-analyzer can't offer IDE services. If you're intentionally working on unowned files, you can silence this warning by adding "unlinked-file" to rust-analyzer.diagnostics.disabled in your settings.`
from version 6.3.0, is it what I suppose to get? Or what should I do to fix this?
