### ISSUE TITLE
intro1: removing last semicolon does nothing

### ISSUE THREAD

**Issue by paulotten** [rust-lang/rustlings#2013]
intro1.rs suggests `Try removing a semicolon and see what happens in the terminal!` The two most likely semicolons for the learner to remove are probably the first one or the last one.

If you remove the last semicolon though nothing changes. `println!("new println")` gets turning into an implicit return statement. Since `println!` returns the unit type `()` and `main` also (implicitly) returns `()` there's no error. The learner shouldn't learn about this until functions5.rs though.

This is relatively high visibility since it's the first exercise. It can give the impression that rustlings code watch functionality isn't working.

**Comment by paulotten** [comment]
For fixing this, maybe we should add a return to `fn main`.  The most minimal change would probably adding a `()` line at the end of the function.

**Comment by mo8it** [comment]
Thanks! Fixed in https://github.com/rust-lang/rustlings/commit/b8826dd3b31661927ad66d1bae2fd49f63e8d812
