### ISSUE TITLE
errors2: Incorrect problem statement?

### ISSUE THREAD

**Issue by cshimmin** [rust-lang/rustlings#2014]
In errors2.rs, the problem statement claims "Right now, this function ... isn't handling the success case properly either", but as far as I can tell, the success case is properly implemented; only the error case needs to be modified.

This was also mentioned by @dotjpg3141 in #1960, but perhaps was overlooked due to all the feedback received there!

**Comment by mo8it** [comment]
Thanks! Fixed in https://github.com/rust-lang/rustlings/commit/d54c05098516f2e8e5958f0b26478c85ebccb67d

**Comment by mo8it** [comment]
@dotjpg3141 I didn't overlook your feedback. But I wanted to release as soon as possible because some people started to get problems with the old version. So I decided to take care of the feedback about the exercises later. Everything should be fixed now. Thank you both again :D
