### ISSUE TITLE
Rustlings v6.0.1 no longer respects NO_EMOJI

### ISSUE THREAD

**Issue by eliminmax** [rust-lang/rustlings#2020]
The new version of rustlings shows emoji even when the NO_EMOJI environment variable is set to a non-empty value.
Specifically, the crab emoji appears in the 'when you are done experimenting...' message whether or not it's set.

**Comment by mo8it** [comment]
Could you please explain why not having emojies is important?

**Comment by eliminmax** [comment]
I don't mind them, but I know that #364 argued that excessive use of Emoji and color is an accessibility issue, leading to the support for the `NO_EMOJI` environment variable being merged in #676, so I figured I'd open an issue.

There was an issue I ran into with the interaction between the byobu wrapper around tmux and rustlings 5.6.1 that caused text to overwrite the dividing line between tmux panes on lines that had emoji and text longer than the terminal pane width, but I think the bug there is almost certainly not in rustlings. The use of emoji in v6.0.1 does not appear to cause the same bug, and that bug was the only reason I added NO_EMOJI to my `.profile` as a lazy workaround.

**Comment by mo8it** [comment]
Yes, but version 6 uses less emojis than before. So I don't think that the usage is excessive.

I am closing the issue, but if people still see this as a problem, I can remove that crab emoji. I prefer removing emojis over the overhead of supporting `NO_EMOJI`.

**Comment by eliminmax** [comment]
That's an understandable decision. Thanks for explaining.

Not sure about switching to zellij just yet, but I've heard good things about it.
