### ISSUE TITLE
Dead link on home page for "third-party exercises"

### ISSUE THREAD

**Issue by pReya** [rust-lang/rustlings#2028]
On the home page `http://rustlings.cool`, the link to third-party exercises isn't working. The exact link is https://rustlings.cool/THIRD_PARTY_EXERCISES.md. I'd love to contribute a fix, but I'm not sure what the intended behavior is. Is there a slug for a fully rendered mdBook page? Or is the link supposed to lead to the file in a GitHub edit view?

**Comment by mo8it** [comment]
Fixed in https://github.com/rust-lang/rustlings/commit/9b5b652c71bf5f921657b610435b785520857bf3
