### ISSUE TITLE
Most hints are visibile on opening a file even on 1080p screens.

### ISSUE THREAD

**Issue by dustypaws** [rust-lang/rustlings#203]
So maybe it would be nice if you could put them further down!? Just a minor improvement. :)

![2019-07-30_13-08-45](https://user-images.githubusercontent.com/19664015/62124894-be296580-b2cb-11e9-8d4b-fa0a53d8fb23.png)

**Comment by AlexAegis** [comment]
If you use an autoformatter on the first save the hint will jump right up. I think it would be better to just have them in separate markdown files. For example: strings1_hint.md
