### ISSUE TITLE
Is it possible to give a correct answer

### ISSUE THREAD

**Issue by sunheyi6** [rust-lang/rustlings#2044]
I found that I really don’t know how to solve some questions. I think it would be better if there were correct answers

**Comment by sibkru** [comment]
Solutions can be found here: 
https://github.com/rust-lang/rustlings/tree/main/solutions

**Comment by sunheyi6** [comment]
ok， thank you

**Comment by mo8it** [comment]
A solution is saved to disk after solving an exercise so that you can compare to your solution. I don't recommend looking at them before solving an exercise. Instead, you can ask for hints by entering `h` in Rustlings.
