### ISSUE TITLE
rustlings command not found

### ISSUE THREAD

**Issue by rudy-in** [rust-lang/rustlings#2047]
i followed the docs and when i tried to run `rustlings init` it said rustlings: command not found

**Comment by mo8it** [comment]
Probably the same issue here: https://github.com/rust-lang/rustlings/issues/2046

You are probably using Linux and `~/.cargo/bin` is not in your `PATH` environment variable.

The easiest way to fix this is to uninstall Rust from your package manager and install it using rustup with the official way: https://www.rust-lang.org/tools/install
