### ISSUE TITLE
Exercise file links won't open in WSL

### ISSUE THREAD

**Issue by krishvishal** [rust-lang/rustlings#2048]
Exercise file links displayed in the terminal wont open upon clicking.

This is the link that I see: `file:///home/kv/projects/rustlings/exercises/03_if/if2.rs h`

Env:

WSL: 2.0
Ubuntu: 20.04
VSCode: 1.90.1

**Comment by mo8it** [comment]
They work on both Linux and Windows. So this has to be a WSL issue. There is nothing Rustings can do about it.

It is possible that VS Code can deal with this. Try using the terminal in VS Code.
