### ISSUE TITLE
as_ref_mut.rs weird error using provided solution

### ISSUE THREAD

**Issue by DaQue** [rust-lang/rustlings#2051]
I copied the solution and pasted it over my solution because I kept getting an odd error and I still get this error: 

error[E0277]: cannot divide `f64` by `usize`
 --> exercises/23_conversions/using_as.rs:8:11
  |
8 |     total / values.len()
  |           ^ no implementation for `f64 / usize`
  |
  = help: the trait `Div<usize>` is not implemented for `f64`
  = help: the following other types implement trait `Div<Rhs>`:
            <f64 as Div>
            <f64 as Div<&f64>>
            <&'a f64 as Div<f64>>
            <&f64 as Div<&f64>>

For more information about this error, try `rustc --explain E0277`.
error: could not compile `exercises` (bin "using_as") due to 1 previous error

It doesn't even match line 8 which is just "}".

**Comment by mo8it** [comment]
The feedback that you get is about the exercise `as_ref_mut` but about `using_as` (shown in the path `exercises/23_conversions/using_as.rs:8:11` and at the end `bin "using_as"`).
