### ISSUE TITLE
issue reinstalling rustlings v6.0.1 -> 6.1.0

### ISSUE THREAD

**Issue by DaQue** [rust-lang/rustlings#2058]
Please include some detail of how to reinstall rustlings so newbies like `me` can complete it again.

I have tried
Removing the rustlings directory and running cargo install rustlings, cargo install rustlings --force, cargo install rustlings --locked.

I have also tried cargo remove rustlings uninstall rustlings and al the above.

No matter what I try the rustlings director is not created in the current directory.

C:\Users\david> cargo --list
Installed Commands:
    add                  Add dependencies to a Cargo.toml manifest file
    b                    alias: build
    bench                Execute all benchmarks of a local package
    build                Compile a local package and all of its dependencies
    c                    alias: check
    check                Check a local package and all of its dependencies for errors
    clean                Remove artifacts that cargo has generated in the past
    clippy               Checks a package to catch common mistakes and improve your Rust code.
    config               Inspect configuration values
    cov
    d                    alias: doc
    doc                  Build a package's documentation
    fetch                Fetch dependencies of a package from the network
    fix                  Automatically fix lint warnings reported by rustc
    fmt                  Formats all bin and lib files of the current crate using rustfmt.
    generate
    generate-lockfile    Generate the lockfile for a package
    git-checkout         This command has been removed
    help                 Displays help for a cargo subcommand
    init                 Create a new cargo package in an existing directory
    install              Install a Rust binary
    locate-project       Print a JSON representation of a Cargo.toml file's location
    login                Log in to a registry.
    logout               Remove an API token from the registry locally
    metadata             Output the resolved dependencies of a package, the concrete used versions including overrides, in machine-readable format
    miri
    new                  Create a new cargo package at <path>
    nm
    objcopy
    objdump
    owner                Manage the owners of a crate on the registry
    package              Assemble the local package into a distributable tarball
    pkgid                Print a fully qualified package specification
    profdata
    publish              Upload a package to the registry
    r                    alias: run
    read-manifest        Print a JSON representation of a Cargo.toml manifest.
    readobj
    remove               Remove dependencies from a Cargo.toml manifest file
    report               Generate and display various kinds of reports
    rm                   alias: remove
    run                  Run a binary or example of the local package
    rustc                Compile a package, and pass extra options to the compiler
    rustdoc              Build a package's documentation, using specified custom flags.
    search               Search packages in the registry. Default registry is crates.io
    size
    strip
    t                    alias: test
    test                 Execute all unit and integration tests and build examples of a local package
    tree                 Display a tree visualization of a dependency graph
    uninstall            Remove a Rust binary
    update               Update dependencies as recorded in the local lock file
    vendor               Vendor all dependencies for a project locally
    verify-project       Check correctness of crate manifest
    version              Show version information
    yank                 Remove a pushed crate from the index

**Comment by mo8it** [comment]
Running `cargo install rustlings` again installs the latest version. Then you need to initialize a new directory by running `rustlings init`.

But Rustlings is thought to be installed once without needing to update it. Also note that version `6.1` doesn't have any new exercises. It only contains some improvements. So it is not worth it to redo Rustlings with the new version unless you want to start over.
