### ISSUE TITLE
No "init" option for rustlings

### ISSUE THREAD

**Issue by Mugworth** [rust-lang/rustlings#2059]
As in the title when i run `rustlings init`  it outputs:

```
Unrecognized argument: init

Run rustlings --help for more information.
```
cargo and rustc version is 1.80

**Comment by mo8it** [comment]
You must have an old version of Rustlings (<6.0).

Please follow the instructions in the README to install Rustlings again. If you still have this issue, share the output of `rustlings --version`

**Comment by Mugworth** [comment]
My bad i had 2 rustlings packages installed on system, one of which was, as you said, under 6.0 version, Thanks!
