### ISSUE TITLE
Option to show solution after completing an exercise.

### ISSUE THREAD

**Issue by KotUW** [rust-lang/rustlings#2064]
Is it OK, to add an option to show solution after completing an exercise.
I will be interested in implementing it. If acceptable.

**Comment by mo8it** [comment]
You mean show it in the terminal instead of just showing the path as a link?

I am not sure if I like that option, especially because of long files. Maybe in a pager?

**Comment by KotUW** [comment]
Pager works

**Comment by mo8it** [comment]
I considered this feature, but unfortunately, it would mean adding a huge library like [syntect](https://github.com/trishume/syntect) for syntax highlighting. It also hides the advantages of having a language server for reading the docs of used items in the solution. "Go to definition" is also very useful if someone wants to take a deeper look at how an std function works.

That being said, I tried to highlight the solution in https://github.com/rust-lang/rustlings/commit/e7ba88f90594962795bd028a8537efd6b1eedf6e. Note that the shown path to the solution file is a terminal link. So you can click on it to open the solution file in your favorite editor :)
