### ISSUE TITLE
Rustlings couldn't install

### ISSUE THREAD

**Issue by muthanii** [rust-lang/rustlings#2067]
I have a WSL launched on Microsoft Terminal running Ubuntu distro. I have installed `gcc`, `rustup` and `cargo` from `apt`, `snap` and `apt` respectively. I have tried to use the `--locked` flag. I also restarted my terminal and it still doesn't work and the following error is thrown everytime I run `cargo install rustlings --locked`. Would love to get started with rustlings ASAP.

![image](https://github.com/user-attachments/assets/9f5a47f0-77d7-4c05-8065-d697ebca45ff)

**Comment by mo8it** [comment]
The repositories have an old version. Rustlings requires the latest Rust version. Please uninstall cargo, rustc and rustup that you installed with apt and install Rust using the official method:

https://www.rust-lang.org/tools/install
