### ISSUE TITLE
rustlings init in a workspace

### ISSUE THREAD

**Issue by senekor** [rust-lang/rustlings#2073]
I would like to have rustlings part of several kinds of exercises during a workshop. So I'd like to provide students with a template repository they can clone. Is it feasible to have the rustlings exercises as part of a workspace? As of right now, rustlings seems to refuse initializing in a workspace. Well, it just says there is a `Cargo.toml`. It makes sense that rustlings shouldn't be within another package. But a workspace should be fine, right?

If so, I could try to extend `rustlings` such that it doesn't refuse initialization in a workspace.

**Comment by senekor** [comment]
I found the [relevant line](https://github.com/rust-lang/rustlings/blob/fd97470f3551e5c068dc796f25320ebb5b93a08c/src/init.rs#L16) in the source code. Maybe it could be specified what these problems are? I know that the workspace will need to contain `"rustlings"` in the `members` key. I think that should be achievable though.

**Comment by mo8it** [comment]
Fixed in https://github.com/rust-lang/rustlings/commit/8df66f79918168617da9709c0edcfeb3ca0e53c8

**Comment by senekor** [comment]
Thanks!
