### ISSUE TITLE
If3 -> Quiz1 skip

### ISSUE THREAD

**Issue by kony-ogony** [rust-lang/rustlings#2080]
I have just started doing rust and have encountered this issue in rustling. As soon as I complete if3 and type "n" it skips over everything straught to quiz1. Any help would be appreciated.

https://github.com/user-attachments/assets/967a0e5e-7261-4a81-9515-99114d49f6ab

**Comment by mo8it** [comment]
This is intended. You can press `l` to open the list mode and see the defined order.
