### ISSUE TITLE
rustlings command isn't running anymore.

### ISSUE THREAD

**Issue by o-jeddd-o** [rust-lang/rustlings#2087]
installed the new one using the readme, followed the exact instructions and it keeps giving me the same error message: 
Error: You are trying to run Rustlings using the old method before version 6.
The new method doesn't include cloning the Rustlings' repository.
Please follow the instructions in `README.md`:
https://github.com/rust-lang/rustlings#getting-started

but the readme is saying to run the exact line of code: rustlings.

**Comment by o-jeddd-o** [comment]
found the error.

**Comment by santhosh77h** [comment]
what is the error @o-jeddd-o ?

**Comment by o-jeddd-o** [comment]
yeah, so i forgot to add manually to path, did that and it all worked out.

**Comment by mo8it** [comment]
The problem is also that you cloned the repository. You shouldn't do that starting with version 6.
