### ISSUE TITLE
`rustlings` command throws an error after first run

### ISSUE THREAD

**Issue by colinfwalsh** [rust-lang/rustlings#2088]
I wanted to report this just in case this was a simple oversight and I didn't see any similar open issues.  Feel free to close if this is obvious but I figure it should be reported as a bug for those new to Rust and Cargo.

`rustlings` will successfully execute after running `rustlings init` but will fail after quitting.  The error thrown is the following:

```
error: failed to parse manifest at `/Users/colinwalsh/code/rustlings/Cargo.toml`

Caused by:
  missing field `version`
  in `package`
Error: The command `cargo metadata …` failed. Are you in the `rustlings/` directory?
```

Simply adding a `version="1.0.0"` to the Cargo.toml file will fix the issue.

**Comment by mo8it** [comment]
This is weird. I can't reproduce it with stable, beta or nightly. The documentation of the manifest also says that `version` is optional and defaults to `0.0.0`.

I can just add the version. But I am interested in when this happens. Can you please post the output of `cargo --version` in your `rustlings/` directory?

Maybe @epage could help? :)

**Comment by epage** [comment]
Looking at https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-version-field

> MSRV: Before 1.75, this field was required

**Comment by epage** [comment]
That is only in the nightly version of the documentation.  Eventually it will hit stable.
