### ISSUE TITLE
Unable to install from the source code in version 6.x

### ISSUE THREAD

**Issue by Platohykj** [rust-lang/rustlings#2090]
Clone the source code down at version 5.x and it works fine, and when I upgrade to version 6.x, the output is as follows

```gitpod /workspace/rustlings (main) $ rustlings init
Error: You are trying to run Rustlings using the old method before version 6.
The new method doesn't include cloning the Rustlings' repository.
Please follow the instructions in `README.md`:
https://github.com/rust-lang/rustlings#getting-started
gitpod /workspace/rustlings (main) $ rustlings -V
rustlings 6.2.0````

**Comment by mo8it** [comment]
As the output tells you, please follow the new instructions in the README. This means that you should run the following commands:

```bash
cargo install rustlings
rustlings init
cd rustlings
rustlings
```

If you still need any help, feel free to comment :)

**Comment by RodrigoGrz** [comment]
@mo8it I did this, following the README, but I'm still have the same problem.

I'm using the latest version **1.80.1**

```
Error: You are trying to run Rustlings using the old method before version 6.
The new method doesn't include cloning the Rustlings' repository.
Please follow the instructions in `README.md`:
https://github.com/rust-lang/rustlings#getting-started
```

**Comment by mo8it** [comment]
@RodrigoGrz **Remove the whole `rustlings/` directory.**

Now, run `rustlings init`. This command will create a new `rustlings/` directory.

Then, use `cd rustlings` to go into the new directory.

Finally, run `rustlings` in that new directory.
