### ISSUE TITLE
The if2 exercise is confusing

### ISSUE THREAD

**Issue by senekor** [rust-lang/rustlings#2108]
I'm teaching a Rust course right now and I noticed that several people got hung up on this exercise. I know that the "fizz" and "foo" stuff isn't supposed to matter, but it's human nature to search for meaning in things. People were struggling to "turn off their brain" and just code against the tests.

I think it would be nice if the mapping from input to output values made at least some sort of sense. It doesn't have to be an elaborate story, just enough so people can focus on the Rust syntax as they are supposed to.

I'll try to come up with something suitable.

**Comment by mo8it** [comment]
I agree. Feel free to open a PR :D

I might review PRs related to exercises later, but they are welcome, especially if they are related to feedback from your course :)
