### ISSUE TITLE
Add:Third-Party List about rustlings-jp on README

### ISSUE THREAD

**Issue by sotanengel** [rust-lang/rustlings#2118]
Thank you for creating great exercises!!
Thanks to these exercises, I not only know more about Rust, but I like Rust even more :)

I have created a third-party repository with Japanese translations of this exercise 
so that more people in my country(Japan) will know about it and be able to use Rust.
https://github.com/sotanengel/rustlings-jp/tree/main

Then, I added link link to my translated repository at README of Rustlings.
Could you check it?

https://github.com/rust-lang/rustlings/pull/2117

**Comment by mo8it** [comment]
Thank you very much for the translation! I would love to add it to the README. But first, you need to fix the `info.toml` file to include the translated hints.

This directory isn't needed: https://github.com/sotanengel/rustlings-jp/tree/main/create_info_data

You should use the [original `info.toml` file](https://github.com/rust-lang/rustlings/blob/main/rustlings-macros/info.toml) instead. `welcome_message`, `final_message` and all hints need to be translated.

**Comment by sotanengel** [comment]
Thank you for checking my repository!
I 'm going to delete unneeded folder `create_info_data` and add translated hints!
When finished, I will mention you at here 🙇

**Comment by sotanengel** [comment]
@mo8it 

I finished fix points!
Cloud you check it??

・Delete un-need folder
![Image](https://github.com/user-attachments/assets/223a13e3-6cc1-4036-ba44-01ba78b493a1)
![Image](https://github.com/user-attachments/assets/ad86f62a-3cd8-4610-9535-25d34bbcf55e)

・Add all hints
https://github.com/sotanengel/rustlings-jp/blob/20240829/info.toml

**Comment by sotanengel** [comment]
I re-create new PR, so please check below🙇
https://github.com/rust-lang/rustlings/pull/2121

**Comment by mo8it** [comment]
I merged the PR. But please make sure that you merge the branch `20240829` with the changes into the `main` branch.

Thank you for the translation :D
