### ISSUE TITLE
Project build generates files that are recognized as virus by most antivirus apps.

### ISSUE THREAD

**Issue by GeorgePapageorgakis** [rust-lang/rustlings#2120]
I dont know what can be done about it but it seems that there is an issue with this project for most antivirus:

![Image](https://github.com/user-attachments/assets/1aa67b30-a66a-4d06-8e59-8ac665a4cdda)

**Comment by mo8it** [comment]
What Antivirus software are you using? Seems like a one that is too restrictive. I recommend sticking to the builtin antivirus in Wondows and not install additional ones.

This is not a Rustlings problem. You need to tell that antivirus to allow binaries in this directory.
