### ISSUE TITLE
Has the solution changed the intent of the code?

### ISSUE THREAD

**Issue by HelgeStenstrom** [rust-lang/rustlings#2132]
In the exercise code below

https://github.com/rust-lang/rustlings/blob/0432e07864d5ee4d2bac1954c965b2077c0447c6/exercises/22_clippy/clippy3.rs#L7-L10

it seems to me that the intent is to print something if my_option is empty. But in the solution, nothing is printed. 

https://github.com/rust-lang/rustlings/blob/0432e07864d5ee4d2bac1954c965b2077c0447c6/solutions/22_clippy/clippy3.rs#L6-L11

To me (beginner with Rust), that is confusing. I would add something to the print statement, perhaps in an "else" section, print that the option is None.

**Comment by mo8it** [comment]
The code in the exercise is wrong. It tries to print the value of the `Some` variant if we have the `None` variant. So it will always panic. The intent is to print the value in the `Some` variant, but only if there is one. So using `is_none` is wrong. Using `is_some` would be correct, but it would still require the call to `unwrap`. `if-let` solves it more elegantly without false alarms with `unwrap`.

**Comment by HelgeStenstrom** [comment]
Maybe the code comments in the exercise can be changed to make the intent more clear.

**Comment by mo8it** [comment]
> Maybe the code comments in the exercise can be changed to make the intent more clear.

Done in https://github.com/rust-lang/rustlings/commit/38016cb2d6053c7d4f18c7ca98880a3ac7d392fa
