### ISSUE TITLE
Can't install Rustlings (6.3.0) on Linux Mint 22 Cinnamon, Error

### ISSUE THREAD

**Issue by nvmb3rth30ry** [rust-lang/rustlings#2148]
Attempt to install latest **Rustlings** on Linux Mint 22 Cinnamon gives this error:

```
$ cargo install rustlings
    Updating crates.io index
error: cannot install package `rustlings 6.3.0`, it requires rustc 1.80 or newer, while the currently active rustc version is 1.75.0
``` 

**System deets:**
  Kernel: 6.8.0-48-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0 clocksource: tsc
  Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
  CPU: 8-core model: AMD Ryzen 7 7700 bits: 64 type: 
  Memory: total: 64 GiB note: est. available: 61.87 GiB used: 9.74 GiB (15.7%)
  Compilers: gcc: 13.2.0 Client: Cinnamon v: 6.2.9 inxi: 3.3.34

**Comment by mo8it** [comment]
Uninstall the Rust version that you installed with `apt` and install Rust using the recommended way to get the latest version: https://www.rust-lang.org/tools/install
