### ISSUE TITLE
This exercise is not complete?

### ISSUE THREAD

**Issue by historydev** [rust-lang/rustlings#2154]
https://github.com/rust-lang/rustlings/blob/main/exercises/19_smart_pointers/rc1.rs

**Comment by mo8it** [comment]
Of course it is not complete. The task is to complete it.
If you mean that it isn't a good one, then I agree. It will be replaced in version 7.

**Comment by historydev** [comment]
I mean that the task is poorly set, yes, at first I thought that the task was still in development, because there is nothing except a short introduction.

I had to figure out what to do myself. (I did not look at the solutions at all)

In general, having gone through the whole path, I can estimate it like this: 95% is too easy, the last 5% required a little thought.

If we take the beginner level - then probably ok.

I expected a persistent knowledge test, perhaps you have exercises of a difficult level?

**Comment by mo8it** [comment]
You are right. There is an issue for this exercise: https://github.com/rust-lang/rustlings/issues/2083

Rustlings is for beginners or people willing to refresh their knowledge. I plan to create a set of advanced exercises that can be done after finishing these beginner exercises. But there are no concrete exercises yet. No due date.

BTW, people are welcome to create their own set of exercises using the [support for third-party exercises](https://github.com/rust-lang/rustlings/blob/main/THIRD_PARTY_EXERCISES.md). I would be happy to link to such projects in the README.
