### ISSUE TITLE
rustlings init fails

### ISSUE THREAD

**Issue by briggs-w** [rust-lang/rustlings#2169]
I have downloaded and unzipped rustlings-main.zip from https://github.com/rust-lang/rustlings on 2024-12-05; version is 6.4.0. Rust is up to date (version 1.83.0 from 2024-11-26). Platform is Windows 10.

cargo rust install seemed to work

README.md says to do this command next:

`rustlings init`

It gives this error message:

```
Error: You are trying to run Rustlings using the old method before version 6.
The new method doesn't include cloning the Rustlings' repository.
Please follow the instructions in `README.md`:
https://github.com/rust-lang/rustlings#getting-started
```

There is no rustlings folder subfolder of rustlings-main. The rustlings command does exist (rustlings --version gives rustlings 6.4.0).

Thanks!

**Comment by Rooarii** [comment]
👋🏼 you should delete the repo and rerun the rustlings init command, it should work.

**Comment by briggs-w** [comment]
Done! For good measure, I reinstalled rust and downloaded rustlings again. Unfortunately, the error message has not changed.

**Comment by mo8it** [comment]
Do not download Rustlings from the Github release page.

Please follow these steps:
1. Remove everything you downloaded related to Rustlings.
1. Check that Rust is installed by running `cargo --version`. It should show you the current version `1.82.0`
2. Run `cargo install rustlings`
3. Finally, run `rustlings init` to initialize the directory with the exercises.
4. Follow the instructions shown by Rustlings.

**Comment by Obasoro** [comment]
I am on wsl and experiencing this error. After installing using `cargo install rustlings`.

Initializing this process with `rustlings init` I get this error

````
rustlings init
This command will create the directory `rustlings/` which will contain the exercises.
Press ENTER to continue

Error: Initialization failed

Caused by:
    0: Failed to create the `rustlings/` directory
    1: Permission denied (os error 13)```

**Comment by Obasoro** [comment]
> I am on wsl and experiencing this error. After installing using `cargo install rustlings`.
> 
> Initializing this process with `rustlings init` I get this error
> 
> ```
> rustlings init
> This command will create the directory `rustlings/` which will contain the exercises.
> Press ENTER to continue
> 
> Error: Initialization failed
> 
> Caused by:
>     0: Failed to create the `rustlings/` directory
>     1: Permission denied (os error 13)```
> ```

Solved this issues after hours of probing

```whoami```

```find ~/.cargo/ -user root```

```sudo chown -R $(whoami):$(whoami) ~/.cargo/bin/rustlings```

```rustlings init```
