### ISSUE TITLE
Add:Third-Party List about rustlings-zh-cn on README

### ISSUE THREAD

**Issue by SandmeyerX** [rust-lang/rustlings#2178]
Dear Rustlings project team,
Thank you very much for creating such wonderful and practical exercise content! 
﻿
I have created a third-party [repository](https://github.com/SandmeyerX/rustlings-zh-cn/) which contains a carefully made Simplified Chinese translation version of the exercises. The aim is to enable more users in China to access and learn Rust, and then gain a deeper understanding of this powerful programming language.
﻿
However, I understand that there may be some aspects in my work that need improvement. So I sincerely ask you to help check it. After that, could you add a link to my translated repository in the Rustlings README?

Thank you again for your hard work, and I'm looking forward to your feedback!

**Comment by mo8it** [comment]
Thanks for the translation, everything looks good to me :D

I just added the link to the README :)
