### ISSUE TITLE
No field init shorthand for tuple struct

### ISSUE THREAD

**Issue by tobx** [rust-lang/rustlings#226]
Since I am a complete newbie, I am not sure I am correct, but in exercise `structs/structs1.rs` the comment says:

    // TODO: Instantiate a tuple struct!
    // For more fun, use the field initialization shorthand.

Is it not correct that the field init shorthand only exists for classic structs and not for tuples?

**Comment by fmoko** [comment]
Hi @tobx! You're right, I'm not exactly sure what "shorthand" here refers to. I'll remove it for now.

**Comment by fmoko** [comment]
Closed in f72e5a8

**Comment by tobx** [comment]
I think "shorthand" refers to:
https://doc.rust-lang.org/edition-guide/rust-2018/data-types/field-init-shorthand.html

Now that I looked at the exercise again, the comment probably belongs to the classic struct initialization and was wrongly placed at the tuple struct initialization.
