### ISSUE TITLE
Transition from `tests3.rs` to `test3.rs` is confusing

### ISSUE THREAD

**Issue by cincodenada** [rust-lang/rustlings#244]
So I was going through rustlings (which has been great, thanks!) and as it happens, the next unit after `tests3.rs` is `test3.rs` in the root. It took me some hard staring to figure out why the code didn't look like I expected it to before I noticed the one-character difference in the filenames.

I'm not sure what the best solution here is - perhaps `test*.rs` in the root directory could be renamed to `quiz*.rs`, since that also describes what they are, and that doesn't collide with a concept being taught?

**Comment by jrvidal** [comment]
I too have thought about this. Maybe `tests<X>.rs` could be renamed to `testing<X>.rs`?

**Comment by fmoko** [comment]
Maybe something like `test-yourself<X>`?

**Comment by ScarboroughCoral** [comment]
Is this problem solved?

**Comment by ScarboroughCoral** [comment]
Oh, I am confused too.I think it's necessary to rename it.

**Comment by sanjaykdragon** [comment]
> 
> 
> Maybe something like `test-yourself<X>`?

Yeah I think this is a better name

**Comment by jrial** [comment]
My $0.02: renaming to "quiz" is the best suggestion I read in this thread so far. If the idea is to avoid confusion with the previous "test" file, it makes little sense to keep "test" in the name.

**Comment by tonyito** [comment]
Does anyone know of the status of this issue? Still says test 1-4, when 'quiz' would be the perfect alternative as @jrial said.

**Comment by fmoko** [comment]
I think it's a good idea, and if someone doesn't snipe it from me, I'll do it as soon as I can.

**Comment by sanjaykdragon** [comment]
sniped @fmoko 
https://github.com/rust-lang/rustlings/pull/402
