### ISSUE TITLE
Thread 'main' panicked in exercises/if/if1.rs 

### ISSUE THREAD

**Issue by tgranqvist** [rust-lang/rustlings#248]
I'm doing the exercises but I get the following error with if1:

thread 'main' panicked at 'Failed to run 'run' command: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\libcore\result.rs:1165:5

F-Secure also warns about Suspicious:W32/Malware!DeepGuard:
Application blocked
File: temp_16356
Reason: Suspicious:W32/Malware!DeepGuard.n

**Comment by tgranqvist** [comment]
Same error, with same reaction from F-Secure, with tests1.rs.

**Comment by fmoko** [comment]
I'm assuming you're running Windows? Rustlings creates temporary files in its directory, but as long as you have permissions for that directory, there shouldn't be any problems. Maybe it's your antivirus blocking access to them?

**Comment by tgranqvist** [comment]
Thank you @fmoko for the answer! Windows 10, yes. I have access to the directories where Rustling is run from. Most of the exercises run okay, only a few had this issue. If it'd been an access issue, I think none would've worked.
I added an exception for the rustlings executable to F-Secure, and since then it has been working. I was able to rerun the failing exercises.
