### ISSUE TITLE
variables3.rs is not working as expected

### ISSUE THREAD

**Issue by manavsah** [rust-lang/rustlings#257]
with rustlings 2.1.0 for below code:
fn main() {
     let mut x = 5;
     println!("The value of x is: {}", x);
     x = 6;
     println!("The value of x is: {}", x);
 }

i am getting following Error:
Successfully compiled exercises/variables/variables3.rs!
⚠️  Compilation of exercises/variables/variables4.rs failed! Compiler error message:
error[E0381]: borrow of possibly-uninitialized variable: `x`
 --> exercises/variables/variables4.rs:8:27
  |
8 |     println!("Number {}", x);
  |                           ^ use of possibly-uninitialized `x`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0381`.

**Comment by enderdzz** [comment]
Look carefully. It's variables4.rs error log.
