### ISSUE TITLE
as_ref_mut.rs has two I AM NOT DONE

### ISSUE THREAD

**Issue by steelwil** [rust-lang/rustlings#259]

**Comment by AbdouSeck** [comment]
Hi @steelwil, thanks for reporting this. The idea behind the two **I AM NOT DONE** lines is to indicate that there are two separate tasks in the file to finish. If it seems too cumbersome, the second one can definitely disappear. Let me know what you think.

Thank you,

Abdou

**Comment by steelwil** [comment]
I think keeping things consistent is important, writing a different exercise may be a better idea.

**Comment by AbdouSeck** [comment]
Hi @steelwil, I don't think it's necessary to write a different exercise. I would be fine with removing the second "I AM NOT DONE" occurrence.

**Comment by Tuxified** [comment]
:wave: I think this issue can be closed as it has been changed by #292 ?
