### ISSUE TITLE
Add hint to variable shadowing for variables3.rs 

### ISSUE THREAD

**Issue by TorbenJ** [rust-lang/rustlings#260]
I think a nice addition to variables3.rs would be to also mention variable shadowing as it also solves the exercise and also gets explained in chapter 3 of the book (https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html)

Any opinions on that one?

**Comment by AbdouSeck** [comment]
Hi @TorbenJ, that sounds like a terrific idea! Want to add that to `variables3.rs` or even make a `variables5.rs` file where you highlight exactly what's expected?

Thank you,

Abdou

**Comment by TorbenJ** [comment]
Yeah I'll give it a try
