### ISSUE TITLE
.pdb files are not included in .gitignore

### ISSUE THREAD

**Issue by sjmann** [rust-lang/rustlings#275]
I noticed when making a small previous contribution that git wanted me to include a bunch of files with names like: `temp_xxxx.pdb`. I'm not totally sure what these files are for, but they seem to be an artifact of running the code locally - can I add them to the .gitignore or are they required somewhere?

**Comment by fmoko** [comment]
Are you running on Windows? If so, I'd assume that's some kind of file type generated by Visual Studio, so yeah, safe to assume we can ignore that.

**Comment by sjmann** [comment]
Yeah - I'm working in vscode, I'll make a PR for it today at some point.
