### ISSUE TITLE
It is unclear how to get started

### ISSUE THREAD

**Issue by shilangyu** [rust-lang/rustlings#279]
I followed the instructions closely: 

> Just run:
> curl -L https://git.io/rustlings | bash

This checked if I have the dependencies needed and installed the rustlings binary. After it was done I was prompted with `All done! Run 'rustlings' to get started.`. Running `rustlings` failed with 'you are not in the rustlings directory'. This confused me, what directory? So I assumed perhaps the `-s mypath/` flag would help during installation. It didn't. The so called 'rustlings directory' was nowhere to be found.

I read the whole README and found no information about it. Then I saw that the 'Doing exercises' section mentions an `exercises/` directory. I connected the dots and cloned this repo to finally get started.

The point of this story is to show the instructions are unclear about the need of cloning this repo.

Perhaps clone with the bash script?

Thanks!

**Comment by fmoko** [comment]
The bash script clones for you, did you have Git installed?

**Comment by fmoko** [comment]
Actually, it seems like that was accidentally removed :confused: I'll readd it and push a 2.2.1

**Comment by fmoko** [comment]
This should be closed in version 2.2.1 (i.e. the install script should now be cloning the repo again). Sorry for the confusion!
