### ISSUE TITLE
iterators2 doesn't compile before step 2

### ISSUE THREAD

**Issue by sapir** [rust-lang/rustlings#359]
The instructions say to first make the first 2 tests pass, but the last 2 tests have compilation errors. Of course, it can easily be fixed by commenting them out. Still, maybe it would be nicer if Step 1 could be completed without having to do that?

**Comment by sapir** [comment]
I see iterators3 has the last parts commented out. This has the disadvantage that after completing the first part, `rustlings watch` thinks I've completed the exercise.

**Comment by Lynoure** [comment]
I was briefly sidetracked by that as well. There have been other exercises where the next in series builds on the previous solution. Maybe this could be done with the iterators2 as well, by splitting it into 3 different parts.
