### ISSUE TITLE
iterators4 text is a bit unclear

### ISSUE THREAD

**Issue by sapir** [rust-lang/rustlings#361]
"Do not use return. For extra fun don't use loops" etc. - this is an iterators exercise, so I assume that this is a strict requirement, but when I read it at first, I thought it meant that avoiding loops was for bonus points.

**Comment by sthavens** [comment]
I think that you read it correctly. I took the first part to not use the "return" keyword as the function expects to have something returned. The rest I solved using a functional pattern which satisfied the rest but I think that it should pass you even if you use a loop or additional variables.
