### ISSUE TITLE
primitive_types4

### ISSUE THREAD

**Issue by benbyford** [rust-lang/rustlings#363]
got to this test and found i was hitting a brick wall with types, sizes and dot notation (which in hindsight might have been my own fault coming from javascript, php and c#). Any advice?

**Comment by AbdouSeck** [comment]
Hi @benbyford, this is one is interested is `slicing` the array from index 1 to index 4 (exclusive).
Since you're more familiar with `Javascript`, the equivalent would be something like the following:

```
let a = [1, 2, 3, 4, 5];
console.log(a.slice(1, 4));
```
I hope this helps a little

Thanks,

Abdou

**Comment by benbyford** [comment]
Thanks, I might soldier on and come back it after looking at the standard docs, in fact just found this https://doc.rust-lang.org/std/primitive.slice.html Thanks!

**Comment by AbdouSeck** [comment]
The standard library documentation is quite wonderful. Enjoy perusing it!

**Comment by AbdouSeck** [comment]
Hi @fmoko, this one should be closed now.

Thanks!
