### ISSUE TITLE
Excess use of colour and emoji is an accessibility issue

### ISSUE THREAD

**Issue by rjek** [rust-lang/rustlings#364]
Hello,

While I can disable the use of colour using CLICOLOR=0 in the environment, sadly I can find no way to disable the use of emoji.

Is it possible to have rustlings respond to EMOJI=0 in the environment?

**Comment by fmoko** [comment]
@rjek Good idea! Thanks for the suggestion!

**Comment by blerchy** [comment]
@fmoko Thank you for accepting my PR! May I suggest closing this issue?

**Comment by fmoko** [comment]
I think so! Thanks for implementing it~
