### ISSUE TITLE
Help with options1 exercise

### ISSUE THREAD

**Issue by mzfr** [rust-lang/rustlings#366]
Sorry to open an issue for this but I really cannot figure out how I am supposed to finish the `/option/option1.rs`, maybe I am overthinking it.

```rust
fn print_number(maybe_number: Option<u16>) {
    println!("printing: {}", maybe_number.unwrap());
}

fn main() {
    print_number(Some(13));
    print_number(Some(99));

    let mut numbers: [Option<u16>; 5];
    for iter in 0..5 {
        let number_to_add: u16 = {
            ((iter * 5) + 2) / (4 * 16)
        };

        numbers[iter] = number_to_add;
    }
}
```

This fixes the error for the integer type but I can't figure out how to fix the following error:

```
   |
21 |         numbers[iter] = number_to_add;
   |         ^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
```

I fixed that error by changing line 21 to

```rust
numbers[iter as usize] = number_to_add;
```

But then I got an error saying the `number_to_add` has to be of `Optional type` So I made it `Some(number_to_add)` then I got an error saying 

```
21 |         numbers[iter as usize] = Some(number_to_add);
   |         ^^^^^^^^^^^^^^^^^^^^^^ use of possibly-uninitialized `numbers`
```

I am confused about what exactly has to be done

**Comment by kohlrabi** [comment]
I stumbled across the same issue, and in addition to using `iter as usize`, I also initialized `numbers` to zero:

    let mut numbers: [Option<u16>; 5] = [Some(0); 5];

I am not sure if that really is the intended way to solve this task.

**Comment by mzfr** [comment]
@kohlrabi Thanks that works, since this seems to work I'll just go ahead and close the issue. If someone have a better solution then please let me know :)

**Comment by strongpower** [comment]
I met an odd situation:
If i change `main` to:
```
fn main() {
    let mut numbers: [Option<u16>; 5] = [Some(0); 5];
    
    for iter in 0..5 {
        let number_to_add: u16 = 1;
        numbers[iter] = Some(number_to_add);
    }
}
```
It built successfully.

But if i changed it this way:
```
fn main() {
    let mut numbers: [Option<u16>; 5] = [Some(0); 5];
    
    for iter in 0..5 {
        let number_to_add: u16 = iter * 1;
        numbers[iter] = Some(number_to_add);
    }
}
```
It built failed with error:
```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the type `[std::option::Option<u16>]` cannot be indexed by `u16`
 --> src/main.rs:6:9
  |
6 |         numbers[iter] = Some(number_to_add);
  |         ^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
  |
  = help: the trait `std::slice::SliceIndex<[std::option::Option<u16>]>` is not implemented for `u16`
  = note: required because of the requirements on the impl of `std::ops::Index<u16>` for `[std::option::Option<u16>]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

The `numbers[iter] = Some(number_to_add);` line didn't change either way.

**Comment by AyWa** [comment]
**So this is my understanding (but I am quite new to rust), so please correct me if I am wrong**
@strongpower 

In your first example:
```
    for iter in 0..5 {
        let number_to_add: u16 = 1;
        numbers[iter] = Some(number_to_add);
    }
```
`iter` is use only in `numbers[iter]` so the compiler know that it can be only a type of `usize`. (because in rust access memory is `usize` only)

But in the second example (or in the exercise), `iter` is first use to multiple number. In this case because `number_to_add` is a `u16`, `iter` will be a `u16`.

That is why you need to write something like: `numbers[iter as usize] = number_to_add;`

**Comment by strongpower** [comment]
Wah~, it makes sense now. Thanks @AyWa

**Comment by Lynoure** [comment]
Given the focus of this exercise is Option, there really should be some hint about using usize, as that topic is not really covered at this point.

**Comment by DeepSpace2** [comment]
FWIW, `let mut numbers = [Some(0); 5];` also works (instead of `let mut numbers: [Option<u16>; 5] = [Some(0); 5];`).  A bit shorter and does not make you repeat the type and size.

**Comment by zack** [comment]
Should probably use `[None; 5]` instead of `[Some(0); 5]`. That is  the purpose of this being an `options` question, I presume. I don't know if it was always like this, but the rustlings hint here says: 

> Hint 2: There are no sensible defaults for the value of an Array; the values need to be filled before use.

Which I think hints even further at using `None`s instead of an arbitrary value to fill the array.

**Comment by jase-k** [comment]
Here is the solution I came up with: 

Had to initialize numbers with 5 None Option Types. 

Then I changed number_to_add to a u16 and added a Some() arround number_to_add when setting the array's value: 

```
let mut numbers: [Option<u16>; 5] = [None; 5];
    for iter in 0..5 {
        let number_to_add: u16 = {
            ((iter * 1235) + 2) / (4 * 16)
        };

        numbers[iter as usize] = Some(number_to_add)
    }        
```
