### ISSUE TITLE
test4 comes too early

### ISSUE THREAD

**Issue by jrial** [rust-lang/rustlings#381]
The solution to `test4.rs` involves concatenating strings. We've already seen concatenation through formatting with `println!` in previous exercises, but this prints the result rather than returning it.

Making programmatic use of concatenated strings is covered in the section on strings, which is not yet covered by the time we reach test4. I believe it would be better to move the strings exercises up, or test4 back, so all the required sections have been covered before tackling this exercise.

**Comment by drguildo** [comment]
Surely the bigger issue here is that it relies on knowledge of macros? Like the previous exercises were literally just the most basic function stuff like parameter and return types and now I'm supposed to have knowledge of the languages internal representation!?

**Comment by fmoko** [comment]
@drguildo `test4.rs` is after the macro exercises in the recommended order, so you should have absorbed the basics of macros at that point.

Generally, since there were some added exercises that all fall behind `test4`, we should probably look at adding another one (or even multiple) after it.

**Comment by drguildo** [comment]
@fmoko That's weird because for me all of of the test?.rs files in the root of the exercises directory appeared after I'd finished the functions?.rs exercises.

**Comment by fmoko** [comment]
@drguildo Was that while you were running `rustlings watch`? If so, can you file this as a separate issue? That's definitely not right.

**Comment by drguildo** [comment]
@fmoko It was using `rustlings watch`, but I don't seem to be able to reproduce the issue. If I encounter it again I'll open a separate issue.

**Comment by mo8it** [comment]
The exercise has changed in the last years and the issue is not relevant anymore 😅
