### ISSUE TITLE
iterators4: solution exists in the documentation

### ISSUE THREAD

**Issue by ikar49** [rust-lang/rustlings#391]
The hint says:
> But you can also use ranges and iterators to solve this in rust.

I went to read the documentation on iterators and saw [this](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.product):
```rust
fn factorial(n: u32) -> u32 {
    (1..=n).product()
}
assert_eq!(factorial(0), 1);
assert_eq!(factorial(1), 1);
assert_eq!(factorial(5), 120);
```

Maybe need a more complex exercise without factorial?

**Comment by AlexandruGG** [comment]
I agree, though possibly the exercise was meant to be solved using `fold`:

```
pub fn factorial(n: u64) -> u64 {
    (1..=n).fold(1, |a, b| a * b)
}
```

I think an alternative would be to ask that something else is computed, like the _product of the squared roots of numbers from 1 to n_ - that way one wouldn't be able to use just the built-in functions to solve the exercise.

**Comment by VuiMuich** [comment]
I want to add that this exercise relying on the knowledge of the mathematical concept of factorial is not optimal.
As English is my second language and almost all my mathematical education has been in German I had to research at first what factorials are. Not that I regret this experience, but a simple paragraph in the hints explaining factorials might help reducing this potential barrier.

**Comment by haydonryan** [comment]
It'd be great to include the algorithm for factorials as comments in the code. I also had to google it.  I haven't done a factorial in 25 years.

**Comment by DLG-bmueller** [comment]
Maybe it makes sense to use matrix multiplication or a similar approach. The explanation can be put in the documentation so anyone can follow the mathematics behind it. But it is just an idea. If this sounds interesting, I can create an example.

**Comment by PascalGiessler** [comment]
Maybe it makes sense to use matrix multiplication or a similar approach. The explanation can be put in the documentation so anyone can follow the mathematics behind it. But it is just an idea. If this sounds interesting, I can create an example.

**Comment by yrmbeauty** [comment]
After adding `assert_eq!(1, factorial(0));` test case, it can be done only by built-in `.product()` method, solution with `.fold()` doesn't fits this case

**Comment by mo8it** [comment]
I improved the exercise a bit and explained what a factorial is (with a link to the Wikipedia article about it).
I think that it is fine to find the solution as an example in the docs. Bonus for reading the docs :D
The hint tells you to use `fold`. After that, Clippy should tell you to just use `product`. One more opportunity to see how useful Clippy is :D

If someone is still not satisfied with [the current version of the exercise](https://github.com/rust-lang/rustlings/blob/main/exercises/18_iterators/iterators4.rs), I am open to suggestions :)
