### ISSUE TITLE
Solutions for `try_from_into` and `from_str` are same

### ISSUE THREAD

**Issue by IkaR49** [rust-lang/rustlings#392]
I'm just copy-paste my code from fisrt exercise to second and it's ok.
May be should combine them into one?

**Comment by AbdouSeck** [comment]
Hi @IkaR49,

Thanks for your comments. `TryFrom` and `FromStr` are two different traits, although the former could everything that the latter does. For the sake of completeness, combining the two would be misleading. What's possible is changing the code in either one of them to make the exercises different.

What do you think? If that sounds good to you, we'd be more than happy to have you implement it.

Thanks!

Abdou

**Comment by IkaR49** [comment]
Hm, your idea is better than mine.
So, I'm newbie, but i'll try :)
