### ISSUE TITLE
rustlings/exercises/test4.rs

### ISSUE THREAD

**Issue by Joshfairhead** [rust-lang/rustlings#396]
Perhaps its just because I'm totally new to this game, but it would have been really nice to have used format! before in an example before encountering it here without a hint! Everything was right except the println! I was using in its place...

**Comment by kellda** [comment]
Maybe not more used before, but `concat!` also works and may be easier

**Comment by calvinbrown085** [comment]
@Joshfairhead @kellda @fmoko I don't see a `test4.rs` in the exercises folder, am I missing something? 😄

**Comment by kellda** [comment]
Seems it moved since:
https://github.com/rust-lang/rustlings/tree/3.0.0/exercises

**Comment by calvinbrown085** [comment]
Did it get removed? I'm having trouble finding it in `main`

**Comment by fmoko** [comment]
@calvinbrown085 The test files got renamed a while ago: https://github.com/rust-lang/rustlings/blob/main/exercises/quiz4.rs

**Comment by calvinbrown085** [comment]
@fmoko Ah, I see. Thank you!

**Comment by mo8it** [comment]
Outdated since the exercise has been changed.
We teach a bit about the `format!` macro in `strings3` now.
