### ISSUE TITLE
error[E0425]: cannot find value `x` in this scope

### ISSUE THREAD

**Issue by nikunjkumarnakum** [rust-lang/rustlings#398]
After installing rustlings course on my machine I ran it from the terminal, and running it with
`rustlings watch`
causes an error [E0425], I am running ubuntu 20.04 with rust v 1.43 installed and other dependency as directed by installer. The brief error is as follows.
![Screenshot from 2020-05-15 20-54-48](https://user-images.githubusercontent.com/40589688/82069406-e2d2ba80-96f0-11ea-8116-304b23d4fb7a.png)

**Comment by fmoko** [comment]
That's Rustlings running as it should :) Your objective is to fix the errors in the files that it points towards, so that no more errors are reported, at which point the exercise is considered done!
