### ISSUE TITLE
test2.rs compiles even though only line 24 is solved

### ISSUE THREAD

**Issue by tonyito** [rust-lang/rustlings#399]
The instructions are a bit unclear when it comes to what needs to be accomplished in this file. 

The goal of this test should be to have all 10 outputs print onto the console, yet the instructions imply the code compiling accomplishes the task. Moreover, line 24 is the only line that needs to be fixed in order to get the code to compile.

Two solutions I can think of for this issue:

1. Remove the semicolons from each line to prevent the file from compiling until the line is at least touched. However, this does not totally resolve the issue of needing each argument to be called by the correct function.

2. Change the instructions of the exercise to output 10 of the correct lines from each function called instead of making it the goal to compile the program.

What does everyone else think?

**Comment by dev-cyprium** [comment]
Agreed, while I was doing this exercise I was under the same impression

**Comment by mo8it** [comment]
Outdated since exercise `test2` has been changed since then.
