### ISSUE TITLE
Smart Pointer Exercises

### ISSUE THREAD

**Issue by vikulikov** [rust-lang/rustlings#403]
There is an exercise to use `Arc<T>` with threads. But I haven't found any exercises to practice in using `Rc<T>`, `RefCell<T>`, `Weak<T>` etc separately or together.

**Comment by danwilhelm** [comment]
Agreed -- it would be nice to cover `Box` and `Rc` before the threadsafe `Arc`.

**Comment by AlexandruGG** [comment]
I just wrote an exercise for `Box` here: https://github.com/rust-lang/rustlings/pull/409.

Let me know what you think 😁

**Comment by fmoko** [comment]
Closing for now, feel free to let me know if you're interested in more smart pointer-related exercises.

**Comment by Pacheco95** [comment]
@diannasoreil I would love it! I also created an issue asking for more smart pointers exercises https://github.com/rust-lang/rustlings/issues/1020
