### ISSUE TITLE
rustlings hint primitive_types4 suggest wrong documentations.

### ISSUE THREAD

**Issue by wontheone1** [rust-lang/rustlings#405]
```
$ rustlings hint primitive_types4

...
If you're curious why the first argument of `assert_eq!` does not
have an ampersand for a reference since the second argument is a
reference, take a look at the Deref coercions section of the book:
https://doc.rust-lang.org/book/ch15-02-deref.html
```

The coercion from arrays to slices doesn't happen via dereference. 
It happens via `unsizing`, a completely different mechanism.
The coercion [T; N] -> [T] happens through the same means as Type -> dyn Trait.
Refer https://doc.rust-lang.org/std/marker/trait.Unsize.html

**Comment by ayushmishra2005** [comment]
@wontheone1 I would like to address this. I agree with your suggestion. Could you please suggest me the text, which you want here?

**Comment by wontheone1** [comment]
@ayushmishra2005 , I don't really have a particular suggestion, sorry

**Comment by diannasoreil** [comment]
Hopefully this rewrite (https://github.com/rust-lang/rustlings/commit/6020ec1fe21aa1763821940dcc7029b99fb9d00a#diff-6bb9edccc7e8b95865f9969548084abe509295653d1423a4c0bb7b01fccb2bf3R217) makes it make a bit more sense?
