### ISSUE TITLE
Structs1: Unit structs aren't actually in the official documetation.

### ISSUE THREAD

**Issue by allstar87** [rust-lang/rustlings#407]
The Book chapter 5 mentions unit structs but gives no examples.  There is no official documentation for unit structs as far as I can find.

Also, this lesson is 2% structs, 98% omfg why are there so many kinds of strings and why are all of them wrong?

Don't fix, have someone else redo from scratch.

**Comment by sjmann** [comment]
Is it exercise three that caused you to get confused by string types?

I wonder if the exercise would be clearer if we change the signature of `Package::new` function to take &str instead of String, and move the `String::from()` which is repeated in all of the tests into the `new` function - something like:

```
impl Package {
    fn new(from: &str, to: &str, weight: f32) -> Package {
        if weight <= 0.0 {
            // Something goes here...
        } else {
            let from = String::from(from);
            let to = String::from(to);
            return Package {from, to, weight};
        }
    }
    // snip
}
```

Otherwise the exercises look ok to me, but having done them before it's difficult to be objective I guess.

**Comment by danwilhelm** [comment]
@allstar87 Perhaps adding some additional comments throughout would be helpful?

For example, it could be clarified that the unit struct declaration does not need to be modified. Also, that its initialization follows the same pattern as the others.

That said, I do see how it could be a bit tricky. The struct field names (and their initialization values) must be inferred from the asserts -- which are at the end of the file.

**Comment by klequis** [comment]
I'm stuck in structs1.rs. After getting classic_c_structs & tuple_structs to work, instantiating the unit struct `let unit_struct = UnitStruct` causes problems/errors to occur in classic_c_structs & tuple_structs. Having the solutions to the first two problems invalidated by trying to solve the third on seems to me to be a problem in itself which should be solved/removed.

I did see that lifetimes seem to be the solution but don't know enough about them yet to get the entire exercise to work.

**Comment by oulenz** [comment]
I also just ran into structs1. I have no idea what a unit struct is supposed to be. In particular, there doesn't seem to any clue regarding its syntax (what kind of brackets) and what goes in it.

@sjmann for me it's exercise 1. I need to specify the types of the struct members, and my first two guesses were `str` and `String`, which seem to be wrong, and my third guess `&str` seems to require setting a lifetime, which I don't know about yet.

**Comment by QuixoticJoe** [comment]
I am also stuck on UnitStructs. 

This is the error: 
---- tests::unit_structs stdout ----
thread 'tests::unit_structs' panicked at 'assertion failed: `(left == right)`
  left: `"\"UnitStruct\"s are fun!"`,
 right: `"UnitStructs are fun!"`', exercises/structs/structs1.rs:48:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

And the relevant code:

#[derive(Debug)]
struct UnitStruct();

    #[test]
    fn unit_structs() {
        // Instantiate a unit struct!
        let unit_struct ="UnitStruct";

        let message = format!("{:?}s are fun!", unit_struct);

        assert_eq!(message, "UnitStructs are fun!");
    }


I cannot work out how to remove the back slashes that cause the inequality between left and right parts of the assertion.

UnitStructs really are not fun!!

**Comment by jcrigby** [comment]
this passes

remove the parens from struct UnitStruct() (they are not in the original):
#[derive(Debug)]
struct UnitStruct;
...
then the let line is just:
let unit_struct = UnitStruct;

your version is setting unit_struct to a string:
let unit_struct ="UnitStruct";

**Comment by opensas** [comment]
Hi, I'm also stuck with struct1.rs

This is my attemp:

```rust
    #[test]
    fn unit_structs() {
        // TODO: Instantiate a unit struct!
        struct UnitStruct;
        let unit_struct = UnitStruct;

        let message = format!("{:?}s are fun!", unit_struct);

        assert_eq!(message, "UnitStructs are fun!");
    }
```

and the error I receive

```
! Compiling of exercises/structs/structs1.rs failed! Please try again. Here's the output:
warning: unused import: `super::*`
  --> exercises/structs/structs1.rs:17:9
   |
17 |     use super::*;
   |         ^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0277]: `tests::unit_structs::UnitStruct` doesn't implement `Debug`
  --> exercises/structs/structs1.rs:50:49
   |
50 |         let message = format!("{:?}s are fun!", unit_struct);
   |                                                 ^^^^^^^^^^^ `tests::unit_structs::UnitStruct` cannot be formatted using `{:?}`
   |
   = help: the trait `Debug` is not implemented for `tests::unit_structs::UnitStruct`
   = note: add `#[derive(Debug)]` to `tests::unit_structs::UnitStruct` or manually `impl Debug for tests::unit_structs::UnitStruct`
   = note: this error originates in the macro `$crate::__export::format_args` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0277`.
```

Any help would be welcom

BTW, this is what I took as reference: https://doc.rust-lang.org/book/ch05-01-defining-structs.html#unit-like-structs-without-any-fields
