### ISSUE TITLE
Rustlings Watch does not refresh in WSL 2 with Ubuntu 20.04

### ISSUE THREAD

**Issue by sthavens** [rust-lang/rustlings#417]
Fresh install of Ubuntu 20.04 with rust, its dependencies, and rustlings being the only installations. Had same problem with 18.04. Began with upgrading to WSL2 but I cannot go back to version 1 due to compatibility issues with planned installations.

This happens in the Windows Terminal, in VS Code's Terminal, as well as in the Ubuntu 20.04 app.

Rustlings watch runs fine when entered but does not re-run the tests as it is supposed to on a saved change.

If you cancel out of watch and re-run, it runs all of the tests again but never starts "watching".

**Comment by danwilhelm** [comment]
@sthavens I verified this, but it is almost certainly a WSL2 bug: https://github.com/microsoft/WSL/issues/4739.

As a workaround, move rustlings into your WSL2 filesystem (i.e. `~`), and `rustlings watch` will work correctly. (In Explorer, you can access it here: `\\wsl$\Ubuntu\home`.)

**Comment by sthavens** [comment]
@danwilhelm Thank you! The workaround was successful. It also improved the speed at which the tests ran in the first place.
