### ISSUE TITLE
exercices/structs/structs3.rs Use of float for a cost in a course, really ?

### ISSUE THREAD

**Issue by SebastienCaunes** [rust-lang/rustlings#432]
Line 28 there is this horrible error: 
`
    fn get_fees(&self, cost_per_kg: f32) -> f32 {
`

**Floats must not be used for a price, never, ever. And even more in a lesson.**

This is much more clever, and just correct:
`
    fn get_fees(&self, cent_per_kg: i32) -> i32 {
`

Sorry but I see this error too often to stay silent, this point has to be understood and not taken lightly: **Floats are not decimal numbers.** Please do not contribute in growing a population of rust coders that don't understand floats.

Some might think, "it's not the purpose of the lesson, that's too advanced to be explained", so why not using integers and cents then? Why should we show a student one of the worst thing he could ever do in production?

**Comment by fmoko** [comment]
Thanks for reporting this! I would advise you to soften your language a bit in the future, as some maintainers may not take too kindly to the very pejorative tone you're putting up here. That being said, I agree that this is a bad practice. Would you be up for creating a PR to fix this?

**Comment by danwilhelm** [comment]
@SebastienCaunes If you are able to make a PR, note there is a similar problem with `assert_eq!` - it is not ideal to perform exact comparisons on floating point values. Also it might be nice to change `from` -> `sender_city` and `to` -> `recipient_city`.

**Comment by SebastienCaunes** [comment]
@fmoko : houps ! sorry for the tone, I'm not native english and also I had a lot of hard fights on this subject. I even got fired for "incompatibility with the lead developer" trying to explain him that it's a bad idea to use a float as a primary key in database to handle more than 2 bilions records.

Good Idea to do a PR I'll try to do it cleanly for getting forgiven for my bad tone. :)

@danwilhelm : yes I saw that too, and I think I will also convert the weight to grams so we only have i32.

**Comment by orlovedev** [comment]
I can't get why I need to multiply the price per **kilo** by the weight in **grams** to make the test pass. Is it something wrong with me or the naming needs to be amended since the previous update?

Also, in the hint, the method is referred to as "calculate_transport_fees" but in the impl it is called "get_fees".

**Comment by SebastienCaunes** [comment]
> I can't get why I need to multiply the price per **kilo** by the weight in **grams** to make the test pass. Is it something wrong with me or the naming needs to be amended since the previous update?
> 
> Also, in the hint, the method is referred to as "calculate_transport_fees" but in the impl it is called "get_fees".

The thing that money must not be stored in a float. If you can't get why check how float numbers work. Choosing the proper variable type for a representing a value is the first task of a developer, before any algorithm.

**Comment by orlovedev** [comment]
Yes, I agree. That's not what I was asking. My question was purely logical. Why does the multiplication of **price per KILOGRAM** by the **weight in GRAMS** results in passing tests?

Should it be **price per GRAMS** * **weight in GRAMS** or **price per KILO** * **weight in KILOS** to be logically correct?

**Comment by SebastienCaunes** [comment]
> Yes, I agree. That's not what I was asking. My question was purely logical. Why does the multiplication of **price per KILOGRAM** by the **weight in GRAMS** results in passing tests?
> 
> Should it be **price per GRAM** * **weight in GRAMS** or **price per KILO** * **weight in KILOs** to be logically correct?

OK So you can guess that "price per gram" or "weight in kilogram" would induce decimals to have realistic values. I also think we should use only integers and kilograms and not caring for the "realism". The only important thing to me is not showing the bad example of money held in floats.

**Comment by orlovedev** [comment]
It's not about "caring for the realism". It's just confusing, or at least it was confusing for me. If the price is per kilogram and the weight is in grams, it is obvious that I need to multiply the weight by 1000 to get the same measurement (price per kilo **and** weight in kilos). But doing this leads to failing tests.

I don't get what any of this has to do with storing money in floats, TBH.

Either the variables can be renamed to use the same measurement, or the tests can be amended to take the difference into consideration.

**Comment by SebastienCaunes** [comment]
You can understand that using integer for the weight in kilogram is not precise enough.
The same way, using integer for transportation fees is not precise enough (at least 1 cent per gram wich is 10 per kilo).
