### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by fmoko** [rust-lang/rustlings#437]
We should do this, but I'm trying to figure out what the necessary steps are. I think at the very least it's:

1. Someone with write access runs `git branch -m master main` and `git push -u origin main`
2. We change the part in the install script (https://github.com/rust-lang/rustlings/blob/e1e453075f5c78e3bca2f0dcaa9260f18d40344d/install.sh#L118)
3. We change the other occurrences (https://github.com/rust-lang/rustlings/blob/e1e453075f5c78e3bca2f0dcaa9260f18d40344d/src/main.rs#L135, https://github.com/rust-lang/rustlings/blob/e1e453075f5c78e3bca2f0dcaa9260f18d40344d/src/exercise.rs#L137)
4. We set the new default branch to `main`.

I don't think this necessitates a new version release, since we don't actually change anything except for the installer, and most new installs are checked out to a tag anyways. Thoughts @jrvidal @AbdouSeck?

**Comment by AbdouSeck** [comment]
Hi @fmoko, this sounds fine to me.

I ran the following command:
`grep master $(find . -type d \( -path ./.git -o -path ./target \) -prune -o -type f -print)`

and got the following matches:
```
./install.sh:118:        echo "Rustlings will be installed using the master branch"
./install.sh:119:        Version="master"
./exercises/clippy/README.md:8:For more information about Clippy lints, please see [their documentation page](https://rust-lang.github.io/rust-clippy/master/).
./src/main.rs:135:        println!("https://github.com/rust-lang/rustlings/blob/master/CONTRIBUTING.md");
./src/exercise.rs:137:                // This is already fixed on master branch. See this issue to track merging into Cargo:
```
These^ files and line numbers may come in handy.

Thanks!

Abdou

**Comment by jrvidal** [comment]
What's the rationale for this? `master` as the default branch is a pretty widespread convention, moreso in the core Rust projects.

**Comment by fmoko** [comment]
@jrvidal Yep, it's a widespread convention, but the association for `master` to the master/slave naming is there, which itself has associations to slavery. GitHub is [working on this](https://twitter.com/natfriedman/status/1271253144442253312), as is [GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/221164), and even if we're the first Rust project to do this, I think it would set a nice precedent. Besides, the advantages on this far outweigh the disadvantages, so I think there's no harm in doing it, especially since we can revert the step.

**Comment by jrvidal** [comment]
Ah, I see, I was missing some context. :+1: on my part

**Comment by fmoko** [comment]
Done with https://github.com/rust-lang/rustlings/commit/55a9284665dc6ef5d9db6f73e76630f22d3ea43d
