### ISSUE TITLE
Attempt to solve \exercises\option\option2.rs triggers bug in rustlings watch

### ISSUE THREAD

**Issue by TrashAccount3424** [rust-lang/rustlings#440]
I ran `rustlings watch` while editing exercises option2.

I ended up with rustlings running the following code which should produce some kind of error but rustling never finishes "running the code".

```rust
// option2.rs
// Make me compile! Execute `rustlings hint option2` for hints

// I AM NOT DONE

fn main() {
    let optional_value = Some(String::from("rustlings"));
    // Make this an if let statement whose value is "Some" type
    if let Some(value) = optional_value {
        println!("the value of optional value is: {}", value);
    } else {
        println!("The optional value doesn't contain anything!");
    }

    let mut optional_values_vec: Vec<Option<i8>> = Vec::new();
    for x in 1..10 {
        optional_values_vec.push(Some(x));
    }

    // make this a while let statement - remember that vector.pop also adds another layer of Option<T>
    // You can stack `Option<T>`'s into while let and if let
    while let value = optional_values_vec.pop() {
        println!("current value: {:?}", value);
    }
}
```
The terminal shows `⠉ Running exercises/option/option2.rs...` with the usual flickering but never ends and I had to kill rustlings.

I change the last who lines to
```rust
while let Some(value) = optional_values_vec.pop() {
        println!("current value: {:?}", value.unwrap());
```
to fix the problem and make it compile. I don't know if that's the correct solution but it may give a hint at what is causing rustlings to endless(?) loop.

Environment Info:
rustc 1.44.0 (49cae5576 2020-06-01)
rustlings 3.0.0
Microsoft Windows 10 Pro Version 1909 10.0.18363 Build 18363

**Comment by AbdouSeck** [comment]
Hi @TrashAccount3424, the following snippet loops infinitely:

```
int main() {
    let mut optional_values_vec: Vec<Option<i8>> = Vec::new();
    while let value = optional_values_vec.pop() {
        println!("current value: {:?}", value);
    }
}
```
So, the code you provided will loop infinitely. The piece of code`optional_values_vec.pop()` will return `None` at every iteration, making the assignment `let value = optional_values_vec.pop()` a valid **_binding assignment_**.
In sum, your answer to that exercises compiles, but that does not quite mean that it is correct.

The latest `main` branch of `rustlings` should display warnings from the compiler about the somewhat incorrectness of your code.

In any case, this is not an issue with `rustlings` per se. Some of the exercises will pass as long as your code compiles without compiler errors; so they don't really check whether or not the provided answer is correct.

I hope this has provided you with some clarifications.

Thanks!

Abdou
