### ISSUE TITLE
if/if1.rs : Stuck with no error output 

### ISSUE THREAD

**Issue by Technician0x** [rust-lang/rustlings#441]
Hi,
I'm a begininer in Rust just trying to do Rustlings exercises (thanks for this awesome projet btw).

`> rustc --version
rustc 1.36.0 (53f9df32 2019-07-03)`

`> rustlings --version
rustlings 3.0.0`

`> ls -la`
`total 5752`
`drwxr-xr-x 1 runner runner     432 Jun 16 11:24 .`
`drwxr-xr-x 1 runner runner    4096 Jun 16 11:12 ..`
`-rw-r--r-- 1 runner runner   12104 Jun 16 09:01 .all-contributorsrc`
`-rw-r--r-- 1 runner runner     147 Jun 16 09:01 buildkite.yml`
`-rw-r--r-- 1 runner runner   42395 Jun 16 09:01 Cargo.lock`
`-rw-r--r-- 1 runner runner     460 Jun 16 09:01 Cargo.toml`
`-rw-r--r-- 1 runner runner   14473 Jun 16 09:01 CHANGELOG.md`
`-rw-r--r-- 1 runner runner      88 Jun 16 09:01 .clog.toml`
`-rw-r--r-- 1 runner runner    4145 Jun 16 09:01 CONTRIBUTING.md`
`-rw-r--r-- 1 runner runner     691 Jun 16 09:01 default_out.txt`
`-rw-r--r-- 1 runner runner     102 Jun 16 09:01 .editorconfig`
`drwxr-xr-x 1 runner runner     396 Jun 16 09:01 exercises`
`drwxr-xr-x 1 runner runner     168 Jun 16 09:03 .git`
`-rw-r--r-- 1 runner runner     103 Jun 16 09:01 .gitignore`
`-rw-r--r-- 1 runner runner   28648 Jun 16 09:01 info.toml`
`-rw-r--r-- 1 runner runner    3023 Jun 16 09:01 install.ps1`
`-rwxr-xr-x 1 runner runner    3787 Jun 16 09:01 install.sh`
`-rw-r--r-- 1 runner runner    1095 Jun 16 09:01 LICENSE`
`-rw-r--r-- 1 runner runner   20144 Jun 16 09:01 README.md`
`-rw-r--r-- 1 runner runner      35 Jun 16 09:01 .replit`
`-rwxr-xr-x 2 runner runner 5712144 Jun 16 09:34 rustlings`
`drwxr-xr-x 1 runner runner      76 Jun 16 09:01 src`
`drwxr-xr-x 1 runner runner      56 Jun 16 09:17 target`
`drwxr-xr-x 1 runner runner      54 Jun 16 09:01 tests`

`> uname -a
Linux 8f8434fb425c 5.4.0-1009-gcp #9-Ubuntu SMP Fri Apr 10 19:12:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

I'm actually working on an online IDE named repl.it, which means i'm compiling on a very low-cost VM.

All variables worked perfectly, but for the if exercises it's stuck on this ouput :
`! Testing of exercises/if/if1.rs failed! Please try again. Here's the output:
`
(obviously there isn't a single print after this)

And i'm not new to programming so i'm pretty sure this code is correct (and it worked great in the Rust playground) :
`pub fn bigger(a: i32, b: i32) -> i32 {`
`    if a > b {a} else {b}`
`}`

If it isn't, well my bad, but i think it should explain my error.

**Comment by Skepfyr** [comment]
This seems to be because your rustc version is quite old, I'm not sure of the exact version requirements but a `rustup update` should solve your problem. (You may have to reinstall rustlings although I'm unsure if you need to)

**Comment by Technician0x** [comment]
Hi,

I'm not strained to work on repl.it anymore and everything works great in Clion.

Thanks for your answer anyway, i'm sure you're right about the issue.

**Comment by wassup-** [comment]
@Skepfyr Updating rust seems to solve the issue. 

Why doesn't it work in an older version?
