### ISSUE TITLE
Support GitHub Codespaces

### ISSUE THREAD

**Issue by taki-on** [rust-lang/rustlings#442]
Hey! I am wondering if it would make sense to support GitHub Codespaces (even though it is still in beta). I forked this repo and added a container setup (https://github.com/taki-on/rustlings). When I launch the Codespace in the forked repo, all rust tools are installed already. I just compiled the source via Terminal (which is provided by VS Code online), then I could just launch `rustlings watch`, so that I could go through the exercises without leaving the web browser. I personally think it is a great experience, and it is very easy to start for beginners.

If this sounds good, I can open a small PR, in order to support GitHub Codespaces with rust tools installed. It is actually pretty simple, since we can just use pre-built dev container setup provided by Microsoft (https://github.com/microsoft/vscode-dev-containers/tree/master/containers/rust)

What do you think?

**Comment by jrvidal** [comment]
That sounds pretty cool, though I'd be a bit reluctant to merge anything if we as maintainers cannot test it :sweat_smile:

**Comment by taki-on** [comment]
That makes sense :) When Codespaces is coming to broader ring, then I will ping you guys again :)

**Comment by fmoko** [comment]
Yeah, I'd be absolutely up for doing this as soon as we can verify it works :P

**Comment by nickytonline** [comment]
Codespaces is available to all now as far as I know. I have a branch that adds support for Codespaces. Happy to put up a PR.

https://github.com/nickytonline/rustlings/tree/add-support-for-github-codespaces

**Comment by diannasoriel** [comment]
Looks like we'd need a team plan for the rust-lang org. I'm gonna ask our infra team whether this is something we have or is otherwise feasible.

**Comment by benjaminbauer** [comment]
A first step would be to add a devcontainer spec -> https://github.com/rust-lang/rustlings/pull/1194

**Comment by rv0710** [comment]
How can I install the rust compiler on workspace on github.

**Comment by shadows-withal** [comment]
Closed by #1399.
