### ISSUE TITLE
idiomatic anwers

### ISSUE THREAD

**Issue by alexxroche** [rust-lang/rustlings#446]
I've just completed `exercises/conversions/from_into.rs` and feel that my solution wasn't very idiomatic.
Do we think that having "the answers in the back of the book" (at least for the more complex exercises) as a reference, (even if its in a separate repo) would help ensure that students don't acquire bad habits and don't end up "writing rust in the style of some other language" ?

**Comment by rainyday** [comment]
Came here to ask the exact same question about the same exercise. I have a solution that works but I'm pretty sure is "bad" since it uses nested matches and repeats code but I don't have a clue how to improve it.

**Comment by alexxroche** [comment]
I've started to curate the many (at least 75) `rustling solutions` repos here on github. I have two contenders for "most idiomatic" for from_into.rs  [Try this](https://github.com/alexxroche/rustlings-idiomatic-solutions/blob/master/exercises/conversions/from_into.rs/a_from_into.rs) and compare it with [this other solution](https://github.com/alexxroche/rustlings-idiomatic-solutions/blob/master/exercises/conversions/from_into.rs/b_from_into.rs)

**Comment by alexxroche** [comment]
I have my first draft of [curated solutions](https://github.com/alexxroche/rustlings-idiomatic-solutions). (Union of my answers and some better solutions that I found on github.) Just need a more talented Rustacean [0] to verify them, (and send me pull requests for the suboptimal solutions that I've entered.) 
 Some of the exercise seem to have one obvious solution, while others have more than one answer; where I thought it useful I've included each answer, (and occasionally a "don't do it like this" where I found myself going wildly off track.)

[0] might be myself in the future

**Comment by melkir** [comment]
Thanks @alexxroche for your solutions, it helped me to improve my answer for the `try_for_into` exercice with have been fixed recently 😁

The solution that I've used differs a little since I'm using `map_err` in order to convert the error to a `String` and avoid changing the test parts to include `#[should_panic]`.

If anyone get stucks, here's mine https://github.com/melkir/rustlings/tree/responses

**Comment by bilboquet** [comment]
Hello
I came with the following solution :
<details>
<summary>
# SHOW ME
</summary>
<p>

```rust
impl From<&str> for Person {
    fn from(s: &str) -> Person {
        if s.len() > 0 {
            let mut i = s.split(',');
            if let Some(name_) = i.next() {
                if name_.len() > 0 {
                    if let Some(age_str) = i.next() {
                        if let Ok(age_usize) = age_str.parse::<usize>() {
                            if None == i.next() {
                                return Person {
                                    name: name_.to_string(),
                                    age: age_usize,
                                };
                            }
                        }
                    }
                }
            }
        }

        Person::default()
    }
}
```
</details>

Could you comment on how idiomatic it is please?

**Comment by alexxroche** [comment]
I don't currently have time to check your code. We have a code review channel in the `Rust Programming Language Community Server` discord https://discord.gg/tPHGcqrG4H

I think that we usually reserve github for development, and requests to inspect your personal answers to exercises is done in places like stackoverflow.com (Or over in discord.)

**Comment by dahifi** [comment]
I'm a newbie but after reviewing all the other posted solutions, I think this one is best, as it relies on `match` and some inter_RUST_ing error handling with `.unwrap_or_default()`. 

https://github.com/alexxroche/rustlings-idiomatic-solutions/blob/master/exercises/conversions/from_into.rs_/from_into_vec_match.rs
