### ISSUE TITLE
Tracking progress of solved/unsolved

### ISSUE THREAD

**Issue by torymur** [rust-lang/rustlings#449]
Is there a way to see a progress?

It would be nice to see where you are and how many exercises there are left to do.

**Comment by estebanborai** [comment]
Hey @torymur!

I think this is a good to have feature! And as I can see in the `main.rs` file, we already have the resources we need to accomplish this!

**Comment by rytheo** [comment]
This looks like a duplicate of #360

**Comment by estebanborai** [comment]
@rytheo it looks like!

**Comment by jrvidal** [comment]
Closing as duplicate then :+1:
