### ISSUE TITLE
/exercise/generics3.rs I dont't know how to solve it 

### ISSUE THREAD

**Issue by master-davidlee** [rust-lang/rustlings#450]
https://github.com/rust-lang/rustlings/blob/main/exercises/generics/generics3.rs
can you give me the answer of this question?

**Comment by fanninpm** [comment]
Did you solve `generics2`? The solution to `generics2` is roughly 90% of the solution to `generics3`.

**Comment by master-davidlee** [comment]
Yeah I’ve finish all exercise  and I put the answer in my repo
