### ISSUE TITLE
rustlings-1:  modules2.rs - dead code warning

### ISSUE THREAD

**Issue by dboyce-gh** [rust-lang/rustlings#451]
*Context: rustlings-1 branch,  modules.rs exercise.*

When the hinted-at keyword is used,  modules2.rs compiles and runs on the playground but issues the following warning:

```
   Compiling playground v0.0.1 (/playground)
warning: constant item is never used: `BERNIE_SANDERS`
  --> src/main.rs:10:9
   |
10 |         pub const BERNIE_SANDERS: &'static str = "Bernie Sanders";
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```

I'm guessing that the playground has added the dead-code warning attribute since the example was created.

This can be fixed by inserting ```#[allow(dead_code)]``` before the start of the module, but perhaps there's a better way?

**Comment by fmoko** [comment]
Thanks for your report! We don't actively maintain the web exercises anymore, but you're free to make a pull request fixing it!
