### ISSUE TITLE
[Typo]: Should it be "then" or "than"?

### ISSUE THREAD

**Issue by Sowed** [rust-lang/rustlings#455]
Hello Rustaceans. This might be a little bit trivial, but spent more than a healthy amount of time debating this with a colleague 🦀and I thought it would be best addressed here.

From the hint here...
> https://github.com/rust-lang/rustlings/blob/d35592702476f8a7e96287afb8616fe9b97e628b/info.toml#L67
```bash
Constants are always immutable and they are declared with keyword 'const' rather
then keyword 'let'.
```
I am wondering if the **`then`** should be a **`than`**, as it makes more grammatical sense in this context.
```bash
Constants are always immutable and they are declared with keyword 'const' rather
than keyword 'let'.

```

**Comment by jrvidal** [comment]
That loos like a typo indeed. Care to send a PR? :smiley:

**Comment by jrvidal** [comment]
I think the PR was to the wrong repo?

**Comment by Sowed** [comment]
@jrvidal, really, I thought I PRed into *rustlang/rustlings* 🤔

**Comment by jrvidal** [comment]
That doesn't seem to be the case, your commit is nowhere to be found on the `main` branch of this repo.
