### ISSUE TITLE
Add a section in README for uninstallation

### ISSUE THREAD

**Issue by mattzjack** [rust-lang/rustlings#459]
I believe it is as simple as deleting the folder, but it'd be helpful to have it explicitly spelled out in README (-:

Along the same line, it'd be helpful to clarify that the `rustlings` folder will be installed in the current directory.

I was in `windows\system32` because I needed to run PowerShell as admin to execute one of the commands, and I ended up having rustlings installed there, which is undesirable.

**Comment by eliblaney** [comment]
Rustlings uses cargo to install the package, so uninstalling it is as simple as:

    cargo uninstall rustlings

Once you've done that, you can also delete the "rustlings/" folder that contains the code. It wouldn't be a bad idea to add these two steps to the README.
