### ISSUE TITLE
How to update Rustling without losing progress?

### ISSUE THREAD

**Issue by afonsolage** [rust-lang/rustlings#463]
I'm using Rustling 3.0 and want to update to newer version 4.0. But there is a way of doing so without losing all my progress so far?

**Comment by crd477** [comment]
Here's what I've done after pulling in the latest (**warning** - it might be manually intensive!):
```
git switch solutions-3.0.0   # this my working branch of solutions
git checkout -b solutions-4.0.0
git rebase -i tags/4.0.0
```
and then plow through the conflicts until the rebase is done.

**Comment by fmoko** [comment]
Not really - you could manually copy over the completed exercises from your old checkout into your new, as an idea.

**Comment by AbdouSeck** [comment]
Just going to add that if you have not committed any of the solutions (with `git add` and `git commit`), you can `stash` your changes and `checkout` the `4.0.0` tag and then finally `pop` the changes from the stash. Something like the following:
```
git fetch # Fetch the latest tag
git stash
git checkout tags/4.0.0
git stash pop
```
Again, this would only work if you did not add and commit the changes from your solutions.

Thank you!

Abdou

**Comment by afonsolage** [comment]
Thanks! using `git stash` worked!
