### ISSUE TITLE
`rustlings watch` fails silently

### ISSUE THREAD

**Issue by jounathaen** [rust-lang/rustlings#472]
Hi,
I can't get rustlings to work correctly. If I run `rustlings watch`, the program fails silently.
Apparently the problem is, that https://github.com/rust-lang/rustlings/blob/523d18b873a319f7c09262f44bd40e2fab1830e5/src/main.rs#L174 fails on my system (Fedora 32, nothing special AFAIK) and this error only handled with an `is_ok()` in https://github.com/rust-lang/rustlings/blob/523d18b873a319f7c09262f44bd40e2fab1830e5/src/main.rs#L122 
which then fails silently.

The error of the failing `watcher.watch(/*...*/)` is  `Io(Os { code: 28, kind: Other, message: "No space left on device" })'` which is most likely a bug in _notify_ as there are hundreds of GB free on the disk. However, I think the error message should at least be propagated and printed to the command line.

Cheers!

**Comment by jounathaen** [comment]
The problem lies apparently in the inotify watch limit. All of them were occupied (by my languageclient). So this is not a bug of rustlings. Only the lack of an error message is

**Comment by victordeleau** [comment]
imo I think the auto refresh should be replaced with a manual refresh (press enter refreshes by default for example), and that for 3 reasons:
1- People (like me) might get the issue described here (which I solved by increasing the inotify watch limit of my OS). But we can't expect people to tweak their OS like that to be able to use **rustlings**.
2- It is bothering when the **rustlings watch** does its thing without us having a say. Sometimes it is not exactly clear if the error displayed is related to the current exercise or the next one if some modifications made the tests pass. We might also want to read the error again even though we edited the code. That's especially true if the shell running **rustlings watch** is not in sight of the editor.
3- Pressing enter to refresh is a no-brainer that takes no time.

**Comment by seeplusplus** [comment]
Looks like this issue may have a resolution soon.

https://github.com/notify-rs/notify/issues/266

**Comment by jyn514** [comment]
@seeplusplus that issue is just about the error message, there will still be an error either way. The issue here is that `rustlings` is ignoring the error, which `notify` can't do anything about.

**Comment by jounathaen** [comment]
By the way, if somebody want's to fix this issue. It is probably very easy. The code just has to be changed to something like:
```rust
if matches.subcommand_matches("watch").is_some() {
     if let Err(e) = watch(&exercises, verbose) {
        println!("Error: Could not watch your progess. Error message was {:?}", e);
        println!("Most likely you run out of disk space or you 'inotify limit' is reached");
        std::process::exit(1);
    }
```
I just don't have time to test this properly...

**Comment by seeplusplus** [comment]
> @seeplusplus that issue is just about the error message, there will still be an error either way. The issue here is that `rustlings` is ignoring the error, which `notify` can't do anything about.

True. I guess I mean it's solved inasmuch as it responds with a "more correct" error. 

I'll try my hand at adding @jounathaen's code and testing it to see if we can resolve this issue.

**Comment by seeplusplus** [comment]
> I just don't have time to test this properly...

For the sake of correctness, what kind of testing would you recommend? I'm not super familiar with testing in Rust (is there some integration test that could be written to test this?). I did test that this gives us the behavior that we want (I dropped the max_user_watches to 256 on my machine and ran "rustlings watch").

**Comment by jounathaen** [comment]
That's exactly what I imagined as test.
