### ISSUE TITLE
generics3: Provide Grading Scale?

### ISSUE THREAD

**Issue by AndrooFrowns** [rust-lang/rustlings#480]
While it's not technically required to implement the trait for the purpose of passing the tests, the instructions seem to imply familiarity with the 1.0 - > 5.5 grading scale.  For many (myself included) this may not be true.

Would it be worth either changing to an exercise that doesn't rely on external knowledge, or to add in the information required to fully implement the grade scale?

**Comment by fmoko** [comment]
@AndrewFrauens Yes! Good idea.

**Comment by VuiMuich** [comment]
I totally agree, that the description and the hint (see #625) is kind of vague and possibly misleading.
But you actually don't need information on how the different grading systems work, you simply can change the `f32` of `Gary Plotter's` grade to a `str` to pass, so the description could simple mention this. (And the hint should probably loose the reference to implement a trait).

**Comment by keldonin** [comment]
Although I can agree with @VuiMuich that you could adapt the exercise, the source file assumes that everyone is used with the US grade system, and may present a challenge for people learning Rust who have now to cope with/guess a "foreign" grading system; this is probably diverting from the intent of the project. The least that could be done is to document within the source code what is the mapping between alphabetic grades and numerical ones. Or refer to an external resource (Wikipedia?)

**Comment by mo8it** [comment]
Closing because the exercise (now `quiz3`) has been improved and the knowledge about the grading system is not required.
