### ISSUE TITLE
The solution to exercises/enums/enums3.rs solution is not clear because it needs functionality not yet described in the course.

### ISSUE THREAD

**Issue by ricjhill** [rust-lang/rustlings#481]
Its not clear to me if you need to use a match statement so that the match arm selected will set the values of  the state struct using new values in the message.. this is not described in the enum readmes  /main/exercises/enums

 ```
   fn process(&mut self, message: Message) {
        // TODO: create a match expression to process the different message variants
    }
}
```

**Comment by oaigudmundsson** [comment]
Hello @ricjhill,

i just finished this ex and in the readme.md you can see this 
- [Pattern syntax](https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html)

Scroll down a bit and you'll find info about Destructuring Enums

https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#destructuring-enums

....And from there, i could figure it out the issue


Cheers

**Comment by ricjhill** [comment]
Yes that   helped a lot thanks. Along with this
https://doc.rust-lang.org/book/ch05-03-method-syntax.html?highlight=self#method-syntax

**Comment by betoharres** [comment]
it would be nice to have the match expressions explained before this exercise :)

**Comment by ricjhill** [comment]
sorry  I left this open so long.
