### ISSUE TITLE
'rustlings watch' errors out

### ISSUE THREAD

**Issue by MintCollie** [rust-lang/rustlings#495]
Hello, I am trying to use rustlings to learn rust. 
I have tried to follow along with the instructions on both my machine and repl.it but both seem to error out the same way.
after running ```rustlings watch```  I get the error 

```

! Compiling of exercises/variables/variables1.rs failed! Please try again. Here's the output:
error[E0425]: cannot find value `x` in this scope
  --> exercises/variables/variables1.rs:12:5
   |
12 |     x = 5;
   |     ^ not found in this scope

error[E0425]: cannot find value `x` in this scope
  --> exercises/variables/variables1.rs:13:36
   |
13 |     println!("x has the value {}", x);
   |                                    ^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.

Type 'hint' to get help or 'clear' to clear the screen
```

**Comment by danwilhelm** [comment]
Hey! This is how rustlings is intended to work. You progress through the exercises by fixing errors and making tests pass. To start, open `exercises/variables/variables1.rs` in a text editor and try to fix the variable declaration!

A few hints:
- It is typically helpful to read the corresponding section(s) in [The Rust Book](https://doc.rust-lang.org/book/) before doing the exercises. The relevant sections are listed in the README.md file in each exercises directory, e.g. in this case [here](https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html).
- If you still get stuck, to get a hint you can type `hint`. 
- If Rust gives you an error message, in another terminal window you can ask Rust to clarify it, e.g. `rustc --explain E0425`.

**Comment by MintCollie** [comment]
> Hey! This is how rustlings is intended to work. You progress through the exercises by fixing errors and making tests pass. To start, open `exercises/variables/variables1.rs` in a text editor and try to fix the variable declaration!
> 
> A few hints:
> 
>     * It is typically helpful to read the corresponding section(s) in [The Rust Book](https://doc.rust-lang.org/book/) before doing the exercises. The relevant sections are listed in the README.md file in each exercises directory, e.g. in this case [here](https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html).
> 
>     * If you still get stuck, to get a hint you can type `hint`.
> 
>     * If Rust gives you an error message, in another terminal window you can ask Rust to clarify it, e.g. `rustc --explain E0425`.

Ah ok! I didnt quite get that initially, thank you for pointing it out!
I will close this as there is no error.
