### ISSUE TITLE
quiz2 should have ??? markers in case student is reading too fast

### ISSUE THREAD

**Issue by riking** [rust-lang/rustlings#496]
I was slightly tripped up by quiz2 because I initially saw a bunch of string-ish things in tuples not being used.

I think this patch would help a lot:

```
-    ("blue");
+    ???("blue");
-    ("red".to_string());
+    ???("red".to_string());
...
```

making it obvious even in a comments-removed view what the desired solve action is. (The initial compiler error suggests that I need to add a type hint to `.into()`; I slowed down and read the comments because a "quiz" couldn't possibly be that simple.)

**Comment by Ant0wan** [comment]
Sounds like a great idea, making it easier to read it at first.
