### ISSUE TITLE
Error: Rust does not seem to be installed.

### ISSUE THREAD

**Issue by MonkeyToiletLadder** [rust-lang/rustlings#514]
Ive installed rust using the link it provides, but after installation i still get this error.  What could be the issue?  Why cant it find my rust?

**Comment by MonkeyToiletLadder** [comment]
rustc --version and cargo --version both return valid answers.

**Comment by calvinbrown085** [comment]
@MonkeyToiletLadder Would you mind copy/pasting the error you're getting here? And possibly what `rustc --version` and cargo --version` return?

**Comment by rouilleux** [comment]
I'm getting a similar error even though rustc and cargo are installed. 

```
 We cannot find `rustc`.
 Try running `rustc --version` to diagnose your problem.
 For instructions on how to install Rust, check the README.
 
 ❯ rustc --version
 rustc 1.47.0 (18bf6b4f0 2020-10-07)
 
 ❯ cargo --version
 cargo 1.47.0 (f3c7e066a 2020-08-28)
```

**Comment by jrvidal** [comment]
@rouilleux Would you be able to try again, but installing `rustlings` from [this branch](https://github.com/jrvidal/rustlings/tree/rustc-exists)?

Also, what OS are you using?

**Comment by rouilleux** [comment]
Debian, 4.19.0-11-amd64

`Reported error: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

Seems to ignore that my rust installation location is in my path. Where is Rustlings checking?

**Comment by jrvidal** [comment]
That's strange... We perform a dry run of the same procedure that rustlings will use to run your exercises, `Command::new(...).spawn()`, which is the standard way to launch a command... :thinking: 

Are you familiar with strace? I'd be curious to see the ouptut of `strace -f your/path/to/rustlings`. Or the even more verbose `strace -f --no-abbrev -s 200 your/path/to/rustlings`. (:warning: but be cautious, the output might contain sensitive information)

**Comment by rouilleux** [comment]
So the problem only occurs when running directly from the rustlings binary. 

Seems that I may have competing Rust installs which are causing a problem. Everything is fine if I launch with `cargo run` command or if I run the binary by specifying the toolchain with `rustup run <toolchain-name> rustlings`. I'm going to clean everything up and re-install Rust from rustup.

**Comment by Shadowblitz16** [comment]
I am getting this error too after installing curl, git, rust and trying to install the rustlings course.
I even get it saying `Rust is installed now. Great!` after installing rust

I am using kubuntu 20.10

**Comment by Shadowblitz16** [comment]
make sure you restart your computer afterwards >.<

**Comment by suryapandian** [comment]
@MonkeyToiletLadder  and @rouilleux I hope this issue got resolved.

If so we could probably close this issue.

Thanks
