### ISSUE TITLE
Function2 some abstraction leak in teaching curve due to compiler message

### ISSUE THREAD

**Issue by darnuria** [rust-lang/rustlings#539]
Hello, I used rustlings with student this week and I found (and they found it too) that the compiler error in function2 is a little bit complicated as of rustc version 1.46.0 (04488afe3 2020-08-24).

The help and error message give a looooot of information related to rust pre-2018 edition `deprecated annonymous param` and `self` it's great for a seasoned Rustacean but for a beginner like a bachelor 2 student in computer science maybe it's too much.

So I open this issue as a place to possibly think about writing an other erroneous code who do not trigger all this advises but only advises about giving correctly a parameter to `call_me` function.

## Actual code and error + suggestion

```rust
! Compiling of exercises/functions/functions2.rs failed! Please try again. Here's the output:
error: expected one of `:`, `@`, or `|`, found `)`
  --> exercises/functions/functions2.rs:10:15
   |
10 | fn call_me(num) {
   |               ^ expected one of `:`, `@`, or `|`
   |
   = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
help: if this is a `self` type, give it a parameter name
   |
10 | fn call_me(self: num) {
   |            ^^^^^^^^^
help: if this is a parameter name, give it a type
   |
10 | fn call_me(num: TypeName) {
   |            ^^^^^^^^^^^^^
help: if this is a type, explicitly ignore the parameter name
   |
10 | fn call_me(_: num) {
   |            ^^^^^^

error: aborting due to previous error
```

## Suggestion 1 : change signature from num to num:

```diff
-fn call_me(num) {
+fn call_me(num: ) {
```

Triggers:

```rust
! Compiling of exercises/functions/functions2.rs failed! Please try again. Here's the output:
error: expected type, found `)`
  --> exercises/functions/functions2.rs:10:16
   |
10 | fn call_me(num:) {
   |                ^ expected type

error[E0425]: cannot find value `num` in this scope
  --> exercises/functions/functions2.rs:11:17
   |
11 |     for i in 0..num {
   |                 ^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
```

## Suggestion 2 changing `num` to `???` gives:

```diff
-fn call_me(num) {
+fn call_me(???) {
```

```rust
! Compiling of exercises/functions/functions2.rs failed! Please try again. Here's the output:
error: expected parameter name, found `?`
  --> exercises/functions/functions2.rs:10:12
   |
10 | fn call_me(???) {
   |            ^ expected parameter name

error[E0425]: cannot find value `num` in this scope
  --> exercises/functions/functions2.rs:11:17
   |
11 |     for i in 0..num {
   |                 ^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
```

Thanks for reading! After the discussion settled to a common point I can do a PR. :)

**Comment by darnuria** [comment]
Whoups I am sorry I resend the same issue because I forgot this one. :x so I closed: #547.

**Comment by AnnikaCodes** [comment]
I think that ??? gives help that's more conducive to learning as well as being more consistent.

**Comment by darnuria** [comment]
`???` can lead to just `num`, I prefers `num:` because it push into the right into the point "writing those types in functions signatures". But it's not a strong feeling just my own idea. :)

Would be happy to change to `???` if it's ok for everybody.

**Comment by AbdouSeck** [comment]
@darnuria I agree that `num:` would give a better error reporting. The error shows exactly what's missing from the function declaration. There is also an additional error  reported concerning `num` not being in scope. But I think that can very easily be linked to the fact that the data type is missing.
Please feel free to submit a PR whenever possible and link it to the issue.

Thanks,
Abdou

**Comment by darnuria** [comment]
> Please feel free to submit a PR *whenever possible* and link it to the issue.

Took your request very seriously: ;)
https://github.com/rust-lang/rustlings/pull/605

**Comment by AbdouSeck** [comment]
@darnuria of course! Thanks for bringing this up.

Abdou
