### ISSUE TITLE
rustlings watch error after first install OSX

### ISSUE THREAD

**Issue by hulleyrob** [rust-lang/rustlings#544]
`Compiling of exercises/variables/variables1.rs failed! Please try again. Here's the output:
error[E0425]: cannot find value `x` in this scope
  --> exercises/variables/variables1.rs:12:5
   |
12 |     x = 5;
   |     ^ not found in this scope

error[E0425]: cannot find value `x` in this scope
  --> exercises/variables/variables1.rs:13:36
   |
13 |     println!("x has the value {}", x);
   |                                    ^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.`

As this is my first venture into rust i have no idea what to do.

**Comment by crd477** [comment]
See: https://github.com/rust-lang/rustlings/issues/495
Good luck!

**Comment by hulleyrob** [comment]
Ah yeah that wasnt very clear !

Thanks
