### ISSUE TITLE
/exercises/threads/threads1.rs compile fail

### ISSUE THREAD

**Issue by DrYaling** [rust-lang/rustlings#567]
Arc DerefMut between thread is not safe.
Maybe we should change status to
 let status = Arc::new(Mutex::new(JobStatus { jobs_completed: 0 }));

**Comment by AbdouSeck** [comment]
Hi @DrYaling the point of the exercise is to have you pick the right data types so that the exercise can compile and run. The exercise, by default, will not compile. Your changes should make it compile.

Please let us know if you have any other question or suggestion.

Thanks,
Abdou
