### ISSUE TITLE
Ability to list the names of all available exercises for searching/debugging purposes

### ISSUE THREAD

**Issue by apatniv** [rust-lang/rustlings#576]
Currently, there doesn’t seem to any option to get the list of all exercises names. In my personal opinion, it would to useful to provide this feature for searching and debugging purposes.   This could help in finding out all exercises for a particular topic and their exact names. Also, users can debug if they end up accidentally running a wrong exercise name.

```bash
 > rustlings run if
No exercise found for your given name!
```

One way to solve the problem is to add a new subcommand say “list”, that will list all exercise names. This will help users to do the following things: 

- Find out all possible exercises

- Filter based on topics 
```bash 
rustlings list | grep “variable” 
# or
 rustings list | rg “if” 
```
 
Alternative, is that user should know about **`info.toml`** structure and look into name property under exercises. 

Let me if you think this is valuable addition and I will more than glad to make a pull request.

Sorry if this has already been asked, but I couldn't find it.

**Comment by seeplusplus** [comment]
You can find a list of available exercises in the info.toml file in the rustlings directory. 

If we want to include this as a feature in rustlings, I've written up a quick implementation here:

https://github.com/seeplusplus/rustlings/commit/3a2cb4fd49fff08cba9d871e548e37591d650301

**Comment by apatniv** [comment]
@seeplusplus Yes you are correct. The information is present in info.toml as I mentioned earlier.

**Comment by seeplusplus** [comment]
Haha my bad, I totally didn't see that, apologies 😅
