### ISSUE TITLE
tests fail with panic 

### ISSUE THREAD

**Issue by ecausarano** [rust-lang/rustlings#577]
Hi,

running rustlings watch causes all exercises with a test to fail with no output
```
⚠️  Testing of exercises/if/if1.rs failed! Please try again. Here's the output:
```
Running with `cargo test' produces the following output:
```
---- exercise::test::test_exercise_with_output stdout ----
thread 'exercise::test::test_exercise_with_output' panicked at 'called `Result::unwrap()` on an `Err` value: ExerciseOutput { stdout: "", stderr: "error: Unrecognized option: \'show-output\'\n" }', src/libcore/result.rs:1084:5
```
```
rustc --version
rustc 1.38.0 (625451e37 2019-09-23)
```
```
rustlings --version
rustlings 4.1.0
```
on macOS Catalina 10.15.7 (19H2)

**Comment by seeplusplus** [comment]
This looks to be due to the fact that show-output was introduced in rust 1.39.0:
https://github.com/rust-lang/rust/pull/62600

**Comment by ecausarano** [comment]
Oh, that's odd... despite updating rust from brew it still reports 'rustc 1.38.0 (625451e37 2019-09-23)'.
I suspect I must have installed rust from a standalone package some time ago.

Perhaps rustlings could add a warning (or error-out) on an old enough version?
