### ISSUE TITLE
error: could not compile `cfg-if`

### ISSUE THREAD

**Issue by jonathan-s** [rust-lang/rustlings#593]
Using 
Elize:oss jonathan$ rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)

Elize:oss jonathan$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/jonathan/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)

**Comment by jrvidal** [comment]
hi @jonathan-s could you provide the detailed error log?

**Comment by jonathan-s** [comment]
I completely removed rust using rustup and then re-installed it again, and that seems to have solved the problem.
