### ISSUE TITLE
rustlings verify is running sporadically .

### ISSUE THREAD

**Issue by ravibajpai001** [rust-lang/rustlings#603]
Most of the time when I am running rustlings verify I am getting link error with following message . 
cannot open file '.\temp_24536_ThreadId1'
I am running it on windows 10 machine.
I can see so many tmp files in the directory in which I am running .

**Comment by AbdouSeck** [comment]
Hi @ravibajpai001, have you seen the reported problem in #248? It does seem like the sporadic nature of the program you're reporting might have to do with an anti-virus program blocking _some_ of the compiled exercises from running. It may also have to do with a lack of `Administrator` access, but that would not have been sporadic.

The fix mentioned in #248 is to somehow find a way to make your anti-virus program be aware of the `rustlings` executable. This should normally let it know it's safe to run the compiled exercises. Can you please try that and let us know what you find?

Thanks,
Abdou

**Comment by ravibajpai001** [comment]
I checked there is no problem with AntiVirus. I am getting following error 

 Successfully ran exercises/variables/variables1.rs!
✓ Successfully ran exercises/variables/variables2.rs!
✓ Successfully ran exercises/variables/variables3.rs!
! Compiling of exercises/variables/variables4.rs failed! Please try again. Here's the output:
error: linking with `link.exe` failed: exit code: 1104
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.0.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.1.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.2.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.3.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.4.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.5.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.6.rcgu.o"
".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.7.rcgu.o" "/OUT:./temp_17244_ThreadId1" ".\\temp_17244_ThreadId1.2sdmqtm61l4rd3r2.rcgu.o"
"/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-f771f8d0374ceeb1.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-9049f341d2774a65.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-6a47dea777db971c.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-a3b06009982e3d9c.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-ebb710aea302de49.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-4304b0c1525af3c3.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-c70f620fc91130c5.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-3b06f844280b3802.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-86edfc7ab798fc86.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-3aa1c50c964075c2.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-3ec787c945bbba26.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-937aede5bfe8081e.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1104: cannot open file '.\temp_17244_ThreadId1'
  
  While If I run single execrice.there I am facing no issue.
  
rustlings run variables4
Number 0

✓ Successfully ran exercises/variables/variables4.rs

**Comment by ravibajpai001** [comment]
I checked there is no issue with AntiVirus or permission . 
 Successfully ran exercises/variables/variables1.rs!
✓ Successfully ran exercises/variables/variables2.rs!
✓ Successfully ran exercises/variables/variables3.rs!
! **Compiling of exercises/variables/variables4.rs failed**! Please try again. Here's the output:
error: linking with `link.exe` failed: exit code: 1104
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.0.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.1.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.2.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.3.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.4.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.5.rcgu.o" ".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.6.rcgu.o"
".\\temp_17244_ThreadId1.variables4.7rcbfp3g-cgu.7.rcgu.o" "/OUT:./temp_17244_ThreadId1" ".\\temp_17244_ThreadId1.2sdmqtm61l4rd3r2.rcgu.o"
"/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-f771f8d0374ceeb1.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-9049f341d2774a65.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-6a47dea777db971c.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-a3b06009982e3d9c.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-ebb710aea302de49.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-4304b0c1525af3c3.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-c70f620fc91130c5.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-3b06f844280b3802.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-86edfc7ab798fc86.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-3aa1c50c964075c2.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-3ec787c945bbba26.rlib" "C:\\Users\\UserName\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-937aede5bfe8081e.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1104: cannot open file '.\temp_17244_ThreadId1'
  
I am able to run single excerise properly . 
C:\Users\RaviB\Documents\rust_test\rustlings>rustlings run variables4
Number 0

✓ Successfully ran exercises/variables/variables4.rs

**Comment by AbdouSeck** [comment]
Hi @ravibajpai001, thanks for sharing the error message. This is a linker error, unlike the usual `Permission Error` that we've seen on Windows machines so far. [The documentation for this specific linker error](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1104?view=msvc-160) highlights two main causes for this: the compiled binary is still running (or is being debugged) and an anti-virus program blocking the compiled exercises.

So, I have the following questions:

1.
> I checked there is no issue with AntiVirus or permission
When you say you checked, how did you check? How did you confirm that an anti-virus program was not blocking the linking from happening?
2. If you run the `verify` command multiple times, is `variables4.rs` always the one that fails to link?

Thanks,
Abdou

**Comment by ravibajpai001** [comment]
Thanks @AbdouSeck.
Please find my answers below regrding your queries .

1. As mentioned by some articles to add exclusion in Windows defender . there is no such option is coming I think because McAfee is installed in my system for security.  I checked McAfee logs for any blocking and didn't find anything for rustlings/linking. Is there anything else which I can try for this part .  

2. No It is not always for variable4.rs . if I takse some pause and run it again . error comes for different excercise.

**Comment by AbdouSeck** [comment]
Hi @ravibajpai001, thanks for the answers. I am still sort of convinced that your anti-virus scanner is blocking some of the compiled binaries from running. Is there any way to include the `rustlings` folder from the list of folders that McAfee scans?
A quick Google search on how to exclude folders with McAfee returned quite a few results. One of those was [this documentation link](https://download.mcafee.com/products/webhelp/5/1033/index.html#GUID-BA648B78-244A-47F1-8AD6-4A57BA8955BC.html) that talks about adding a specific folder to an exclusion list. It does look old tho. In any case, can you try adding the entire `rustlings` directory to this exclusion list?

Thanks,
Abdou

**Comment by ravibajpai001** [comment]
@AbdouSeck Thank you so much!!
After I added Rustlings folder in exlusion for quick scan settings in McAfee. Isssue got fixed .

**Comment by AbdouSeck** [comment]
Wonderful! I am glad that ended up fixing the problem. Thanks!

**Comment by jamesgecko** [comment]
I had my rustlings folder in Dropbox and consistently experienced this issue until I moved it elsewhere.
