### ISSUE TITLE
rustlings watch gives a permission error on Windows 10 

### ISSUE THREAD

**Issue by RoelofWobben** [rust-lang/rustlings#604]
Hello, 

I installed rustlings on windows 10 according to the manual.
But every time I do `rustlings watch` I see this error 👍 

⠂ Running exercises/variables/variables1.rs...
thread 'main' panicked at 'Failed to run 'run' command: Os { code: 5, kind: PermissionDenied, message: "Toegang geweigerd." }', src\exercise.rs:180:14

**Comment by AbdouSeck** [comment]
Hi @RoelofWobben, thanks for reporting this. The error message does indicate that the `rustlings` program does not have enough permission to compile and run the exercises in the directory where the repository is saved.
Looking at the error message only, there are 2 reasons why this may have happened:

1. You saved the `rustlings` repository in a folder that requires `Administrator` access to write files, but you did not open `powershell` or `cmd.exe` as an `Administrator`.

2. Or, you cloned the `rustlings` repository while logged in as `Administrator`, but you are now using it as a normal user.

Either way, the quickest fix for you would be to open your terminal application (`powershell` or `cmd.exe`) as `Administrator` and run the application again. However, the better fix would be to install `rustlings` without any `Administrator` access, so you can invoke it without needing to open your terminal as `Administrator`.

Please give the above recommendation a try and let us know if you have any additional questions.

Thank you,
Abdou

**Comment by RoelofWobben** [comment]
Thanks 

Did the install again as user and foind out thatI need to tell my virusscanner that the directory where I  saved rustlings must be excluded and then everything worked fine

**Comment by AbdouSeck** [comment]
Wonderful. Thanks for reporting your findings. This is probably the problem raised by issue #603.

In any case, I would not object to a note about this being added to the `README.md` of the repository. If you're up for it, please feel free to submit a pull request containing some text warning Windows users that they may need to exclude the rustlings folder from the folders scanned by their anti-virus programs.

Thank you!
Abdou
