### ISSUE TITLE
Reference to copy on Move Semantics exercise?

### ISSUE THREAD

**Issue by gerardmarquina** [rust-lang/rustlings#613]
I was learning rust just this evening with rustlings and I really struggled on move semantics 2 even when reading the hint multiple times. Given that "clone()" is just a [small section](https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html) of the Rust Book there should be a reference to use clone in the hint.

That's my humble opinion.

**Comment by mo8it** [comment]
Fixed in https://github.com/rust-lang/rustlings/commit/47ba4502e0a60bf720e4c70ff27150bba2d18f8c
