### ISSUE TITLE
Less distracting GIF in README / potential trigger

### ISSUE THREAD

**Issue by aeplay** [rust-lang/rustlings#620]
Hi, this looks like a great project, but my first impression was pretty bad:

The GIF on top of the README is incredibly distracting, because of its fast looping and harsh cuts.
And I am not usually sensitive to fast-paced GIFs at all, let alone have photo-sensitive epilepsy!

I'm assuming that this would be really bad for people suffering from this condition, especially since I would not expect fast, flashing content on GitHub of all places.

Given that the GIF sends a cute message, I'd propose to either slow it down significantly, or to just use these two still frames side-by-side

<img width="370" alt="Screen Shot 2021-01-08 at 01 57 45 839" src="https://user-images.githubusercontent.com/1593585/103961665-3e0c5e00-5155-11eb-8a00-70189b90fa78.png">
<img width="370" alt="Screen Shot 2021-01-08 at 01 58 15 186" src="https://user-images.githubusercontent.com/1593585/103961671-41074e80-5155-11eb-862e-9047983c621a.png">

**Comment by fmoko** [comment]
Yeah, I've wanted to remove this GIF for a while now, but never got around to it. Sorry for your bad experience :/

**Comment by fmoko** [comment]
Should be fixed on main.
