### ISSUE TITLE
Add more strict conditions to from_into.rs and from_str.rs

### ISSUE THREAD

**Issue by lntuition** [rust-lang/rustlings#621]
🦀 First, thank you for providing good tutorial to people. I also enjoyed this, too. I found very minor improving point to some exercise. Current `conversions/from_into.rs` and `conversions/from_str.rs` doesn't check tralling commas and the next one. So i propose below improvement.

As-is (from_into.rs)
``` rust
impl From<&str> for Person {
    fn from(s: &str) -> Person {
       // if s = "Mark,20,something" or s = "Mark,20,"
       // is succeed to make Person with mark and 20
    }
}
```

To-be
``` rust
impl From<&str> for Person {
    fn from(s: &str) -> Person {
       // if s = "Mark,20,something" or s = "Mark,20,"
       // is failed to make Person with mark and 20
    }
}
```

Is it intended feature? If the improvement that I suggested looks good, can I work on it? If you answer to my dumb question, i would really appreciate! Thx

**Comment by AbdouSeck** [comment]
Hi @lntuition, thanks for raising this point. This was done on purpose to make sure that the converters worked as long as the required components were present in the given string. But I do realize now that it makes sense to handle strings with more components than expected differently. So, if you'd like to work on adding more unit tests that handle such cases, I would not object to it; in fact, I would welcome it.
Please feel free to reach out if you have any questions.

Thanks!
Abdou

**Comment by lntuition** [comment]
@AbdouSeck Thank you for answering ! I made some PR to add more unit test! Any review is welcome

**Comment by AbdouSeck** [comment]
@lntuition reviewed, approved and merged. Thank you, again.
