### ISSUE TITLE
Feat: Add more detail about list

### ISSUE THREAD

**Issue by swartz-k** [rust-lang/rustlings#624]
Hey, Does show more info about `list` sub command will be better?
Maybe like this.
![image](https://user-images.githubusercontent.com/49771587/104834884-a558a980-58dd-11eb-8706-e1313c2bd7ae.png)

and ends with progress percent.

![image](https://user-images.githubusercontent.com/49771587/104834916-da64fc00-58dd-11eb-9037-587d7345b115.png)

**Comment by fmoko** [comment]
This might be fixed by #599?

**Comment by swartz-k** [comment]
Thanks, Did not find this function while using.

**Comment by fmoko** [comment]
No problem, the feature was just merged in, so it's not available in Rustlings quite yet.
