### ISSUE TITLE
Generics module is badly programmed

### ISSUE THREAD

**Issue by bmarkovic** [rust-lang/rustlings#625]
By "programming" I don't mean programming as in programming languages but as in "setlist", I.e. defining the progression of the curriculum (the issue title might be a clickbait but I doubt it, I'm nothing like that 😁).

Specifically, `generics3.rs` exercise requires knowledge about traits, and the hint even starts with the following sentence: *"To find the best solution to this challenge you're going to need to think back to your knowledge of traits, specifically Trait Bound Syntax"*.

But Generics module come before Traits module in current progression of exercises. I'm assuming this is some reshuffle of rustlings from earlier state where someone simply failed to notice this dependency issue.

So this should be fixed ASAP, as Rust community is supposed to care big deal about preventing data races 😁

Bad jokes aside. I do think that having generics after traits actually makes much more sense even if this wasn't the case., as they are, much like interfaces or subtyping, a less generic (whoops) form of polymorphism than parametric polymorphism.

**Comment by nickChenyx** [comment]
thanks for rust compiler, help me resolve this even not learn traits before.

```
help: consider restricting type parameter `T`
   |
21 | impl<T: std::fmt::Display> ReportCard<T> {
   |       ^^^^^^^^^^^^^^^^^^^
```

**Comment by Zerotask** [comment]
@nickChenyx 
I also stumbled over this problem. I added a help to the corresponding readme: #721
This is a generic constraint / bound to limit the types of T. In that case to types which implement the Display trait.

**Comment by thephet** [comment]
Hi, I came here to say the same. Generics3 is impossible to solve with the knowledge acquired so far reading the rust book. There's nothing in the generics chapter that would help to solve this.

I think this exercise needs to be re-written.

**Comment by codeofdusk** [comment]
I've also run into this (didn't understand the hint and googled it to get here).

**Comment by diannasoreil** [comment]
In `5.0-dev`, I moved this to be a quiz after generics and traits - hopefully that helps.
