### ISSUE TITLE
Possible bug when checking exercises

### ISSUE THREAD

**Issue by siidheesh** [rust-lang/rustlings#638]
I can't say how this happened as it worked fine after re-running `rustlings watch`, but it skipped over `macros/`, `standard_library_types/` and ended at `conversions/from_str.rs`, saying the course was over.

After running it again, it failed at `standard_library_types/box1.rs` as expected, since the program never reached that exercise

**Comment by AbdouSeck** [comment]
@siidheesh thanks for reporting this. It's been fixed by #599 and should be included in the next release. You're more than welcome to fetch the latest `main` branch from this upstream and reinstall `rustlings`. Please let me know if you have any question.

Thanks,
Abdou

**Comment by siidheesh** [comment]
Thanks for the heads up! 😃
