### ISSUE TITLE
Collections exercises run and hint command does not match standard pattern

### ISSUE THREAD

**Issue by arnoldn1** [rust-lang/rustlings#651]
rustc version: rustc 1.49.0 (e1884a8e3 2020-12-29)
rustlings version: rustlings 4.3.0

The README gives the `run` and `hint` commands as:
```bash
rustlings run myExercise1
```
``` bash
rustlings hint myExercise1
```
where `myExercise1` is the exercise file name. This remains true for other exercise groups where the file names do not match their parent directory name e.g., conversions.

However, for the collections exercises the pattern is instead:
`rustlings run collections1` to run `vec1`
`rustlings run collections2` to run `vec2`
`rustlings run collections3` to run `hashmap1`
`rustlings run collections4` to run `hashmap2`

There is a comment in each file that specifies the correct `hint` command but not `run` command. The lack of consistency leads to some confusion.

**Comment by fmoko** [comment]
Yup, I think this has been an inconsistency ever since these exercises came into being, since the folder name is `collections`. A PR renaming the files themselves to `collections1` - `collections4` would be appreciated!

**Comment by lauralindzey** [comment]
@fmoko -- It looks like this Issue could be closed?

**Comment by fmoko** [comment]
@lauralindzey Thanks for the nudge!
