### ISSUE TITLE
"compilation failed" on "rustlings watch"

### ISSUE THREAD

**Issue by lemmy04** [rust-lang/rustlings#657]
I've done the manual installation of rustlings, now when I try to run "rustlings watch" i get some compilation error:

! Compiling of exercises/variables/variables1.rs failed! Please try again. Here's the output:
error[E0425]: cannot find value `x` in this scope
  --> exercises/variables/variables1.rs:12:5
   |
12 |     x = 5;
   |     ^ not found in this scope

Any ideas?

**Comment by RansomTime** [comment]
Hi @lemmy04.

This is actually what's expected to happen. Your goal in the exercises is to get the code to compile. There's a README.md in each directory with a link to the Rust book about the topic (this first one is [How Functions Work](https://doc.rust-lang.org/book/ch03-03-how-functions-work.html)). The rustlings watch command will automatically update whenever you make a change to the file and attempt to re-compile the code. You can also type hint to get a hint on the current exercise.

Hope that helps.

**Comment by lemmy04** [comment]
...so its basically not for people who don't know anything about rust at all...?

**Comment by RansomTime** [comment]
Sorry I gave the wrong link. The book chapter I meant to link to is [Variables and Mutability](https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html)

Reading that section of the book should give you the information you need to do the first set of exercises. The main project's README.md describes doing exercises like this:

----
## Doing exercises

The exercises are sorted by topic and can be found in the subdirectory `rustlings/exercises/<topic>`. For every topic there is an additional README file with some resources to get you started on the topic. We really recommend that you have a look at them before you start.

The task is simple. Most exercises contain an error that keeps them from compiling, and it's up to you to fix it! Some exercises are also run as tests, but rustlings handles them all the same. To run the exercises in the recommended order, execute:

```bash
rustlings watch
```

This will try to verify the completion of every exercise in a predetermined order (what we think is best for newcomers). It will also rerun automatically every time you change a file in the `exercises/` directory. If you want to only run it once, you can use:

```bash
rustlings verify
```

This will do the same as watch, but it'll quit after running.

In case you want to go by your own order, or want to only verify a single exercise, you can run:

```bash
rustlings run myExercise1
```

In case you get stuck, you can run the following command to get a hint for your
exercise:

``` bash
rustlings hint myExercise1
```

---

I think that without reading the book then the exercises won't really make sense. If this doesn't seem to fit with the way you'd like to learn there are links to alternative resources that might be a better fit for you in the README

**Comment by crd477** [comment]
> ...so its basically not for people who don't know anything about rust at all...?

It's **precisely** for people that don't (yet) know anything at all about Rust!  I also recommend the steps that @RansomTime suggested but if you find that you learn better by video, you can find several examples on youtube of people working through the exercises.

Either way, I encourage you not to give up even if you get frustrated.  Rust is a supremely satisfying programming language once you start to get familiar with it.

**Comment by lemmy04** [comment]
> I think that without reading the book then the exercises won't really make sense. If this doesn't seem to fit with the way you'd like to learn there are links to alternative resources that might be a better fit for you in the README

Well, the website that pointed me at the rustlings exercises explicitely said "Rustlings guides you through downloading and setting up the Rust toolchain, and teaches you the basics of reading and writing Rust syntax". From what I understand now, rustlings is more like a series of tests, or exams if you will, to see if you learnt enough from whatever other source you used.

Maybe that website needs fixing: https://www.rust-lang.org/learn
