### ISSUE TITLE
quiz2 compiles before completing the excersice

### ISSUE THREAD

**Issue by VenelinMartinov** [rust-lang/rustlings#662]
rustc 1.50.0 (cb75ad5db 2021-02-10)
rustlings 3.0.0
no additional files in the directory.

The only compile error with the exercise before editing is line 22: `("nice weather".into())`
All the other lines are valid statements which give no error if the user doesn't prepend one of the functions with the exercise intended.
This means that if you do the exercises sequentially and rustlings watch will pass the file after line 22.
A possible solution is to add a non-existent function in front of each statement in main. Something like `string_slice_or_string`?

**Comment by lauralindzey** [comment]
I think that this issue should be closed -- https://github.com/rust-lang/rustlings/commit/101072ab9f8c80b40b8b88cb06cbe38aca2481c5 fixed it.

**Comment by fmoko** [comment]
Thanks!
