### ISSUE TITLE
functions4 - compiles but CLion IDE states 'use of moved value' error

### ISSUE THREAD

**Issue by jmstudyacc** [rust-lang/rustlings#669]
Hi there,

The code for functions4 is below:

```
fn main() {
    let original_price = 51;
    println!("Your sale price is {}", sale_price(original_price));
}

fn sale_price(price: i32) -> i32 {
    if is_even(price) {
        price - 10
    } else {
        price - 3
    }
}

fn is_even(num: i32) -> bool {
    num % 2 == 0
}
```
In CLion with Rust plugins installed 'use of moved value' appears with a red underline on price.

**Comment by jrvidal** [comment]
We don't do anything funny to determine whether something compiles correctly or not, we just run the compiler! So I suspect the bug here is on CLion's side. I'll add that values of type `i32` should never produced "use of moved value" errors.
