### ISSUE TITLE
rustlings watch halts when starting to edit file with emacs

### ISSUE THREAD

**Issue by tanj** [rust-lang/rustlings#673]
When ever I start to edit a file with emacs `rustlings watch` ends with `★ All exercises completed! ★`

`GNU Emacs 27.1 (build 1, x86_64-w64-mingw32)` on `Windows 10 Pro Version 10.0.19042 Build 19042`

### Steps to reproduce:
1. ` % /c/Program\ Files/Emacs/x86_64/bin/runemacs.exe -Q`
2. Run `rustlings watch` in external shell (not  in emacs)
3. Open `rustlings/exercises/variables/variables1.rs`
4. Insert any text (no save needed)
5. `rustlings watch` ends with  `★ All exercises completed! ★`

**Comment by tanj** [comment]
Looks like it is related to this https://stackoverflow.com/questions/5738170/why-does-emacs-create-temporary-symbolic-links-for-modified-files

Seems this is as issue for [npm](https://github.com/npm/cli/issues/1365) as well.

It seems to be fine if the file exists when `rustlings watch` starts. So it must have something to do with the creation of the symlink that causes the program to end.

The solution seems to be to not create lock files by setting `(setq create-lockfiles nil)` in `.emacs` or other init file locations.

I'm not sure if there is a way to handle this in the rustlings app. If you don't feel it's in your scope to fix feel free to close this.

**Comment by jrvidal** [comment]
What's the filename of those symlinks? Do they still have a `.rs` extension by any chance? If that's the case, it would confuse `rustlings watch`.

**Comment by tanj** [comment]
the symlinks named with the file name and prepended with `.#` So `variables1.rs` would create a symlink as `.#variables1.rs`

**Comment by tanj** [comment]
9f61db5db

**Comment by jrvidal** [comment]
Could you please try the latest release? We introduced some changes in https://github.com/rust-lang/rustlings/pull/599 that I think will fix your issue.

**Comment by tanj** [comment]
Oh, I didn't realize you weren't using the master branch and had switched to main. 

I originally installed via the command `curl -L https://git.io/rustlings | bash` which I got from this repo's README.md

that git.io link currently points to `https://raw.githubusercontent.com/rust-lang/rustlings/master/install.sh`


Tested with the head of main 0d894e6ff and the problem is resolved.

Thanks for your help

**Comment by glima** [comment]
This is still happening as of today (version 6.4.0).
