### ISSUE TITLE
Windows install source is 404

### ISSUE THREAD

**Issue by jlkiri** [rust-lang/rustlings#681]
Trying to install WIndows version from PowerShell throws 404. It looks like  https://git.io/install-rustlings-win returns 404. Did the link change?

**Comment by dnsobchuk** [comment]
> Trying to install WIndows version from PowerShell throws 404. It looks like https://git.io/install-rustlings-win returns 404. Did the link change?
i have the same problem. Link don't work too.
You can use https://git.io/rustlings-win from master branch https://github.com/rust-lang/rustlings/tree/master

**Comment by fmoko** [comment]
I'm not sure why it's not working, the new link seems to include an... enter symbol???
<img width="458" alt="image" src="https://user-images.githubusercontent.com/6445316/112112728-2cfcb600-8bb6-11eb-97e8-65d83c682cd9.png">
No idea where this is coming from.

**Comment by fmoko** [comment]
Should (hopefully?) be fixed on `main`
