### ISSUE TITLE
Add Nix (flake) support

### ISSUE THREAD

**Issue by jakeisnt** [rust-lang/rustlings#683]
It would be great to be able to build `rustlings` with nix and have it automatically available in a local shell. This will allow new users to start working on rustlings with nothing but the Nix package manager installed on their system without having to worry about trying to install rustlings.

It also exposes the rustlings program as a flake itself so that it can be imported and used elsewhere.

I've already done this on my fork of the repository, which you can find [here](https://github.com/jakeisnt/rustlings-nix), but as per the contributing guidelines for new features, I'm opening an issue to discuss!

**Comment by RosarioPulella** [comment]
As a nix user, I have to say this would be really nice, in fact I am looking to help do the same thing for the haskellings repo https://github.com/MondayMorningHaskell/haskellings/issues/29.

This work could help me there.
