### ISSUE TITLE
Misnamed function in collections/hashmap2.rs?

### ISSUE THREAD

**Issue by dimitrijekostic** [rust-lang/rustlings#688]
Hello, my impression is that the at_least_five_types_of_fruits() test function on lines 67-72 (in the testing module for collections/hashmap2.rs) has a misleading name, and would be more accurately named exactly_five_types_of_fruits().  Or perhaps the body of the function should be different?

**Comment by Zerotask** [comment]
Hello @dimitrijekostic 
it seems that you mean *collections/hashmap1.rs*. 
**At least** is correct here since the body's assertion is `>= 5`. This means it results in a true if you have 5 or 10 or 500 fruits, everything which is 5 or greater.

**Comment by dimitrijekostic** [comment]
@Zerotask No, I'm referring to collections/hashmap2.rs.  The hashmap exercises have similarly-named methods in them:
collections/hashmap1.rs has at_least_five_fruits()
collections/hashmap2.rs has at_least_five_types_of_fruits()
I'm referring to the latter.  Note that at_least_five_types_of_fruits() contains an `assert!(count_fruit_kinds == 5);` which is not what the name of the method leads you to expect.

**Comment by Zerotask** [comment]
Oh, it seems I was a bit blind. :D You're right.

This is already fixed with https://github.com/rust-lang/rustlings/pull/660
https://github.com/rust-lang/rustlings/blob/7cd635fa847d33716a735ac1673287db54b6c842/exercises/collections/hashmap2.rs#L71

**Comment by dimitrijekostic** [comment]
Very good, I guess I just need to do another pull.  Thanks for looking into it!
