### ISSUE TITLE
Feature: Support Notebook (From Visual Studio Code) 

### ISSUE THREAD

**Issue by nurmohammed840** [rust-lang/rustlings#689]
Learning by example is great,

Visual Studio Code has [Notebook](https://code.visualstudio.com/api/extension-guides/notebook), rustlings can take full advantage of that, It will make learning more enjoyable... 

Spread rust! with rustlings for all rust lovers.
Thanks for all yours hard work...

**Comment by mo8it** [comment]
Thanks for the idea :) But these notebooks require a kernel (just like Jupyter notebooks). There is a [kernel for Rust](https://github.com/evcxr/evcxr), but the experience is rather limited. Such notebooks are not designed for statically compiled programming languages and I don't think that they are a good fit for Rust(lings).
