### ISSUE TITLE
Ambiguous question in exercises/quiz2.rs

### ISSUE THREAD

**Issue by dimitrijekostic** [rust-lang/rustlings#690]
Line 24 of exercises/quiz2.rs asks whether 

`string("nice weather".into())
`
or 

`string_slice("nice weather".into())
`
will compile.  However both of these options compile. (The `string_slice` option is trivial, since "nice weather" is already of type &str.) I suspect this is an oversight, since there is a wrong answer for each of the nine other lines in the quiz.

**Comment by Nagidal** [comment]
I thought this is a nice feature, it gives you one right answer for free. It made me lookup the `into` trait in std library.

**Comment by mo8it** [comment]
I will keep it like this, but this is now explained in the solution in the upcoming version 6.
