### ISSUE TITLE
Add short commands

### ISSUE THREAD

**Issue by Zerotask** [rust-lang/rustlings#726]
In addition to the current commands, there could be some short commands:
- `w`, `watch`
- `r`, `run`
- `h`, `hint`
- `ls`, `list`

*(I wouldn't recommend a `v` for `verify` since this often stands for verbose)*

This would make it a bit easier to use rustlings, especially with known commands like `ls` for listing etc.

**Comment by fmoko** [comment]
We used to support these (in fact, the latest released version does), but they went away with the CLI refactor since `argh` doesn't support command abbreviations. I don't think it's a priority right now.
