### ISSUE TITLE
Variables1: Removing // I AM NOT DONE causes error

### ISSUE THREAD

**Issue by ssi112** [rust-lang/rustlings#752]
This is the first exercise and a simple one at that. Completed the exercise by doing this:

```
// I AM NOT DONE

fn main() {
    let mut x: u32 = 5;
    println!("x has the value {}", x);

    x += x;
    println!("x has the value {}", x);
}
```
And it compiles. Yea!

Once I remove the I am not done comment. It fails!
```
error[E0282]: type annotations needed
 --> exercises/variables/variables2.rs:7:9
  |
7 |     let x;
  |         ^ consider giving `x` a type
```

Considering that I am explicitly giving x a type. It makes no sense to error by removing the comment. _Also, the code compiles outside of the rustlings environment._ The hint does not help in this case.

If this is a bug in Rustlings then I don't have much confidence going forward that it will be able to handle more complex problems. If it is not a bug, then what is wrong with this? `let mut x: u32 = 5;`

Thanks

**Comment by crd477** [comment]
It's telling you that `exercises/variables/variables2.rs` is the one failing to compile.

**Comment by ssi112** [comment]
Dang if it isn't! I guess I have to read the screen closely.
Thanks
