### ISSUE TITLE
Why verify previous ones?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [rust-lang/rustlings#754]
I think there are no reasons to verify previous ones every time.  

I'm asking because my laptop is so slow,   
and I want to verify the current one like  
`rustlings hint primitive_types4`.

**Comment by luceat-lux-vestra** [comment]
I made some changes to the code, and now I can verify only one item at a time.

But I think not good enough to do `pull request`. I mean not good enough to merged into main branch.

I don't know `rust` well yet.

Codes are like this...,
> in main.rs
```rust
            if _subargs.name.is_empty() {
                verify(&exercises, verbose).unwrap_or_else(|_| std::process::exit(1));
            }
            else {
                let exercise = find_exercise(&_subargs.name, &exercises);

                verify_one(exercise, verbose).unwrap_or_else(|_| std::process::exit(1));
            }
```
> in verify.rs
```rust
pub fn verify_one(exercise: &Exercise, verbose: bool) -> Result<(), ()> {
    let compile_result = match exercise.mode {
        Mode::Test => compile_and_test(&exercise, RunMode::Interactive, verbose),
        Mode::Compile => compile_and_run_interactively(&exercise),
        Mode::Clippy => compile_only(&exercise),
    };
    if !compile_result.unwrap_or(false) {
        return Err(());
    }
    Ok(())
}
```

**Comment by alexandrethm** [comment]
Just for reference, it seems the command `run` already does this, e.g. `rustlings run primitive_types4` to only test a single exercise
