### ISSUE TITLE
Occasional character missing in watch output on Windows 10 cmd

### ISSUE THREAD

**Issue by eddyp** [rust-lang/rustlings#765]
I'm getting some weird rendering issues; initially I thought it was some weird sense of humor I was not getting, but it became apparent is not after looking into the sources.

For instance I'm getting this kind of consistent text alterations:

�🎉🎉🎉  The code is compilin! �🎉 🎉🎉
�🎉🎉🎉  The code is compiling, and the tests pas! �🎉 🎉🎉
�🎉🎉🎉  The code is compiling, ad 🎉📎 Clppy 📎📎 is apy! 🎉🎉 🎉🎉

From what I can see they should be something like:
🎉🎉  The code is compiling! 🎉 🎉
🎉🎉  The code is compiling, and the tests pass! 🎉 🎉
🎉🎉  The code is compiling, and 📎 Clippy 📎 is happy! 🎉🎉

See screenshots:

![image](https://user-images.githubusercontent.com/123772/119886399-96dd6700-bf3b-11eb-9d81-4656898864d8.png)

![image](https://user-images.githubusercontent.com/123772/119886358-8cbb6880-bf3b-11eb-9ac4-92a7afa1b13d.png)

![image](https://user-images.githubusercontent.com/123772/119886267-71505d80-bf3b-11eb-85ce-60c2763c4b04.png)

**Comment by mo8it** [comment]
Closing since this looks like a terminal issue. I would recommend using another terminal. Does it also happen in the new Windows terminal?
