### ISSUE TITLE
how do i skip a exercise from testing

### ISSUE THREAD

**Issue by sagnik-chatterjee** [rust-lang/rustlings#774]
I was doing a exercise and was not able to solve it , and so  I decided to do the other ones . But rustling verfiy runs all the exercises sequentially .How do I prevent this and list which questions I want it to verify on ? 
Passing cli args on rsuling verify doesnt seem to work.

**Comment by almir-neto** [comment]
The `rustlings watch` do not can skip exercises but if you want can just check "by hand" use the `run` flag followed by the especific exercise, like this: `rustlings run if1`, that will run your exercise(and tries compile it). If you want the hint to this exercise use `rustlings hint if1` and you will get list of all hints.

**Comment by sagnik-chatterjee** [comment]
Thanks.
