### ISSUE TITLE
[CLI] New Feature Idea: Add "next" to directly run or point to the next exercise.

### ISSUE THREAD

**Issue by jazzplato** [rust-lang/rustlings#783]
Hi,

First of all, I have been using rustlings to learn rust since a few days ago and I totally love it!

During the process of learning, I find myself repeatedly trying to locate which is the very next exercise I need to go for. Since the folders are ordered basically in lexicographical order and it is very different from the learning order of the different modules, I have to use shell scripting like `rustlings list | grep Pending | head -n1` to locate which is the very next one I should go for and use `rustlings run <EXERCISE_NAME>` to check the error messages. It is OK, but it is a bit tedious, and I think it can be improved.

I am wondering if it could be a good idea that users can just run `rustlings run next` to execute the very next exercise and get the error messages right away without manually looking for what is next.

If you guys think it could be a nice feature to add, I will be more than happy to apply what I have learned with rustlings and work on this feature.

Thank!

**Comment by PSSF23** [comment]
This is closed by #785 I believe.

**Comment by jazzplato** [comment]
Yes it is completed and the change has been merged in #785
