### ISSUE TITLE
Consider renaming quiz2 to strings3?

### ISSUE THREAD

**Issue by lauralindzey** [rust-lang/rustlings#797]
I typically expect a "quiz" to be a review of material that I've seen before, perhaps asking me to put it together into a more complicated program.

Instead, quiz2 covered a whole list of new-to-me ways to create strings, and asked whether the result would be a `String` or a `&str`.

**Comment by suryapandian** [comment]
This is valid, I also felt that same.
It would be great, if you could raise a PR with the change that you have suggested and attach it to this issue.

If the repo maintainers feel okay with it then the change could be merged to the main branch.

Thanks

**Comment by mo8it** [comment]
The exercise has been changed since then.
