### ISSUE TITLE
Having trouble with try_from_into excerise

### ISSUE THREAD

**Issue by burtonr** [rust-lang/rustlings#798]
First, rustlings is a great way to get introduced to a lot of the Rust language features, so thank you!

However, I've found myself struggling with the `try_from_into.rs` exercise. Specifically, how to return an error. It sounds trivial, but I can't seem to find the solution. 

The exercise asks to validate that the color values are in the `0..=255` range, and that the slice implementation validates the appropriate length. The trouble I'm having is **how do I return an error?**

I understand the concept of using the `?` to raise the error provided by a crate or module as shown in the `error_handling` exercises. I do not see how to create a generic error though. The tests are only checking for `is_err()`. 

Coming from other languages, I expected to be able to do something similar to:
```
if slice.len() != 3 {
  return Err(Box::new(error::new("failed"));
}
```
Where the boxed error is a general error with a message/description of "failed".

Thank you.

**Comment by m-sean** [comment]
I struggled with this for a while too. The easiest way I found to instantiate a new Box with an error message (String) using `from` like this:
`Box::from(String::from("Error message here"))`

**Comment by burtonr** [comment]
Thank you @m-sean! That does seem to work. 

I had already gone through and implemented a custom error type... The simple solution is often overlooked :smile:
