### ISSUE TITLE
Feature: Add `// SKIP` to skip an exercise from running in watch mode

### ISSUE THREAD

**Issue by sinharaksh1t** [rust-lang/rustlings#802]
The `// I AM NOT DONE` comment in an exercise file pauses the evaluation of that exercise. Similarly, I'd like to propose a new item called `// SKIP` which automatically skips the execution of that file in the `rustlings watch` mode.
This may be helpful to someone who wants to skip working on an exercise and move on to the next one, while also continue to use the fallthrough mechanism provided by the `rustlings watch` command.

This is different from simply removing the `// I AM NOT DONE` comment from an exercise. That's because if a file has compilation errors, `rustlings watch` stops the fallthrough and the user cannot move to the next exercise without first resolving the issues in that file. Having `// SKIP` in this file will automatically skip over this file while in `rustlings watch` mode. and the file will be tested for compilation or runtime errors, and `rustlings watch` will go directly to the the next file in order.

Edit: If this gets accepted, I'd love to open a PR for this. Since I'm a newbie, I'd love to get someone's guidance while working on this. Thanks!

**Comment by codingupastorm** [comment]
In case it's helpful for anyone else in future: You can remove exercises from `info.toml` and they will no longer be tracked by the `watch` command. 

On another device I had completed everything up until quiz2,  so just deleting everything before `# QUIZ 2` helped me

**Comment by mo8it** [comment]
That won't be needed if we implement an [interactive exercises list in a TUI](https://github.com/rust-lang/rustlings/issues/1920)
