### ISSUE TITLE
how can i fix the question of errors6

### ISSUE THREAD

**Issue by tmdhhl** [rust-lang/rustlings#808]
I have no idea on how to solve this problem, can anyone help me? Thanks.

**Comment by suryapandian** [comment]
Hi @tmdhhl 

The Pull requests are usually for updating the rustlings code or document.

You could use `rustlings hint errors6` to get hint or help and follow the documents or suggestions provided there.

Solutions to rustlings are available in Github by those who have solved, you could take a look at how it is solved.
Here is my solution to the problem statement: https://github.com/suryapandian/rustlings/blob/main/exercises/error_handling/errors6.rs


While posting doubts I would recommend you to post the doubt with more details like the solution that you have tried, the error you received etc... so that more people would be able to help.

Here are some resources you could like into:

Newbie references:
https://www.rust-lang.org/learn
https://doc.rust-lang.org/book
github.com/rust-lang/rustlings
https://tourofrust.com/
https://doc.rust-lang.org/stable/rust-by-example/
Books:
https://lborb.github.io/book/
http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/README.html
Discussion forums
https://www.rust-lang.org/community
#rustlang
https://rust-lang.zulipchat.com
https://users.rust-lang.org/
https://discord.com/invite/aVESxV8
https://rust-slack.herokuapp.com/ 


I am closing this PR since this does not have any code change, suggestion or document update.
If you would like to contribute to rustlings, please feel to add changes and reopen the PR or rise a new PR.

Happy coding!

Thanks

**Comment by KennthStailey** [comment]
The best documentation on `map_err` I've found is at
https://docs1.w3cub.com/rust/book/error-handling/

**Comment by dzungtran** [comment]
For another solution, you might use `match` keyword, and does not need to create more function to handle error

```
    // TODO: change this to return an appropriate error instead of panicking
    // when `parse()` returns an error.
    let x: i64 = match s.parse::<i64>() {
        Err(err) => return Err(ParsePosNonzeroError::ParseInt(err)),
        Ok(n) => n
    };
```

**Comment by jbloomAus** [comment]
This worked for me!

> For another solution, you might use `match` keyword, and does not need to create more function to handle error
> 
> ```
>     // TODO: change this to return an appropriate error instead of panicking
>     // when `parse()` returns an error.
>     let x: i64 = match s.parse::<i64>() {
>         Err(err) => return Err(ParsePosNonzeroError::ParseInt(err)),
>         Ok(n) => n
>     };
> ```

This worked for me. Thankyou!

**Comment by Steve-Z** [comment]
As another newbie `rustlings` learner, I had a hard time with this as well. May I suggest that developers consider an "I give up, show me" command (with some explanation of why solution works) and/or a second level hint. `rustlings list` could show where this command was used. I realize this would be a lot of work for volunteer developers so it might not ever happen.

I just figured out errors6 (my solution is a bit different than above although that helped), but it took me a couple of days (not spending entire days on this, of course; I'm not insane :-) My point is that I read various sources to try to understand this and I am not simply looking for an easy shortcut. (I did not try discussion forums, but that is an excellent suggestion from @suryapandian, and probably would have been my next step. Sometimes newbies just get stuck, and ultimately the goal is to learn.

**Comment by Juniokoi** [comment]
To solve it using map_err() you have to indicate the function or use it with a closure:
```rust
fn parse_pos_nonzero(s: &str) -> Result<PositiveNonzeroInteger,ParsePosNonzeroError> {
    let x: i64 = s.parse().map_err(ParsePosNonzeroError::from_parseint)?; pass the function without calling it
    Ok(PositiveNonzeroInteger::new(x).map_err(|err| ParsePosNonzeroError::from_creation(err))?) // or invoke a closure to call the function
}
```

**Comment by reed9999** [comment]
Even though the OP isn't very descriptive, as I write in early 2024, it looks like something's going on that I wouldn't expect in a tutorial. See the first two errors here although I've included the third for completeness. Unless the tutorial is specifically about learning where to import errors from -- and the hint doesn't seem to indicate this -- then it surprises me to have a broken `use`.

I looked at Rust issues #103765 <https://github.com/rust-lang/rust/issues/103765> but it feels like this is beyond the scope of what you're trying to teach beginners.


```

Progress: [###################################>------------------------] 56/96 (58.3 %)                                                                                                                 ⚠️  Compiling of exercises/13_error_handling/errors6.rs failed! Please try again. Here's the output:
error[E0658]: use of unstable library feature 'error_in_core'
  --> exercises/13_error_handling/errors6.rs:15:5
   |
15 | use core::error;
   |     ^^^^^^^^^^^
   |
   = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information

error[E0658]: use of unstable library feature 'error_in_core'
  --> exercises/13_error_handling/errors6.rs:35:69
   |
35 | fn parse_pos_nonzero(s: &str) -> Result<PositiveNonzeroInteger, dyn error::Error> {
   |                                                                     ^^^^^^^^^^^^
   |
   = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information

error[E0277]: the size for values of type `(dyn std::error::Error + 'static)` cannot be known at compilation time
   --> exercises/13_error_handling/errors6.rs:35:34
    |
35  | fn parse_pos_nonzero(s: &str) -> Result<PositiveNonzeroInteger, dyn error::Error> {
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn std::error::Error + 'static)`
```

**Comment by ivandardi** [comment]
> Hi @tmdhhl
> 
> The Issues are usually for reporting issue in rustlings. If you could elaborate on where you are stuck at then we could try and add more details to the problem description or hint.
> 
> You could use `rustlings hint errors6` to get hint or help and follow the documents or suggestions provided there.
> 
> Solutions to rustlings are available in Github by those who have solved, you could take a look at how it is solved. Here is my solution to the problem statement: https://github.com/suryapandian/rustlings/blob/main/exercises/error_handling/errors6.rs
> 
> While posting doubts I would recommend you to post the doubt with more details like the solution that you have tried, the error you received etc... so that more people would be able to help.
> 
> Here are some resources you could like into:
> 
> Newbie references: https://www.rust-lang.org/learn https://doc.rust-lang.org/book https://github.com/rust-lang/rustlings/ https://tourofrust.com/ https://doc.rust-lang.org/stable/rust-by-example/
> 
> Books: https://lborb.github.io/book/ http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/README.html
> 
> Discussion forums https://www.rust-lang.org/community https://rust-lang.zulipchat.com https://users.rust-lang.org/ https://discord.com/invite/aVESxV8 https://rust-slack.herokuapp.com/
> 
> We can close this issue since this does not have details or suggestions. If you would like to contribute to rustlings, please feel to add changes and reopen the issue or rise a new issue.
> 
> Happy coding!
> 
> Thanks

Hello! Do you mind updating your reply with the new link to the Rust Programming Language Community Server? It's discord.gg/rust-lang-community now. Thank you!

**Comment by tatimblin** [comment]
Thanks @junio256 this helped me. Calling out that the last line in your snippet didn't need to be edited.

> Complete the _TODO_ area by creating a `from_parseint` function:
> 
> ```rust
> fn parse_pos_nonzero(s: &str) -> Result<PositiveNonzeroInteger,ParsePosNonzeroError> {
>     let x: i64 = s.parse().map_err(ParsePosNonzeroError::from_parseint)?;
>     PositiveNonzeroInteger::new(x).map_err(ParsePosNonzeroError::from_creation) <-- leave as provided
> }
> ```

**Comment by richard5334** [comment]
> Complete the _TODO_ area by creating a `from_parseint` function:
> 
> impl ParsePosNonzeroError {
>     fn from_creation(err: CreationError) -> ParsePosNonzeroError {
>         ParsePosNonzeroError::Creation(err)
>     }
>     fn from_parseint(err: ParseIntError) -> ParsePosNonzeroError {
>         ParsePosNonzeroError::ParseInt(err)
>     }
> }
> And the `parse_pos_nonzero` part you can use map_err() to indicate the function or use it with a closure:
> 
> fn parse_pos_nonzero(s: &str) -> Result<PositiveNonzeroInteger,ParsePosNonzeroError> {
>     let x: i64 = s.parse().map_err(ParsePosNonzeroError::from_parseint)?; // pass the function without calling it
>     Ok(PositiveNonzeroInteger::new(x).map_err(|err| ParsePosNonzeroError::from_creation(err))?) // or invoke a closure to call the function
> }

Not sure how a beginner should be able to get there. 

It mix too many new concepts all at once: 
1) impl on an enum
2) error enum with error in them (ParsePosNonzeroError of variant Creation contains a CreationError...?)
3) conversion of specific error type into a more generic one
4) .map_err with some functional programing concept
