### ISSUE TITLE
Conversions/as_ref_mut.rs no method named `as_ref` found error

### ISSUE THREAD

**Issue by awareness481** [rust-lang/rustlings#811]
The following code results to an error. As far as I understand, this should be working

```rs
fn byte_counter<T: AsRef<str>>(arg: T) -> usize {
    arg.as_ref().as_bytes().len()
}
```
Everything else in the exercise is unchanged.
```
error[E0599]: no method named `as_ref` found for type parameter `T` in the current scope
   --> exercises/conversions/as_ref_mut.rs:16:9
    |
16  |     arg.as_ref().chars().count()
    |         ^^^^^^ method not found in `T`
    | 
```
Considering [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6a79ae1480cd5f08bc666cdf763bfc75) (thanks #beginners on Rust discord) this looks like an `rustlings` error

Edit: versions
```
rustc 1.54.0 (a178d0322 2021-07-26)
rustlings 4.3.0
Ubuntu 20.04.2 LTS (Xubuntu)
```

**Comment by AbdouSeck** [comment]
That error is not from the function you shared. The function that causes that error is [`char_counter`](https://github.com/rust-lang/rustlings/blob/df25684cb79f8413915e00b5efef29369849cef1/exercises/conversions/as_ref_mut.rs#L15), which counts the number of **characters** in a string-like object. That function is part of the exercise, as well. Solve it in the same way you solved `byte_counter`, and that should take care of the compilation error, at least.

**Comment by awareness481** [comment]
D:
