### ISSUE TITLE
arc1 way too difficult for progression

### ISSUE THREAD

**Issue by quangvdao** [rust-lang/rustlings#813]
Hi,

I'm going through the exercises, and it seems that `arc1.rs` is a bit out of place. It doesn't relate to any other exercises in `standard_library_types`, and the solver probably has to read most of the concurrency chapter before being able to do it. Perhaps a better home for this would be in `threads`, and we could add more exercises about concurrency?

**Comment by seaerchin** [comment]
Hi, i actually ran into the same issue (as i'm using this as a resource to reinforce my rust book reading) - how rustlings works is that it reads from `info.toml` to determine the list of exercises to do and the order; a simple fix for this would be to simply edit the `info.toml` file on the client end but i definitely think that the solution should be 2 fold: 

1. shift box + arc down below `iterators.rs`
2. add a section called Chapter 15 in the `README.md` for smart pointers (the actual chapter in the book that relates to this) + shift the related exercises there

i can make the PR if this seems reasonable!

**Comment by th317erd** [comment]
I agree with all of this. I was cruising through all these exercises and then this one stumped me hard... this was the first one where I NEEDED the hint to proceed.

**Comment by rlpowell** [comment]
Expanding on this: the order in the book is iterators, then box, then concurrency/arc; the toml just needs re-ordering to match.

**Comment by seporterfield** [comment]
I also found this incredibly confusing. I'm gonna make a pull request for this.
