### ISSUE TITLE
`exercises/conversions/as_ref_mut` does not actually touch `AsMut`.

### ISSUE THREAD

**Issue by LeoniePhiline** [rust-lang/rustlings#817]
Hi!

First of all, thanks for making `rustlings`! I had a blast and learnt a lot in a short time. Thank you :)

After solving `exercises/conversions/as_ref_mut.rs` I realized that mutability is not part of the exercise at all.

- Should there be a separate exercise for `AsMut`?
- Should `as_ref_mut` be modified to require mutable references?

**Comment by diannasoreil** [comment]
Added a section for that: https://github.com/rust-lang/rustlings/commit/4bebdb5f02f492081568900b739ad76dc05ea4ef
