### ISSUE TITLE
move_semantics2: mutable and immutable exist same time

### ISSUE THREAD

**Issue by ziyouwa** [rust-lang/rustlings#823]
Rule of Refernces 👍 
At any given time, you can have either one mutable reference or any number of immutable references.

but  this code compile success!  

```
fn main() {
    let mut vec0 = Vec::new();

    // Do not change the following line!
    println!("{} has length {} content `{:?}`", "vec0", vec0.len(), vec0);   // vec0  immutable borrow

    let  vec1 = fill_vec(&mut vec0);   //vec0  mutable borrow   ?!!
    vec1.push(88);

    println!("{} has length {} content `{:?}`", "vec1", vec1.len(), vec1);
}

fn fill_vec(vec: &mut Vec<i32>) -> &mut Vec<i32> {
    // let mut vec = vec.clone();

    vec.push(22);
    vec.push(44);
    vec.push(66);

    vec
}
```

**Comment by FutureHet** [comment]
I want to work on this issue, can you please assign it to me.

**Comment by FutureHet** [comment]
I created a pull request named, updated move_semantics2.rs.
Please check that and merge that...
If there is any update let me know.

**Comment by zachs18** [comment]
> **At any given time**, you can have either one mutable reference or any number of immutable references.

The lifetimes of the two borrows of vec0 mentioned in comments do not overlap (the borrows do not exist at the same time), so the rule of references is not broken.

**Comment by SkiFire13** [comment]
To expand on @zachs18's explanation, borrows are ended as soon as you no longer use them. The first immutable borrow of `vec0` is only used inside the `println!`, so after that there aren't borrows active anymore and you're free to create a mutable borrow of `vec0` when calling `fill_vec`
