### ISSUE TITLE
Consider changing Replit configuration so rustlings can compile

### ISSUE THREAD

**Issue by dxbednarczyk** [rust-lang/rustlings#825]
Replit currently uses 1.44 as it's rustc version which errors out in compiling rustlings, however using a Nix environment in Replit allows you to add add the correct dependencies for compiling and running rustlings, see [this configuration](https://gist.github.com/dbednar230/12366d048dda0d10f10127e0be1686d1).

With this configuration you can compile and use rustlings in Replit regardless of the version it uses in a new Rust repl, although I don't think it properly loads an existing folder of rustlings.

**Comment by CyberAustin** [comment]
The above referenced gist is gone. Is there a copy of this config file somewhere?
