### ISSUE TITLE
Clear feature

### ISSUE THREAD

**Issue by Cesare12** [rust-lang/rustlings#833]
Hello：
 Very very thanks the projects!
 But after build projects, there are a lot of temp files like .pdb, .o.
 So, is it possible have a command feature to clear them all?

**Comment by SwiftSergio** [comment]
I'm also wondering the same thing as I also have a build up of said files.
Thanks

**Comment by jlagneau** [comment]
Wouldn't `cargo clean` do that for you?

**Comment by diannasoreil** [comment]
Those artifacts usually build up in the `target/` folder, which `cargo clean` will delete for you, yes.

**Comment by mo8it** [comment]
`cargo clean` should take care of cleaning, especially after https://github.com/rust-lang/rustlings/issues/1935
