### ISSUE TITLE
Use Docker to work on exercises in isolated environment

### ISSUE THREAD

**Issue by VMois** [rust-lang/rustlings#839]
*Problem*: what if I want to work on rustlings but I do not want to install Rust on my host operating system?

*Solution*: build a rustling Docker image, run it and mount your host directory with all rustlings exercises.

Rustling Dockerfile can be as simple as:

```Dockerfile
FROM rust:1.54.0

WORKDIR /pwd
# image build from your host rustlings folder 
COPY . .

RUN cargo install --force --path .
```

Example:

```bash
$ docker run --rm -v $PWD:/pwd --name rustling -it rustling:1.54.0 bash
$ root@1234:/pwd# rustling verify
```

What do you think? Will it be worth adding a similar Dockerfile (improved probably) and some description on how to use this setup to rustling? Thank you.

**Comment by diannasoriel** [comment]
I'm generally against this, installing Rust is very easy via `rustup`, and so is completely removing it (`rustup self uninstall`). If you need an alternative to doing this via Rust, there's the browser-based methods: https://github.com/rust-lang/rustlings#browser.

If you use Rustlings to learn Rust, it'll ensure you have a complete Rust development environment (minus RLS/rust-analyzer), which is imo an important step for people, and I don't want to automate or minimize that away.

**Comment by VMois** [comment]
Got it. Closing the issue.

BTW, `rustlings` is amazing!
