### ISSUE TITLE
no way to quit `rustlings watch`

### ISSUE THREAD

**Issue by abusch** [rust-lang/rustlings#842]
I ran `rustlings watch` and started working my way through the exercices and wanted to stop for a bit, only to find out there was absolutely no way to quit the process (except by finishing all the exercises...). I tried `C-c`, `C-\`, `C-d`, `quit`, `exit`, ...

It would be handy to add a `quit` command or similar (and maybe a `help` one too).

**Comment by RusimbiP** [comment]
I use CTRL + C and it works

**Comment by abusch** [comment]
hmm, it might be a `fish` shell thing maybe...

**Comment by diannasoriel** [comment]
A quit command would be a good idea, yeah.
