### ISSUE TITLE
The exercise `primitive_types3` pass even if the array is small

### ISSUE THREAD

**Issue by anuk909** [rust-lang/rustlings#845]

**Comment by diannasoreil** [comment]
That's part of the idea behind the exercise!

**Comment by mobergmann** [comment]
> That's part of the idea behind the exercise!

@shadows-withal But why does the comment then state: `// Create an array with at least 100 elements...` when it passes with less then 100 elements?

**Comment by mo8it** [comment]
The current version panics when the array isn't big enough.
