### ISSUE TITLE
Option to disable color output (for running in vim)

### ISSUE THREAD

**Issue by tonijarjour** [rust-lang/rustlings#863]
Hey at the moment running `!rustlings run next` gives output with color codes which will not display properly in vim.
![image](https://user-images.githubusercontent.com/39845673/137605001-23e6945c-1f5c-4e8c-a62c-e3a0d2d32b8e.png)

It would be appreciated if the program could detect it is being run in vim and not color the output (that's how cargo works).
![image](https://user-images.githubusercontent.com/39845673/137605016-e9d3f8d0-6483-40d2-bf7a-09f3af191d94.png)

Thank you

**Comment by mo8it** [comment]
`rustlings run` is not the recommended way of using Rustlings. Just run `rustlings` in a new terminal (pane). It will watch for file changes.

I recommend using [Zellij](https://zellij.dev/screencasts/) when using a terminal editor. I use one myself ([Helix](https://helix-editor.com)).
