### ISSUE TITLE
In watch, can we display the command to compile ? 

### ISSUE THREAD

**Issue by PierreAntoineGuillaume** [rust-lang/rustlings#881]
I am a beginner with the rust toolchain, and when `rustlings watch` (or `rustlings run move_semantics2`) shows me an error :

```shell
 ! Compiling of exercises/move_semantics/move_semantics2.rs failed! Please try again. Here's the output:
error[E0382]: borrow of moved value: `vec0`
  --> exercises/move_semantics/move_semantics2.rs:13:57
   |
8  |     let vec0 = Vec::new();
   |         ---- move occurs because `vec0` has type `Vec<i32>`, which does not implement the `Copy` trait
9  | 
10 |     let mut vec1 = fill_vec(vec0);
   |                             ---- value moved here
...
13 |     println!("{} has length {} content `{:?}`", "vec0", vec0.len(), vec0);
   |                                                         ^^^^^^^^^^ value borrowed here after move

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
```

It doesn't tell me how I could use `cargo` to build and run the file myself.

Can we display the command to compile ?

I think that would help me understand the toolchain more ; though maybe too much info is parasitic in this context.

<sub>I am currently trying to understand how this program works to attempt a pull request</sub>

**Comment by diannasoreil** [comment]
I think telling the user too much here would detract from the learning experience; the way Rustlings compiles these files is by manually invoking the `rustc` compiler and then executing the compiled binary, which is something you don't usually do (you would usually operate within a project structure that Cargo can work with).

For future reference, though, here's how you'd do what `rustlings run <exercise>.rs` does:
```
rustc <path/to/exercise.rs> -o temp
./temp
```

And for testing:
```
rustc --test <path/to/exercise.rs> -o temp
./temp
```
