### ISSUE TITLE
Bash completion proposal

### ISSUE THREAD

**Issue by PierreAntoineGuillaume** [rust-lang/rustlings#886]
I did a small completion function to integrate with bash_completion :

```shell
_rustlings() {
    if ! rustlings >/dev/null; then # rustlings will exit with 1 if we are not in a rustlings directory
        return 0
    fi
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ ${cur} == -* || ${COMP_CWORD} -eq 1 ]] ; then
        # Nothing has been typed yet, only show main commands
        COMPREPLY=( $(compgen -W "verify watch run hint list" -- ${cur}) )
        return 0
    fi

    # there is nothing to complete watch, list or verify with
    if [[ ${prev} == watch || ${prev} == list || ${prev} == verify ]]; then
        return 0
    fi

    # else, complete with the list of exercices.
    mapfile -t exercises < <(rustlings list | awk '$3 ~ /Pending|Done/ { print $1 }')
    COMPREPLY=( $(compgen -W "${exercises[*]}" -- ${cur}) )
}

complete -F _rustlings rustlings

```

I was wondering if I could integrate this script somewhere to provide users with better bash integration.
(The same as `rustup completions bash` cf https://rust-lang.github.io/rustup/installation/index.html#enable-tab-completion-for-bash-fish-zsh-or-powershell )

**Comment by mo8it** [comment]
Thanks for sharing this function. But to be honest I don't think that this is worth it since Rustlings doesn't have many commands.

Also, some people (like me) use other shells like Fish. We would need to add completions for that too and maintain them.
