### ISSUE TITLE
rustlings: command not found ... still

### ISSUE THREAD

**Issue by delphonso** [rust-lang/rustlings#895]
I saw some issues reporting this but they seem to be old and solved. I'm still getting this issue.

Running Manjaro on a Raspberry Pi 4.

Installed rustup via pamac, updated rust, cargo, and rustup through rustup. 
Manually installed rustlings 
`git clone -b 4.6.0 --depth 1 https://github.com/rust-lang/rustlings`
failed the first time to network error (common for me)
```
cd rustlings
cargo install --force --path .
```
performed as if a success.

checked again for updates with rustup - nothing

running 
`rustlings watch`
just gives me 
`bash: rustlings: command not found`

No idea where to go from here. Would love to run through the course the easy way - but if I have to, I can just go through them manually.

**Comment by diannasoreil** [comment]
Sounds to me like Cargo binaries aren't available in your PATH environment variable. Check if `echo $PATH` includes anything with `cargo/bin`, and if not, you're going to have to add that yourself (by the way, I'd recommend sourcing rustup directly from the rustup.rs website and not via a package manager, as the installer also takes care of setting up your PATH for you)

**Comment by delphonso** [comment]
Ah - that was it, thanks for the help. I'll try to track down the maintainer of the package I downloaded and see if they can fix that or at least provide some warning.

**Comment by delphonso** [comment]
Ah - that was it, thanks for the help. I'll try to track down the maintainer of the package I downloaded and see if they can fix that or at least provide some warning.
