### ISSUE TITLE
variables5: shadowing solution should be more prominent

### ISSUE THREAD

**Issue by gavindsouza** [rust-lang/rustlings#909]
I feel Shadowing still isn't prominent enough, even after https://github.com/rust-lang/rustlings/issues/375. I got by this exercise by blindly changing the code to the following:

```diff
// variables5.rs
// Make me compile! Execute the command `rustlings hint variables5` if you want a hint :)

fn main() {
    let number = "T-H-R-E-E"; // don't change this line
    println!("Spell a Number : {}", number);
+    let number1 = 3;
-    number = 3;
+    println!("Number plus two is : {}", number1 + 2);
-    println!("Number plus two is : {}", number + 2);
}
```

It passed and I went on to the next one and thought oh something isn't right. Checked the hints to see there was some talk about "Shadowing" and that I could reuse variables (via [the book's ref](https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html#shadowing)). I think we can give a nudge towards the exercise's objective with a comment `// don't rename this variable`.

```rs
// variables5.rs
// Make me compile! Execute the command `rustlings hint variables5` if you want a hint :)

fn main() {
    let number = "T-H-R-E-E"; // don't change this line
    println!("Spell a Number : {}", number);
    number = 3; // don't rename this variable
    println!("Number plus two is : {}", number + 2);
}
```

**Comment by th317erd** [comment]
I also have a question on `variables5`:

I was thinking "I wonder if creating a shadow variable immediately drops the previous variable?" This would make sense, right? If you shadow a variable name (within the same scope), then you can not access that variable again... so why wouldn't it be dropped immediately?

I wrote the following test:

```rust
// variables5.rs
// Make me compile! Execute the command `rustlings hint variables5` if you want a hint :)

// I AM NOT DONE

#[derive(Debug)]
struct Test {
  x: i32,
}

impl Drop for Test {
  fn drop(&mut self) {
    println!("I have been dropped!");
  }
}

fn main() {
  let number = Test { x: 10 }; // don't change this line
  println!("Spell a Number : {:?}", number);

  let number = 3;
  println!("Number plus two is : {}", number + 2);
}
```

Output:
```
Spell a Number : Test { x: 10 }
Number plus two is : 5
I have been dropped!
```

And it's output shows that the variable is dropped at the END of the `main` scope, not as soon as the shadow variable is created.

I was just wondering, why is this? If you can no longer access the previous variable, then why would it not be immediately dropped? Does anyone have an answer for me?

**Comment by gavindsouza** [comment]
@th317erd Found this thread from 2015: https://github.com/rust-lang/rust/issues/26701. Quite interesting :godmode:

**Comment by th317erd** [comment]
Thank you for the link @gavindsouza ! The discussion over there does make sense. :)
