### ISSUE TITLE
[BUG] functions5 will not compile without //I AM NOT DONE comment present, even if correct code is written.

### ISSUE THREAD

**Issue by shrug2** [rust-lang/rustlings#939]
functions5 will not compile if the //I AM DONE comment is removed even with correct code written. 

functions5 will compile only if the //I AM DONE comment is left in the file, but thereby prevents the user from progressing forward.

![image](https://user-images.githubusercontent.com/96326129/156898735-49e2b235-5713-40bd-a61c-c13b7d336c73.png)

![image](https://user-images.githubusercontent.com/96326129/156898751-c401497d-8eb0-41dc-9bca-e80fc61f09be.png)

**Comment by Mobuos** [comment]
I'm pretty sure that's working as intended. 

Look, he says "Successfully ran exercises/functions/functions5.rs!"
He is complaining at the next exercise you're supposed to do, `if1.rs`. 

When you remove the `//I AM NOT DONE` rustlings checks for the next exercise you should do (if you're following their predetermined order).

**Comment by shrug2** [comment]
Thanks Mobous, you're absolutely right! My mistake.
