### ISSUE TITLE
rustlings wont compile on replit

### ISSUE THREAD

**Issue by nerkn** [rust-lang/rustlings#943]
I updated rust using `cargo update`
then cargo build

    error[E0658]: use of unstable library feature 'renamed_spin_loop'
     --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.9.1/src/spinwait.rs:9:5
      |
    9 | use core::hint::spin_loop;
      |     ^^^^^^^^^^^^^^^^^^^^^
      |
      = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information
    
    error[E0658]: use of unstable library feature 'renamed_spin_loop'
      --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.9.1/src/spinwait.rs:16:9
       |
    16 |         spin_loop()
       |         ^^^^^^^^^
       |
       = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information
    
    error: aborting due to 2 previous errors
    
    For more information about this error, try `rustc --explain E0658`.
    error: could not compile `parking_lot_core`.
    
    To learn more, run the command again with --verbose.
    warning: build failed, waiting for other jobs to finish...
    error: failed to compile `rustlings v4.6.0 (/home/runner/rustlings)`, intermediate artifacts can be found at `/home/runner/rustlings/target`
    
    Caused by:
      build failed
     rustc --version
    rustc 1.44.0 (49cae5576 2020-06-01)****

**Comment by sethupavan12** [comment]
did you edit `Cargo.toml` file?
