### ISSUE TITLE
Changing the test in errors1 feels inconsistent. 

### ISSUE THREAD

**Issue by autotel** [rust-lang/rustlings#951]
In the errors1 test, one is required to update the test function. This is the first time that it happens during the rustlings tutorial, and it feels like an inconsistency. Before this, one generally expects that the tests should supposedly not be changed.

**Comment by Adin9** [comment]
nice

**Comment by diannasoreil** [comment]
Closed by #958 and 76a36dd38594c63b4bd64e655efeb272ccfaf2a4.
