### ISSUE TITLE
'rustlings' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by alpereira7** [rust-lang/rustlings#960]
Hi.
I would like to install rustlings in Windows 10 and so far I managed to follow this [tutorial](https://github.com/rust-lang/rustlings/#windows).

![image](https://user-images.githubusercontent.com/32866310/162205887-ba90b39f-9b41-4948-b712-8b1699af847f.png)

I may have missed an instruction but I can't find what...

**Comment by Nicodile** [comment]
It seems that rustlings was not empty when you ran that command, I would delete it fully, then try to reinstall

**Comment by diannasoreil** [comment]
Yep, the installation script will abort if the `rustlings` folder already exists. Delete it or move to a different directory, then try again :)
