### ISSUE TITLE
requires nightly but no mention of this until after git clone

### ISSUE THREAD

**Issue by commandline-be** [rust-lang/rustlings#964]
git clone -b 4.7.0 https://github.com/rust-lang/rustlings.git
cd rustlings
cargo install --force --path .
error: failed to parse manifest at `/usr/src/rust/rustlings/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature

**Comment by diannasoreil** [comment]
Your Rust is probably not new enough to run the 2021 edition, check if `rustc --version` outputs 1.56.0 or higher.

**Comment by commandline-be** [comment]
Thanks, it does mention nightly features though.

**Comment by diannasoreil** [comment]
That's a bug in Cargo if anything, and unrelated to Rustlings, we simply use the `edition = "2021"` statement.

**Comment by commandline-be** [comment]
FYI : https://doc.rust-lang.org/nightly/edition-guide/rust-2021/index.html
