### ISSUE TITLE
clippy1 doesn't fail until I add deny to it

### ISSUE THREAD

**Issue by dhandy2013** [rust-lang/rustlings#977]
I had a difficult time with the clippy1 exercise, not because it was difficult to make it compile, but because it was difficult to make it fail to compile!

When I first ran the clippy1 exercise, it passed, without me needing to make any changes. After lots of googling I discovered that the clippy check that was supposed to fail was ``float_cmp``, which is [allowed by default](https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp). In order to make clippy1 fail I had to add this at the top of the file:
```rust
#![deny(clippy::float_cmp)]
```
Then finally it failed. After that I fixed it (again) by changing ``x == y`` to ``(y - x).abs() <= f64::EPSILON``.

This was an interesting exercise for someone like me who has 3+ years experience of Rust hobby programming, but it would probably be very difficult for a beginner.

I would suggest changing this exercise to either:
- Add the ``#![deny(clippy::float_cmp)]`` to clippy1.rs so that it fails at first
- Change the comments to let the student know that the first task is to make this exercise fail, before making it pass again. And maybe give the name of the lint (``float_cmp``) so the student knows what to search for.

**Comment by equal-l2** [comment]
This is not relevant to `main` branch at least because `clippy1.rs` is replaced with a new exercise.

**Comment by diannasoreil** [comment]
Yep, this should be fixed in >4.7.0.
