### ISSUE TITLE
Enum3: unable to complete through typical means

### ISSUE THREAD

**Issue by Nicodile** [rust-lang/rustlings#995]
Please bare with me as first issue ive ever created.

When doing Enum3 exercise I could not figure it out, I had to google a solution so I could remember how to do it later, However every solution did not work except for ones with information that was not covered within Rustlings nor within the Rust Handbook. For example, Only way I could I get it to work was by inputting these:

Part 1 of TODO
`enum Message {
    ChangeColor((u8, u8, u8)),
    Echo(String),
    Move(Point),
    Quit,
`
Part 2 
`    fn process(&mut self, message: Message) {
        match message {
            Message::ChangeColor(col) => self.change_color(col),
            Message::Echo(str) => self.echo(str),
            Message::Move(ptr) => self.move_position(ptr),
            Message::Quit => self.quit(),
        }
`

As the above snippet shows it has str(which I could be wrong on if that has shown up). But col and ptr are unknown. 
Again This was the only way to "Solve" it Below are the ones that are seemingly correct:
P1 of Todo
`
   ChangeColor(u8, u8, u8),
    Echo(String),
    Move{x: u8, y: u8},
    Quit`

`match message {
            Message::ChangeColor(r, g, b) => self.change_color((r, g, b)),
            Message::Echo(s) => self.echo(s),
            Message::Move{x, y} => self.move_position(Point{x, y}),
            Message::Quit => self.quit()`

Inputting these will make Rustlings watch fail. Below are my versions
`rustc 1.60.0 (7737e0b5c 2022-04-04)` Rustc
rustlings v4.7.0
`drwxr-xr-x    - krodin 13 May 07:30  .
drwx------    - krodin 13 May 05:53  ..
drwxr-xr-x    - krodin 13 May 07:30  .git
drwxr-xr-x    - krodin 18 Apr 07:04  exercises
drwxr-xr-x    - krodin 18 Apr 07:04  src
drwxr-xr-x    - krodin  2 May 06:36  target
drwxr-xr-x    - krodin 18 Apr 07:04  tests
.rw-r--r--  31k krodin 18 Apr 07:04  .all-contributorsrc
.rw-r--r--   88 krodin 18 Apr 07:04  .clog.toml
.rw-r--r--  102 krodin 18 Apr 07:04  .editorconfig
.rw-r--r--  117 krodin 18 Apr 07:04  .gitignore
.rw-r--r--  175 krodin 18 Apr 07:04  .gitpod.yml
.rw-r--r--  104 krodin 18 Apr 07:04  .replit
.rw-r--r--  38k krodin 18 Apr 07:04  AUTHORS.md
.rw-r--r--  19k krodin 18 Apr 07:04  Cargo.lock
.rw-r--r--  490 krodin 18 Apr 07:04  Cargo.toml
.rw-r--r--  37k krodin 18 Apr 07:04  CHANGELOG.md
.rw-r--r-- 4.2k krodin 18 Apr 07:04  CONTRIBUTING.md
.rw-r--r--  38k krodin 18 Apr 07:04  info.toml
.rw-r--r-- 3.0k krodin 18 Apr 07:04  install.ps1
.rwxr-xr-x 4.1k krodin 18 Apr 07:04  install.sh
.rw-r--r-- 1.1k krodin 18 Apr 07:04  LICENSE
.rw-r--r-- 6.8k krodin 18 Apr 07:04  README.md
`
ls -la
Garuda linux / Arch linux

**Comment by shaleh** [comment]
What would you like to see explained above and beyond https://doc.rust-lang.org/book/ch06-01-defining-an-enum.html?
The rustling example is pretty much a direct copy.

**Comment by shaleh** [comment]
Spoilers below.

```
diff --git a/exercises/enums/enums3.rs b/exercises/enums/enums3.rs
index 178b40c..4b4d437 100644
--- a/exercises/enums/enums3.rs
+++ b/exercises/enums/enums3.rs
@@ -1,10 +1,11 @@
 // enums3.rs
 // Address all the TODOs to make the tests pass!

-// I AM NOT DONE
-
 enum Message {
-    // TODO: implement the message variant types based on their usage below
+    Echo(String),
+    Move(Point),
+    ChangeColor((u8, u8, u8)),
+    Quit,
 }

 struct Point {
@@ -36,7 +37,12 @@ impl State {
     }

     fn process(&mut self, message: Message) {
-        // TODO: create a match expression to process the different message variants
+        match message {
+            Message::Echo(text) => self.echo(text),
+            Message::Move(point) => self.move_position(point),
+            Message::ChangeColor(tuple) => self.change_color(tuple),
+            Message::Quit => self.quit(),
+        }
     }
 }
```
There are two tasks in this lesson:
1. fill in the `Message` enum
2. fill in `process` to handle `Message`

The functions in `State` have names to match the `Message` enum tags which is intended to be a clue.

https://doc.rust-lang.org/book/ch06-02-match.html shows the `match` syntax. This is the next chapter after the one I referenced above.
