### ISSUE TITLE
VSCode integration is unexplained. Support of rust-analyzer broken

### ISSUE THREAD

**Issue by unreal79** [rust-lang/rustlings#997]
So, I expected to use **rustlings** as a no-hassle tool -- it's got 24k stars! Instead I've got a bunch of files with `main()` in them... **rustlings** is intended as a Rust newbie helper. Git-cloning is not a problem. Actually editing and running the exercises is.

1. How should I open files one by one in VSCode? What folder specifically?
- "rustlings" folder? But I'm immediately getting 100+ problems and not able to compile specific exercise. 
- "exercises" folder? Ok, It's better but what about compiling file I'm currently editing? Luckily VSCode is asking me to autogenerate launch.json after I manually created Cargo.toml file with `path = 'variables/variables1.rs'`  as suggested [deep in issues](https://github.com/rust-lang/rustlings/issues/443#issuecomment-657150623). Am I intended to edit Cargo.toml, delete and autogenerate launch.json every time?.. Very convenient!

2. Pasting `"rust-analyzer.cargo.features": ["exercises"]` in .vscode/settings.json gives me error: `Value is not accepted. Valid values: "all".` Wut?! Was it even tested?.. After setting it to "all", I'm getting errors it "tests" sub-folder -- so I have to rename "test" folder. Now I'm ready to exercise.

Currently I see **rustlings** as a CLI with basic functionality and set of assorted files, not a tool to learn Rust.

**Comment by Nicodile** [comment]
as per instructions, Change your directory to rustlings, then run rustlings watch.

**Comment by diannasoreil** [comment]
We don't support VSCode outside of the rust-analyzer stuff, so things such as creating a run configuration are not in our scope.

Other than that, this part of the README https://github.com/rust-lang/rustlings#doing-exercises explains how to run exercises in the recommended order.
