### ISSUE TITLE
install.sh checks for rustc and cargo but not rustup.

### ISSUE THREAD

**Issue by shaleh** [rust-lang/rustlings#999]
However, rustup is used at the end to install Clippy.
While it is likely uncommon to end up with rustc and cargo but not rustup it is possible.

**Comment by eirnym** [comment]
By the way, rust installation from distributions like mentionend above is one of recommended ways to install rust:

https://forge.rust-lang.org/infra/other-installation-methods.html

**Comment by shadows-withal** [comment]
The recommended way to install Rust has, and will likely always be rustup. I do agree that sometimes installing from distro package managers, or from source can be preferential, and I think we could probably provide an installation script flag to skip these rustup-specific checks.

**Comment by eirnym** [comment]
Please do. Rustling doesn't depend on nightly or other builds than stable. Tooling like clippy is important, and it's usually installed by a package manager

**Comment by shadows-withal** [comment]
>  Tooling like clippy is important, and it's usually installed by a package manager

Not quite true, the recommended way to install Clippy is via `rustup component add clippy` :) That doesn't detract from your point, though.

**Comment by mo8it** [comment]
Closing because the installation script will be removed by https://github.com/rust-lang/rustlings/issues/1919

After implementing https://github.com/rust-lang/rustlings/issues/1935, Cargo should tell the user to install Clippy.

**Comment by eirnym** [comment]
@mo8it FYI, clippy and some other tooling is installed by package managers during Rust installation. I hope new way to install wouldn't depend on Nightly
